// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// CloudUserAccount represents a F5XC CloudUserAccount
type CloudUserAccount struct {
	Metadata        Metadata               `json:"metadata"`
	Spec            map[string]interface{} `json:"spec"`
	ResourceVersion string                 `json:"resource_version,omitempty"`
}

// CreateCloudUserAccount creates a new CloudUserAccount
func (c *Client) CreateCloudUserAccount(ctx context.Context, resource *CloudUserAccount) (*CloudUserAccount, error) {
	var result CloudUserAccount
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_user_accounts", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetCloudUserAccount retrieves a CloudUserAccount
func (c *Client) GetCloudUserAccount(ctx context.Context, namespace, name string) (*CloudUserAccount, error) {
	var result CloudUserAccount
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_user_accounts/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateCloudUserAccount updates a CloudUserAccount
func (c *Client) UpdateCloudUserAccount(ctx context.Context, resource *CloudUserAccount) (*CloudUserAccount, error) {
	var result CloudUserAccount
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_user_accounts/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteCloudUserAccount deletes a CloudUserAccount
func (c *Client) DeleteCloudUserAccount(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_user_accounts/%s", namespace, name)
	return c.Delete(ctx, path)
}
