apiVersion: v1
kind: certificate
metadata:
  name: example-cert
  namespace: demo-app
spec:
  certificate_url: "string:///BASE64_ENCODED_CERTIFICATE"
  private_key:
    clear_secret_info:
      url: "string:///BASE64_ENCODED_PRIVATE_KEY"
      provider: ""
