apiVersion: v1
kind: healthcheck
metadata:
  name: http-health
  namespace: demo-app
spec:
  http_health_check:
    path: /health
    use_origin_server_name: {}
  interval: 15
  timeout: 3
  unhealthy_threshold: 1
  healthy_threshold: 3
  jitter_percent: 30
