apiVersion: v1
kind: protocol_inspection
metadata:
  name: example-inspection
  namespace: demo-app
spec:
  enable_disable_compliance_checks:
    disable_compliance_checks: {}
  enable_disable_signatures:
    enable_signature: {}
