apiVersion: v1
kind: waf_exclusion_policy
metadata:
  name: example-waf-exclusion
  namespace: demo-app
spec:
  waf_exclusion_rules:
    - metadata:
        name: exclude-health
      exact_path: "/health"
