// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC enriched API response-operation contract

package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
)

var _ datasource.DataSource = &AccessActiveSessionDataSource{}
var _ datasource.DataSourceWithConfigure = &AccessActiveSessionDataSource{}

func NewAccessActiveSessionDataSource() datasource.DataSource {
	return &AccessActiveSessionDataSource{}
}

type AccessActiveSessionDataSource struct{ client *client.Client }
type AccessActiveSessionDataSourceModel struct {
	ID               types.String `tfsdk:"id"`
	Namespace        types.String `tfsdk:"namespace"`
	ClientIP         types.String `tfsdk:"client_ip"`
	ExpirationTime   types.String `tfsdk:"expiration_time"`
	LastActivityTime types.String `tfsdk:"last_activity_time"`
	Policy           types.String `tfsdk:"policy"`
	Site             types.String `tfsdk:"site"`
	StartTime        types.String `tfsdk:"start_time"`
	Status           types.String `tfsdk:"status"`
	Username         types.String `tfsdk:"username"`
	Variables        types.List   `tfsdk:"variables"`
	VirtualServer    types.String `tfsdk:"virtual_server"`
}

// AccessActiveSessionEmptyModel represents empty nested blocks
type AccessActiveSessionEmptyModel struct {
}

// AccessActiveSessionVariablesModel represents variables block
type AccessActiveSessionVariablesModel struct {
	Value    types.String `tfsdk:"value"`
	Variable types.String `tfsdk:"variable"`
}

// AccessActiveSessionVariablesModelAttrTypes defines the attribute types for AccessActiveSessionVariablesModel
var AccessActiveSessionVariablesModelAttrTypes = map[string]attr.Type{
	"value":    types.StringType,
	"variable": types.StringType,
}

func (d *AccessActiveSessionDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_access_active_session"
}
func (d *AccessActiveSessionDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{MarkdownDescription: "Resource retrieval operation.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "ID ID of the session.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace Namespace of the App type for the current request.",
				Required:            true,
			},
			"client_ip": schema.StringAttribute{
				MarkdownDescription: "Client IP of the user that connected via the session.",
				Computed:            true,
			},
			"expiration_time": schema.StringAttribute{
				MarkdownDescription: "Expiration time of the session in RFC 3339 format.",
				Computed:            true,
			},
			"last_activity_time": schema.StringAttribute{
				MarkdownDescription: "Last activity time of the session in RFC 3339 format.",
				Computed:            true,
			},
			"policy": schema.StringAttribute{
				MarkdownDescription: "Policy. Policy associated with the session.",
				Computed:            true,
			},
			"site": schema.StringAttribute{
				MarkdownDescription: "Site. Site where the session is created.",
				Computed:            true,
			},
			"start_time": schema.StringAttribute{
				MarkdownDescription: "Start time of the session in RFC 3339 format.",
				Computed:            true,
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "[Enum: PENDING|ESTABLISHED] The actual status of an active session Session status is pending Session status is established. Possible values are `PENDING`, `ESTABLISHED`. Defaults to `PENDING`.",
				Computed:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("PENDING", "ESTABLISHED"),
				},
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Username used in authentication of this session.",
				Computed:            true,
			},
			"variables": schema.ListNestedAttribute{
				MarkdownDescription: "Variables. Session variables as key-value pairs.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"value": schema.StringAttribute{
							MarkdownDescription: "Variable Value. The value of the session variable.",
							Computed:            true,
						},
						"variable": schema.StringAttribute{
							MarkdownDescription: "Variable Name. The name of the session variable.",
							Computed:            true,
						},
					},
				},
				Computed: true,
			},
			"virtual_server": schema.StringAttribute{
				MarkdownDescription: "Virtual server associated with the session.",
				Computed:            true,
			},
		},
	}
}
func (d *AccessActiveSessionDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	configured, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = configured
}
func (d *AccessActiveSessionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data AccessActiveSessionDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiPath := "/api/data/namespaces/{namespace}/access/active-sessions/{id}"
	apiPath = strings.ReplaceAll(apiPath, "{id}", url.PathEscape(data.ID.ValueString()))
	apiPath = strings.ReplaceAll(apiPath, "{namespace}", url.PathEscape(data.Namespace.ValueString()))
	queryValues := url.Values{}
	if encoded := queryValues.Encode(); encoded != "" {
		apiPath += "?" + encoded
	}
	apiResult := map[string]interface{}{}
	if err := d.client.Get(ctx, apiPath, &apiResult); err != nil {
		resp.Diagnostics.AddError("Client Error", "Unable to invoke response operation. Raw API diagnostics are suppressed.")
		return
	}
	apiResource := struct{ Spec map[string]interface{} }{Spec: apiResult}
	isImport := true
	_ = isImport
	if err := client.ValidateResponseFields(apiResult, []client.ResponseField{
		{Name: "client_ip", Type: "string", Required: false, MinLength: 0, Format: "", Pattern: ""},
		{Name: "expiration_time", Type: "string", Required: false, MinLength: 0, Format: "date-time", Pattern: ""},
		{Name: "id", Type: "string", Required: false, MinLength: 0, Format: "", Pattern: ""},
		{Name: "last_activity_time", Type: "string", Required: false, MinLength: 0, Format: "date-time", Pattern: ""},
		{Name: "policy", Type: "string", Required: false, MinLength: 0, Format: "", Pattern: ""},
		{Name: "site", Type: "string", Required: false, MinLength: 0, Format: "", Pattern: ""},
		{Name: "start_time", Type: "string", Required: false, MinLength: 0, Format: "date-time", Pattern: ""},
		{Name: "status", Type: "", Required: false, MinLength: 17, Format: "", Pattern: ""},
		{Name: "username", Type: "string", Required: false, MinLength: 0, Format: "", Pattern: ""},
		{Name: "variables", Type: "array", Required: false, MinLength: 0, Format: "", Pattern: ""},
		{Name: "virtual_server", Type: "string", Required: false, MinLength: 0, Format: "", Pattern: ""},
	}); err != nil {
		resp.Diagnostics.AddError("Incomplete API Response", err.Error())
		return
	}
	if v, ok := apiResource.Spec["client_ip"].(string); ok && v != "" {
		data.ClientIP = types.StringValue(v)
	} else {
		data.ClientIP = types.StringNull()
	}
	if v, ok := apiResource.Spec["expiration_time"].(string); ok && v != "" {
		data.ExpirationTime = types.StringValue(v)
	} else {
		data.ExpirationTime = types.StringNull()
	}
	if v, ok := apiResource.Spec["last_activity_time"].(string); ok && v != "" {
		data.LastActivityTime = types.StringValue(v)
	} else {
		data.LastActivityTime = types.StringNull()
	}
	if v, ok := apiResource.Spec["policy"].(string); ok && v != "" {
		data.Policy = types.StringValue(v)
	} else {
		data.Policy = types.StringNull()
	}
	if v, ok := apiResource.Spec["site"].(string); ok && v != "" {
		data.Site = types.StringValue(v)
	} else {
		data.Site = types.StringNull()
	}
	if v, ok := apiResource.Spec["start_time"].(string); ok && v != "" {
		data.StartTime = types.StringValue(v)
	} else {
		data.StartTime = types.StringNull()
	}
	if v, ok := apiResource.Spec["status"].(string); ok && v != "" {
		data.Status = types.StringValue(v)
	} else {
		data.Status = types.StringNull()
	}
	if v, ok := apiResource.Spec["username"].(string); ok && v != "" {
		data.Username = types.StringValue(v)
	} else {
		data.Username = types.StringNull()
	}
	if !isImport && (data.Variables.IsNull() || len(data.Variables.Elements()) == 0) {
		data.Variables = types.ListNull(types.ObjectType{AttrTypes: AccessActiveSessionVariablesModelAttrTypes})
	} else if listData, ok := apiResource.Spec["variables"].([]interface{}); ok && len(listData) > 0 {
		var VariablesList []AccessActiveSessionVariablesModel
		var existingVariablesItems []AccessActiveSessionVariablesModel
		if !data.Variables.IsNull() && !data.Variables.IsUnknown() {
			data.Variables.ElementsAs(ctx, &existingVariablesItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				VariablesList = append(VariablesList, AccessActiveSessionVariablesModel{
					Value: func() types.String {
						if v, ok := itemMap["value"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Variable: func() types.String {
						if v, ok := itemMap["variable"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: AccessActiveSessionVariablesModelAttrTypes}, VariablesList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Variables = listVal
		}
	} else {
		data.Variables = types.ListNull(types.ObjectType{AttrTypes: AccessActiveSessionVariablesModelAttrTypes})
	}
	if v, ok := apiResource.Spec["virtual_server"].(string); ok && v != "" {
		data.VirtualServer = types.StringValue(v)
	} else {
		data.VirtualServer = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
