// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
)

var (
	_ datasource.DataSource              = &AlertTemplateDataSource{}
	_ datasource.DataSourceWithConfigure = &AlertTemplateDataSource{}
)

func NewAlertTemplateDataSource() datasource.DataSource {
	return &AlertTemplateDataSource{}
}

type AlertTemplateDataSource struct {
	client *client.Client
}

type AlertTemplateDataSourceModel struct {
	ID                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	Namespace           types.String `tfsdk:"namespace"`
	Description         types.String `tfsdk:"description"`
	Labels              types.Map    `tfsdk:"labels"`
	Annotations         types.Map    `tfsdk:"annotations"`
	AlertMessage        types.String `tfsdk:"alert_message"`
	AlertMessageDetails types.String `tfsdk:"alert_message_details"`
	AlertName           types.String `tfsdk:"alert_name"`
	Severity            types.String `tfsdk:"severity"`
}

func (d *AlertTemplateDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_alert_template"
}

func (d *AlertTemplateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages Domain to protect in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the AlertTemplate.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the AlertTemplate exists.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description of the AlertTemplate.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels applied to this resource.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations applied to this resource.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"alert_message": schema.StringAttribute{
				MarkdownDescription: "Alert Message. Alert Message.",
				Computed:            true,
			},
			"alert_message_details": schema.StringAttribute{
				MarkdownDescription: "Alert Message Details. Detailed message of the alert.",
				Computed:            true,
			},
			"alert_name": schema.StringAttribute{
				MarkdownDescription: "Alert Name. Alert Name.",
				Computed:            true,
			},
			"severity": schema.StringAttribute{
				MarkdownDescription: "[Enum: MINOR|MAJOR|CRITICAL] List of alert severities Minor Major Critical. Possible values are `MINOR`, `MAJOR`, `CRITICAL`. Defaults to `MINOR`.",
				Computed:            true,
			},
		},
	}
}

func (d *AlertTemplateDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *AlertTemplateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data AlertTemplateDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	namespace := data.Namespace.ValueString()
	resource, err := d.client.GetAlertTemplate(ctx, namespace, data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read AlertTemplate: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	if resource.Metadata.Namespace != "" {
		data.Namespace = types.StringValue(resource.Metadata.Namespace)
	} else {
		data.Namespace = types.StringValue(namespace)
	}
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Prefix filtering only, never the discovery labels (#1391). A data source cannot
	// propose deleting anything, so filtering them here would buy no convergence and
	// would only hide hw-model and friends from a caller that asked for the object.
	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels, false)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}
	apiResource := resource
	if v, ok := apiResource.Spec["alert_message"].(string); ok && v != "" {
		data.AlertMessage = types.StringValue(v)
	} else {
		data.AlertMessage = types.StringNull()
	}
	if v, ok := apiResource.Spec["alert_message_details"].(string); ok && v != "" {
		data.AlertMessageDetails = types.StringValue(v)
	} else {
		data.AlertMessageDetails = types.StringNull()
	}
	if v, ok := apiResource.Spec["alert_name"].(string); ok && v != "" {
		data.AlertName = types.StringValue(v)
	} else {
		data.AlertName = types.StringNull()
	}
	if v, ok := apiResource.Spec["severity"].(string); ok && v != "" {
		data.Severity = types.StringValue(v)
	} else {
		data.Severity = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
