// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC enriched API ephemeral-operation contract

package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
)

var _ ephemeral.EphemeralResource = &ArtifactRegistryTokenEphemeralResource{}
var _ ephemeral.EphemeralResourceWithConfigure = &ArtifactRegistryTokenEphemeralResource{}

func NewArtifactRegistryTokenEphemeralResource() ephemeral.EphemeralResource {
	return &ArtifactRegistryTokenEphemeralResource{}
}

type ArtifactRegistryTokenEphemeralResource struct{ client *client.Client }
type ArtifactRegistryTokenEphemeralResourceModel struct {
	Namespace      types.String `tfsdk:"namespace"`
	ExpirationTime types.String `tfsdk:"expiration_time"`
	Token          types.String `tfsdk:"token"`
}

func (e *ArtifactRegistryTokenEphemeralResource) Metadata(ctx context.Context, req ephemeral.MetadataRequest, resp *ephemeral.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_artifact_registry_token"
}
func (e *ArtifactRegistryTokenEphemeralResource) Schema(ctx context.Context, req ephemeral.SchemaRequest, resp *ephemeral.SchemaResponse) {
	resp.Schema = schema.Schema{MarkdownDescription: "Authentication credential for access control.",
		Attributes: map[string]schema.Attribute{
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace. Namespace is used to scope the query.",
				Required:            true,
			},
			"expiration_time": schema.StringAttribute{
				MarkdownDescription: "Expiration Time. Expiration time of the token.",
				Computed:            true,
				Sensitive:           true,
			},
			"token": schema.StringAttribute{
				MarkdownDescription: "Access token for the F5 Artifact Registry (FAR) This token can be used to authenticate with FAR when pulling related images for Kubernetes bot infrastructure.",
				Computed:            true,
				Sensitive:           true,
			},
		},
	}
}
func (e *ArtifactRegistryTokenEphemeralResource) Configure(ctx context.Context, req ephemeral.ConfigureRequest, resp *ephemeral.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	configured, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Ephemeral Resource Configure Type", "Expected *client.Client")
		return
	}
	e.client = configured
}
func (e *ArtifactRegistryTokenEphemeralResource) Open(ctx context.Context, req ephemeral.OpenRequest, resp *ephemeral.OpenResponse) {
	var data ArtifactRegistryTokenEphemeralResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiPath := "/api/shape/bot/namespaces/{namespace}/artifact-registry-token"
	apiPath = strings.ReplaceAll(apiPath, "{namespace}", url.PathEscape(data.Namespace.ValueString()))
	queryValues := url.Values{}
	if encoded := queryValues.Encode(); encoded != "" {
		apiPath += "?" + encoded
	}
	apiResult := map[string]interface{}{}
	if err := e.client.Get(ctx, apiPath, &apiResult); err != nil {
		resp.Diagnostics.AddError("Client Error", "Unable to invoke response operation. Raw API diagnostics are suppressed.")
		return
	}
	apiResource := struct{ Spec map[string]interface{} }{Spec: apiResult}
	isImport := true
	_ = isImport
	if err := client.ValidateResponseFields(apiResult, []client.ResponseField{
		{Name: "expiration_time", Type: "string", Required: false, MinLength: 0, Format: "date-time", Pattern: ""},
		{Name: "token", Type: "string", Required: false, MinLength: 0, Format: "", Pattern: ""},
	}); err != nil {
		resp.Diagnostics.AddError("Incomplete API Response", err.Error())
		return
	}
	if v, ok := apiResource.Spec["expiration_time"].(string); ok && v != "" {
		data.ExpirationTime = types.StringValue(v)
	} else {
		data.ExpirationTime = types.StringNull()
	}
	if v, ok := apiResource.Spec["token"].(string); ok && v != "" {
		data.Token = types.StringValue(v)
	} else {
		data.Token = types.StringNull()
	}
	resp.Diagnostics.Append(resp.Result.Set(ctx, &data)...)
}
