// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
	xcsherrors "github.com/f5-sales-demo/terraform-provider-xcsh/internal/errors"
	inttimeouts "github.com/f5-sales-demo/terraform-provider-xcsh/internal/timeouts"
	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &BGPRoutingPolicyResource{}
	_ resource.ResourceWithConfigure      = &BGPRoutingPolicyResource{}
	_ resource.ResourceWithImportState    = &BGPRoutingPolicyResource{}
	_ resource.ResourceWithModifyPlan     = &BGPRoutingPolicyResource{}
	_ resource.ResourceWithValidateConfig = &BGPRoutingPolicyResource{}
)

func NewBGPRoutingPolicyResource() resource.Resource {
	return &BGPRoutingPolicyResource{}
}

type BGPRoutingPolicyResource struct {
	client *client.Client
}

// BGPRoutingPolicyEmptyModel represents empty nested blocks
type BGPRoutingPolicyEmptyModel struct {
}

// BGPRoutingPolicyRulesModel represents rules block
type BGPRoutingPolicyRulesModel struct {
	Action *BGPRoutingPolicyRulesActionModel `tfsdk:"action"`
	Match  *BGPRoutingPolicyRulesMatchModel  `tfsdk:"match"`
}

// BGPRoutingPolicyRulesModelAttrTypes defines the attribute types for BGPRoutingPolicyRulesModel
var BGPRoutingPolicyRulesModelAttrTypes = map[string]attr.Type{
	"action": types.ObjectType{AttrTypes: BGPRoutingPolicyRulesActionModelAttrTypes},
	"match":  types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchModelAttrTypes},
}

// BGPRoutingPolicyRulesActionModel represents action block
type BGPRoutingPolicyRulesActionModel struct {
	AsPath          types.String                               `tfsdk:"as_path"`
	LocalPreference types.Int64                                `tfsdk:"local_preference"`
	Metric          types.Int64                                `tfsdk:"metric"`
	Allow           *BGPRoutingPolicyEmptyModel                `tfsdk:"allow"`
	Community       *BGPRoutingPolicyRulesActionCommunityModel `tfsdk:"community"`
	Deny            *BGPRoutingPolicyEmptyModel                `tfsdk:"deny"`
}

// BGPRoutingPolicyRulesActionModelAttrTypes defines the attribute types for BGPRoutingPolicyRulesActionModel
var BGPRoutingPolicyRulesActionModelAttrTypes = map[string]attr.Type{
	"as_path":          types.StringType,
	"local_preference": types.Int64Type,
	"metric":           types.Int64Type,
	"allow":            types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"community":        types.ObjectType{AttrTypes: BGPRoutingPolicyRulesActionCommunityModelAttrTypes},
	"deny":             types.ObjectType{AttrTypes: map[string]attr.Type{}},
}

// BGPRoutingPolicyRulesActionCommunityModel represents community block
type BGPRoutingPolicyRulesActionCommunityModel struct {
	Community types.List `tfsdk:"community"`
}

// BGPRoutingPolicyRulesActionCommunityModelAttrTypes defines the attribute types for BGPRoutingPolicyRulesActionCommunityModel
var BGPRoutingPolicyRulesActionCommunityModelAttrTypes = map[string]attr.Type{
	"community": types.ListType{ElemType: types.StringType},
}

// BGPRoutingPolicyRulesMatchModel represents match block
type BGPRoutingPolicyRulesMatchModel struct {
	AsPath     types.String                               `tfsdk:"as_path"`
	Community  *BGPRoutingPolicyRulesMatchCommunityModel  `tfsdk:"community"`
	IPPrefixes *BGPRoutingPolicyRulesMatchIPPrefixesModel `tfsdk:"ip_prefixes"`
}

// BGPRoutingPolicyRulesMatchModelAttrTypes defines the attribute types for BGPRoutingPolicyRulesMatchModel
var BGPRoutingPolicyRulesMatchModelAttrTypes = map[string]attr.Type{
	"as_path":     types.StringType,
	"community":   types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchCommunityModelAttrTypes},
	"ip_prefixes": types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesModelAttrTypes},
}

// BGPRoutingPolicyRulesMatchCommunityModel represents community block
type BGPRoutingPolicyRulesMatchCommunityModel struct {
	Community types.List `tfsdk:"community"`
}

// BGPRoutingPolicyRulesMatchCommunityModelAttrTypes defines the attribute types for BGPRoutingPolicyRulesMatchCommunityModel
var BGPRoutingPolicyRulesMatchCommunityModelAttrTypes = map[string]attr.Type{
	"community": types.ListType{ElemType: types.StringType},
}

// BGPRoutingPolicyRulesMatchIPPrefixesModel represents ip_prefixes block
type BGPRoutingPolicyRulesMatchIPPrefixesModel struct {
	Prefixes types.List `tfsdk:"prefixes"`
}

// BGPRoutingPolicyRulesMatchIPPrefixesModelAttrTypes defines the attribute types for BGPRoutingPolicyRulesMatchIPPrefixesModel
var BGPRoutingPolicyRulesMatchIPPrefixesModelAttrTypes = map[string]attr.Type{
	"prefixes": types.ListType{ElemType: types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes}},
}

// BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel represents prefixes block
type BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel struct {
	IPPrefixes        types.String                `tfsdk:"ip_prefixes"`
	EqualOrLongerThan *BGPRoutingPolicyEmptyModel `tfsdk:"equal_or_longer_than"`
	ExactMatch        *BGPRoutingPolicyEmptyModel `tfsdk:"exact_match"`
	LongerThan        *BGPRoutingPolicyEmptyModel `tfsdk:"longer_than"`
}

// BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes defines the attribute types for BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
var BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes = map[string]attr.Type{
	"ip_prefixes":          types.StringType,
	"equal_or_longer_than": types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"exact_match":          types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"longer_than":          types.ObjectType{AttrTypes: map[string]attr.Type{}},
}

type BGPRoutingPolicyResourceModel struct {
	Name        types.String   `tfsdk:"name"`
	Namespace   types.String   `tfsdk:"namespace"`
	Annotations types.Map      `tfsdk:"annotations"`
	Description types.String   `tfsdk:"description"`
	Disable     types.Bool     `tfsdk:"disable"`
	Labels      types.Map      `tfsdk:"labels"`
	ID          types.String   `tfsdk:"id"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
	Rules       types.List     `tfsdk:"rules"`
}

func (r *BGPRoutingPolicyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_bgp_routing_policy"
}

func (r *BGPRoutingPolicyResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a BGP Routing Policy resource in F5 Distributed Cloud for bgp routing policy is a list of rules containing match criteria and action to be applied. these rules help control routes which are imported or exported to bgp peers. configuration.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the BGP Routing Policy. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the BGP Routing Policy is created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true administratively disables the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"rules": schema.ListNestedBlock{
				MarkdownDescription: "BGP Routing policy is composed of one or more rules. Note that the order of rules is critical as rules are applied top to bottom.",

				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{},
					Blocks: map[string]schema.Block{
						"action": schema.SingleNestedBlock{
							MarkdownDescription: "Action to be enforced if the BGP route matches the rule.",
							Attributes: map[string]schema.Attribute{
								"as_path": schema.StringAttribute{
									MarkdownDescription: "Exclusive with [allow community deny local_preference metric] AS-Path Prepending is generally used to influence incoming traffic.",
									Optional:            true,
								},
								"local_preference": schema.Int64Attribute{
									MarkdownDescription: "Exclusive with [allow as_path community deny metric] BGP Local Preference is generally used to influence outgoing traffic.",
									Optional:            true,
								},
								"metric": schema.Int64Attribute{
									MarkdownDescription: "Exclusive with [allow as_path community deny local_preference] The Multi-Exit Discriminator metric to indicate the preferred path to AS.",
									Optional:            true,
								},
							},
							Blocks: map[string]schema.Block{
								"allow": schema.SingleNestedBlock{
									MarkdownDescription: "Enable this option",
								},
								"community": schema.SingleNestedBlock{
									MarkdownDescription: "BGP Community list. List of BGP communities.",
									Validators:          []validator.Object{validators.RequiredObjectAttributes("community")},
									Attributes: map[string]schema.Attribute{
										"community": schema.ListAttribute{
											MarkdownDescription: "Unordered set of RFC 1997 defined 4-byte community, first 16 bits being ASN and lower 16 bits being value.",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeBetween(1, 8),
											},
										},
									},
								},
								"deny": schema.SingleNestedBlock{
									MarkdownDescription: "Enable this option",
								},
							},
						},
						"match": schema.SingleNestedBlock{
							MarkdownDescription: "Predicates which have to match information in route for action to be applied.",
							Attributes: map[string]schema.Attribute{
								"as_path": schema.StringAttribute{
									MarkdownDescription: "Exclusive with [community ip_prefixes] AS path can also be a regex, which will be matched against route information.",
									Optional:            true,
								},
							},
							Blocks: map[string]schema.Block{
								"community": schema.SingleNestedBlock{
									MarkdownDescription: "BGP Community list. List of BGP communities.",
									Validators:          []validator.Object{validators.RequiredObjectAttributes("community")},
									Attributes: map[string]schema.Attribute{
										"community": schema.ListAttribute{
											MarkdownDescription: "Unordered set of RFC 1997 defined 4-byte community, first 16 bits being ASN and lower 16 bits being value.",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeBetween(1, 8),
											},
										},
									},
								},
								"ip_prefixes": schema.SingleNestedBlock{
									MarkdownDescription: "List of IP prefix and prefix length range match condition.",
									Validators:          []validator.Object{validators.RequiredObjectAttributes("prefixes")},
									Attributes:          map[string]schema.Attribute{},
									Blocks: map[string]schema.Block{
										"prefixes": schema.ListNestedBlock{
											MarkdownDescription: "Prefix list. List of IP prefix.",
											NestedObject: schema.NestedBlockObject{
												Attributes: map[string]schema.Attribute{
													"ip_prefixes": schema.StringAttribute{
														MarkdownDescription: "IP Prefix. IP prefix to match on BGP route.",
														Optional:            true,
														Validators: []validator.String{
															stringvalidator.LengthAtMost(1024),
															validators.CIDRValidator(),
														},
													},
												},
												Blocks: map[string]schema.Block{
													"equal_or_longer_than": schema.SingleNestedBlock{
														MarkdownDescription: "Configuration parameter for equal or longer than.",
													},
													"exact_match": schema.SingleNestedBlock{
														MarkdownDescription: "Configuration parameter for exact match.",
													},
													"longer_than": schema.SingleNestedBlock{
														MarkdownDescription: "Configuration parameter for longer than.",
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *BGPRoutingPolicyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *BGPRoutingPolicyResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data BGPRoutingPolicyResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *BGPRoutingPolicyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This permanently deletes the bgp_routing_policy from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan BGPRoutingPolicyResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *BGPRoutingPolicyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data BGPRoutingPolicyResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating bgp_routing_policy", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.BGPRoutingPolicy{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	// Capture which label keys the configuration declared, so Read can tell a label this
	// configuration owns from one the platform added (#1398). Create and Update are the
	// only places the configuration is visible; Read sees prior state, and prior state is
	// not evidence of ownership because providers up to 3.81.1 wrote the platform's own
	// labels into it.
	//
	// Captured here, written to private state only after the API call succeeds — see the
	// note at the write site.
	ownedLabelKeys, ownedLabelErr := encodeOwnedLabelKeys(configLabelKeys(createReq.Metadata.Labels))
	if ownedLabelErr != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Owned Label Keys",
			"Could not encode the configuration's label keys for private state: "+ownedLabelErr.Error()+
				"\n\nWithout this record the read-back cannot distinguish a label this "+
				"configuration owns from one the platform authored, and a label in the "+
				"ves.io/ namespace would never converge.",
		)
		return
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.Rules.IsNull() && !data.Rules.IsUnknown() {
		var RulesElems []BGPRoutingPolicyRulesModel
		diags := data.Rules.ElementsAs(ctx, &RulesElems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(RulesElems) > 0 {
			var RulesList []map[string]interface{}
			for _, RulesItem := range RulesElems {
				RulesItemMap := make(map[string]interface{})
				if RulesItem.Action != nil {
					RulesActionMap := make(map[string]interface{})
					if RulesItem.Action.Allow != nil {
						RulesActionMap["allow"] = map[string]interface{}{}
					}
					if !RulesItem.Action.AsPath.IsNull() && !RulesItem.Action.AsPath.IsUnknown() {
						RulesActionMap["as_path"] = RulesItem.Action.AsPath.ValueString()
					}
					if RulesItem.Action.Community != nil {
						RulesActionCommunityMap := make(map[string]interface{})
						if !RulesItem.Action.Community.Community.IsNull() && !RulesItem.Action.Community.Community.IsUnknown() {
							var CommunityItems []string
							diags := RulesItem.Action.Community.Community.ElementsAs(ctx, &CommunityItems, false)
							resp.Diagnostics.Append(diags...)
							if !diags.HasError() {
								RulesActionCommunityMap["community"] = CommunityItems
							}
						}
						RulesActionMap["community"] = RulesActionCommunityMap
					}
					if RulesItem.Action.Deny != nil {
						RulesActionMap["deny"] = map[string]interface{}{}
					}
					if !RulesItem.Action.LocalPreference.IsNull() && !RulesItem.Action.LocalPreference.IsUnknown() {
						RulesActionMap["local_preference"] = RulesItem.Action.LocalPreference.ValueInt64()
					}
					if !RulesItem.Action.Metric.IsNull() && !RulesItem.Action.Metric.IsUnknown() {
						RulesActionMap["metric"] = RulesItem.Action.Metric.ValueInt64()
					}
					RulesItemMap["action"] = RulesActionMap
				}
				if RulesItem.Match != nil {
					RulesMatchMap := make(map[string]interface{})
					if !RulesItem.Match.AsPath.IsNull() && !RulesItem.Match.AsPath.IsUnknown() {
						RulesMatchMap["as_path"] = RulesItem.Match.AsPath.ValueString()
					}
					if RulesItem.Match.Community != nil {
						RulesMatchCommunityMap := make(map[string]interface{})
						if !RulesItem.Match.Community.Community.IsNull() && !RulesItem.Match.Community.Community.IsUnknown() {
							var CommunityItems []string
							diags := RulesItem.Match.Community.Community.ElementsAs(ctx, &CommunityItems, false)
							resp.Diagnostics.Append(diags...)
							if !diags.HasError() {
								RulesMatchCommunityMap["community"] = CommunityItems
							}
						}
						RulesMatchMap["community"] = RulesMatchCommunityMap
					}
					if RulesItem.Match.IPPrefixes != nil {
						RulesMatchIPPrefixesMap := make(map[string]interface{})
						if !RulesItem.Match.IPPrefixes.Prefixes.IsNull() && !RulesItem.Match.IPPrefixes.Prefixes.IsUnknown() {
							var PrefixesElems []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
							diags := RulesItem.Match.IPPrefixes.Prefixes.ElementsAs(ctx, &PrefixesElems, false)
							resp.Diagnostics.Append(diags...)
							if !resp.Diagnostics.HasError() && len(PrefixesElems) > 0 {
								var PrefixesList []map[string]interface{}
								for _, PrefixesItem := range PrefixesElems {
									PrefixesItemMap := make(map[string]interface{})
									if PrefixesItem.EqualOrLongerThan != nil {
										PrefixesItemMap["equal_or_longer_than"] = map[string]interface{}{}
									}
									if PrefixesItem.ExactMatch != nil {
										PrefixesItemMap["exact_match"] = map[string]interface{}{}
									}
									if !PrefixesItem.IPPrefixes.IsNull() && !PrefixesItem.IPPrefixes.IsUnknown() {
										PrefixesItemMap["ip_prefixes"] = PrefixesItem.IPPrefixes.ValueString()
									}
									if PrefixesItem.LongerThan != nil {
										PrefixesItemMap["longer_than"] = map[string]interface{}{}
									}
									PrefixesList = append(PrefixesList, PrefixesItemMap)
								}
								RulesMatchIPPrefixesMap["prefixes"] = PrefixesList
							}
						}
						RulesMatchMap["ip_prefixes"] = RulesMatchIPPrefixesMap
					}
					RulesItemMap["match"] = RulesMatchMap
				}
				RulesList = append(RulesList, RulesItemMap)
			}
			createReq.Spec["rules"] = RulesList
		}
	}

	_, err := r.client.CreateBGPRoutingPolicy(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create BGPRoutingPolicy: %s", err))
		return
	}

	// The concurrency token is declared only on GET responses. Read back the object
	// after creation and record that exact server-assigned value for the next replace.
	apiResource, err := r.client.GetBGPRoutingPolicy(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Concurrency Token After Create",
			fmt.Sprintf("The object was created, but its server-assigned concurrency token could not be read. Refresh the resource before updating it: %s", err),
		)
		return
	}
	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(apiResource.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Record Concurrency Token After Create", tokenErr.Error())
		return
	}

	// Only now that the write has landed. terraform-plugin-framework persists private
	// state even when the method returns an error (it copies createResp.Private into the
	// response before checking diagnostics), so recording ownership earlier would claim
	// keys the server never received.
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, ownedLabelKeysPrivateKey, ownedLabelKeys)...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if !isImport && (data.Rules.IsNull() || len(data.Rules.Elements()) == 0) {
		data.Rules = types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes})
	} else if listData, ok := apiResource.Spec["rules"].([]interface{}); ok && len(listData) > 0 {
		var RulesList []BGPRoutingPolicyRulesModel
		var existingRulesItems []BGPRoutingPolicyRulesModel
		if !data.Rules.IsNull() && !data.Rules.IsUnknown() {
			data.Rules.ElementsAs(ctx, &existingRulesItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				RulesList = append(RulesList, BGPRoutingPolicyRulesModel{
					Action: func() *BGPRoutingPolicyRulesActionModel {
						if ActionData, ok := itemMap["action"].(map[string]interface{}); ok {
							return &BGPRoutingPolicyRulesActionModel{
								Allow: func() *BGPRoutingPolicyEmptyModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil {
										return existingRulesItems[listIdx].Action.Allow
									}
									if _, ok := ActionData["allow"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyEmptyModel{}
									}
									return nil
								}(),
								AsPath: func() types.String {
									if v, ok := ActionData["as_path"].(string); ok && v != "" {
										return types.StringValue(v)
									}
									return types.StringNull()
								}(),
								Community: func() *BGPRoutingPolicyRulesActionCommunityModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && existingRulesItems[listIdx].Action.Community != nil {
										return existingRulesItems[listIdx].Action.Community
									}
									if CommunityData, ok := ActionData["community"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesActionCommunityModel{
											Community: func() types.List {
												if v, ok := CommunityData["community"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, diags := types.ListValueFrom(ctx, types.StringType, items)
													resp.Diagnostics.Append(diags...)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								Deny: func() *BGPRoutingPolicyEmptyModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil {
										return existingRulesItems[listIdx].Action.Deny
									}
									if _, ok := ActionData["deny"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyEmptyModel{}
									}
									return nil
								}(),
								LocalPreference: func() types.Int64 {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && !existingRulesItems[listIdx].Action.LocalPreference.IsUnknown() {
										return existingRulesItems[listIdx].Action.LocalPreference
									}
									if v, ok := ActionData["local_preference"].(float64); ok && v != 0 {
										return types.Int64Value(int64(v))
									}
									return types.Int64Null()
								}(),
								Metric: func() types.Int64 {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && !existingRulesItems[listIdx].Action.Metric.IsUnknown() {
										return existingRulesItems[listIdx].Action.Metric
									}
									if v, ok := ActionData["metric"].(float64); ok && v != 0 {
										return types.Int64Value(int64(v))
									}
									return types.Int64Null()
								}(),
							}
						}
						return nil
					}(),
					Match: func() *BGPRoutingPolicyRulesMatchModel {
						if MatchData, ok := itemMap["match"].(map[string]interface{}); ok {
							return &BGPRoutingPolicyRulesMatchModel{
								AsPath: func() types.String {
									if v, ok := MatchData["as_path"].(string); ok && v != "" {
										return types.StringValue(v)
									}
									return types.StringNull()
								}(),
								Community: func() *BGPRoutingPolicyRulesMatchCommunityModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.Community != nil {
										return existingRulesItems[listIdx].Match.Community
									}
									if CommunityData, ok := MatchData["community"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesMatchCommunityModel{
											Community: func() types.List {
												if v, ok := CommunityData["community"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, diags := types.ListValueFrom(ctx, types.StringType, items)
													resp.Diagnostics.Append(diags...)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								IPPrefixes: func() *BGPRoutingPolicyRulesMatchIPPrefixesModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil {
										return existingRulesItems[listIdx].Match.IPPrefixes
									}
									if IPPrefixesData, ok := MatchData["ip_prefixes"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesMatchIPPrefixesModel{
											Prefixes: func() types.List {
												if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil && (existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsNull() || len(existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.Elements()) == 0) {
													return types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes})
												}
												var PrefixesExisting []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
												if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil && !existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsNull() && !existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsUnknown() {
													existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.ElementsAs(ctx, &PrefixesExisting, false)
												}
												if rawList, ok := IPPrefixesData["prefixes"].([]interface{}); ok && len(rawList) > 0 {
													var PrefixesResult []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
													for PrefixesIdx, PrefixesItem := range rawList {
														_ = PrefixesIdx
														if PrefixesItemMap, ok := PrefixesItem.(map[string]interface{}); ok {
															PrefixesResult = append(PrefixesResult, BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel{
																EqualOrLongerThan: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].EqualOrLongerThan
																	}
																	if _, ok := PrefixesItemMap["equal_or_longer_than"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
																ExactMatch: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].ExactMatch
																	}
																	if _, ok := PrefixesItemMap["exact_match"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
																IPPrefixes: func() types.String {
																	if v, ok := PrefixesItemMap["ip_prefixes"].(string); ok && v != "" {
																		return types.StringValue(v)
																	}
																	return types.StringNull()
																}(),
																LongerThan: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].LongerThan
																	}
																	if _, ok := PrefixesItemMap["longer_than"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
															})
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes}, PrefixesResult)
													return listVal
												}
												return types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes})
											}(),
										}
									}
									return nil
								}(),
							}
						}
						return nil
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes}, RulesList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Rules = listVal
		}
	} else {
		data.Rules = types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes})
	}

	tflog.Trace(ctx, "created BGPRoutingPolicy resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *BGPRoutingPolicyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data BGPRoutingPolicyResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetBGPRoutingPolicy(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "BGPRoutingPolicy not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		// Some F5 XC APIs do not implement GET-by-name (read returns 501 Not
		// Implemented — e.g. the shape/csd domain objects, which support only
		// list/create/delete). Treat that as "cannot refresh" and preserve the
		// prior state rather than erroring, so the resource stays manageable and
		// idempotent (create/delete still work).
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "BGPRoutingPolicy read not implemented by API (501); keeping prior state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read BGPRoutingPolicy: %s", err))
		return
	}

	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(apiResource.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Refresh Concurrency Token", tokenErr.Error())
		return
	}
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// #1286: the API omits an empty metadata map entirely, so "no entries in the
	// response" is ambiguous — it means either "never declared" or "declared empty".
	// Nulling both makes a config that declares labels = {} drift (+ labels = {}) on
	// every plan after apply, with no import involved. Resolve it from the prior
	// value: a known-empty prior map stays an empty map, anything else (null = never
	// declared, or unknown) becomes null. A prior map WITH entries still nulls, so a
	// genuine out-of-band deletion is still reported as drift.
	// The MapValueMust below cannot panic: it panics only on diagnostics, and with nil
	// elements NewMapValue's sole error path (per-element type mismatch) is unreachable.
	priorLabelsEmpty := !data.Labels.IsNull() && !data.Labels.IsUnknown() && len(data.Labels.Elements()) == 0
	priorAnnotationsEmpty := !data.Annotations.IsNull() && !data.Annotations.IsUnknown() && len(data.Annotations.Elements()) == 0

	// Filter out the labels the platform authors itself, which Terraform must not
	// propose deleting just because the configuration does not mention them (#1391) —
	// except any key the configuration declared at the last Create or Update, recorded
	// in private state. Without that exemption a configuration cannot own a label in the
	// ves.io/ namespace at all: the write succeeds, the read-back strips it, and the next
	// plan proposes adding it again, forever (#1398). Prior state cannot serve as the
	// record, because providers up to 3.81.1 wrote the platform's own labels into it.
	ownedLabels := map[string]struct{}{}
	if rawOwned, ownedDiags := req.Private.GetKey(ctx, ownedLabelKeysPrivateKey); !ownedDiags.HasError() {
		ownedLabels = decodeOwnedLabelKeys(rawOwned)
	}
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabelsOwning(apiResource.Metadata.Labels, false, ownedLabels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else if priorLabelsEmpty {
			data.Labels = types.MapValueMust(types.StringType, nil)
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else if priorLabelsEmpty {
		data.Labels = types.MapValueMust(types.StringType, nil)
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else if priorAnnotationsEmpty {
		data.Annotations = types.MapValueMust(types.StringType, nil)
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if !isImport && (data.Rules.IsNull() || len(data.Rules.Elements()) == 0) {
		data.Rules = types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes})
	} else if listData, ok := apiResource.Spec["rules"].([]interface{}); ok && len(listData) > 0 {
		var RulesList []BGPRoutingPolicyRulesModel
		var existingRulesItems []BGPRoutingPolicyRulesModel
		if !data.Rules.IsNull() && !data.Rules.IsUnknown() {
			data.Rules.ElementsAs(ctx, &existingRulesItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				RulesList = append(RulesList, BGPRoutingPolicyRulesModel{
					Action: func() *BGPRoutingPolicyRulesActionModel {
						if ActionData, ok := itemMap["action"].(map[string]interface{}); ok {
							return &BGPRoutingPolicyRulesActionModel{
								Allow: func() *BGPRoutingPolicyEmptyModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil {
										return existingRulesItems[listIdx].Action.Allow
									}
									if _, ok := ActionData["allow"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyEmptyModel{}
									}
									return nil
								}(),
								AsPath: func() types.String {
									if v, ok := ActionData["as_path"].(string); ok && v != "" {
										return types.StringValue(v)
									}
									return types.StringNull()
								}(),
								Community: func() *BGPRoutingPolicyRulesActionCommunityModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && existingRulesItems[listIdx].Action.Community != nil {
										return existingRulesItems[listIdx].Action.Community
									}
									if CommunityData, ok := ActionData["community"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesActionCommunityModel{
											Community: func() types.List {
												if v, ok := CommunityData["community"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, diags := types.ListValueFrom(ctx, types.StringType, items)
													resp.Diagnostics.Append(diags...)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								Deny: func() *BGPRoutingPolicyEmptyModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil {
										return existingRulesItems[listIdx].Action.Deny
									}
									if _, ok := ActionData["deny"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyEmptyModel{}
									}
									return nil
								}(),
								LocalPreference: func() types.Int64 {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && !existingRulesItems[listIdx].Action.LocalPreference.IsUnknown() {
										return existingRulesItems[listIdx].Action.LocalPreference
									}
									if v, ok := ActionData["local_preference"].(float64); ok && v != 0 {
										return types.Int64Value(int64(v))
									}
									return types.Int64Null()
								}(),
								Metric: func() types.Int64 {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && !existingRulesItems[listIdx].Action.Metric.IsUnknown() {
										return existingRulesItems[listIdx].Action.Metric
									}
									if v, ok := ActionData["metric"].(float64); ok && v != 0 {
										return types.Int64Value(int64(v))
									}
									return types.Int64Null()
								}(),
							}
						}
						return nil
					}(),
					Match: func() *BGPRoutingPolicyRulesMatchModel {
						if MatchData, ok := itemMap["match"].(map[string]interface{}); ok {
							return &BGPRoutingPolicyRulesMatchModel{
								AsPath: func() types.String {
									if v, ok := MatchData["as_path"].(string); ok && v != "" {
										return types.StringValue(v)
									}
									return types.StringNull()
								}(),
								Community: func() *BGPRoutingPolicyRulesMatchCommunityModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.Community != nil {
										return existingRulesItems[listIdx].Match.Community
									}
									if CommunityData, ok := MatchData["community"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesMatchCommunityModel{
											Community: func() types.List {
												if v, ok := CommunityData["community"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, diags := types.ListValueFrom(ctx, types.StringType, items)
													resp.Diagnostics.Append(diags...)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								IPPrefixes: func() *BGPRoutingPolicyRulesMatchIPPrefixesModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil {
										return existingRulesItems[listIdx].Match.IPPrefixes
									}
									if IPPrefixesData, ok := MatchData["ip_prefixes"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesMatchIPPrefixesModel{
											Prefixes: func() types.List {
												if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil && (existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsNull() || len(existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.Elements()) == 0) {
													return types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes})
												}
												var PrefixesExisting []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
												if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil && !existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsNull() && !existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsUnknown() {
													existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.ElementsAs(ctx, &PrefixesExisting, false)
												}
												if rawList, ok := IPPrefixesData["prefixes"].([]interface{}); ok && len(rawList) > 0 {
													var PrefixesResult []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
													for PrefixesIdx, PrefixesItem := range rawList {
														_ = PrefixesIdx
														if PrefixesItemMap, ok := PrefixesItem.(map[string]interface{}); ok {
															PrefixesResult = append(PrefixesResult, BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel{
																EqualOrLongerThan: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].EqualOrLongerThan
																	}
																	if _, ok := PrefixesItemMap["equal_or_longer_than"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
																ExactMatch: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].ExactMatch
																	}
																	if _, ok := PrefixesItemMap["exact_match"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
																IPPrefixes: func() types.String {
																	if v, ok := PrefixesItemMap["ip_prefixes"].(string); ok && v != "" {
																		return types.StringValue(v)
																	}
																	return types.StringNull()
																}(),
																LongerThan: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].LongerThan
																	}
																	if _, ok := PrefixesItemMap["longer_than"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
															})
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes}, PrefixesResult)
													return listVal
												}
												return types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes})
											}(),
										}
									}
									return nil
								}(),
							}
						}
						return nil
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes}, RulesList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Rules = listVal
		}
	} else {
		data.Rules = types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes})
	}

	// The import marker is a one-shot signal for the import Read only. Clear it so every
	// subsequent refresh runs as a normal Read with drift-preservation; otherwise the
	// resource stays in "import mode" forever and re-reads server-managed fields the user
	// never configured, producing perpetual plan drift.
	if isImport {
		resp.Diagnostics.Append(resp.Private.SetKey(ctx, "isImport", nil)...)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *BGPRoutingPolicyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data BGPRoutingPolicyResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	rawConcurrencyToken, tokenDiags := req.Private.GetKey(ctx, concurrencyTokenPrivateKey)
	resp.Diagnostics.Append(tokenDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	concurrencyToken, tokenErr := decodeConcurrencyToken(rawConcurrencyToken)
	if tokenErr != nil {
		resp.Diagnostics.AddError(
			"Refresh Required Before Update",
			"The update was not sent because this resource has no usable concurrency token from its last read. Run terraform refresh (or terraform plan with refresh enabled), review the refreshed configuration, and apply again. The provider will not fetch and silently adopt a newer token during a write. Details: "+tokenErr.Error(),
		)
		return
	}

	apiResource := &client.BGPRoutingPolicy{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}
	apiResource.ResourceVersion = concurrencyToken

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	// Re-capture ownership on every update, because the configuration's label set can
	// change: a key added here becomes owned, and a key removed stops being owned so the
	// next Read filters it again if it lives in a platform namespace (#1398).
	//
	// Captured HERE, before the platform's own discovery labels are merged in below —
	// merging first would record those as configuration-owned and reintroduce exactly the
	// #1391 bug this pairs with. Written to private state only after the API call
	// succeeds; see the note at the write site.
	ownedLabelKeys, ownedLabelErr := encodeOwnedLabelKeys(configLabelKeys(apiResource.Metadata.Labels))
	if ownedLabelErr != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Owned Label Keys",
			"Could not encode the configuration's label keys for private state: "+ownedLabelErr.Error()+
				"\n\nWithout this record the read-back cannot distinguish a label this "+
				"configuration owns from one the platform authored, and a label in the "+
				"ves.io/ namespace would never converge.",
		)
		return
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.Rules.IsNull() && !data.Rules.IsUnknown() {
		var RulesElems []BGPRoutingPolicyRulesModel
		diags := data.Rules.ElementsAs(ctx, &RulesElems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(RulesElems) > 0 {
			var RulesList []map[string]interface{}
			for _, RulesItem := range RulesElems {
				RulesItemMap := make(map[string]interface{})
				if RulesItem.Action != nil {
					RulesActionMap := make(map[string]interface{})
					if RulesItem.Action.Allow != nil {
						RulesActionMap["allow"] = map[string]interface{}{}
					}
					if !RulesItem.Action.AsPath.IsNull() && !RulesItem.Action.AsPath.IsUnknown() {
						RulesActionMap["as_path"] = RulesItem.Action.AsPath.ValueString()
					}
					if RulesItem.Action.Community != nil {
						RulesActionCommunityMap := make(map[string]interface{})
						if !RulesItem.Action.Community.Community.IsNull() && !RulesItem.Action.Community.Community.IsUnknown() {
							var CommunityItems []string
							diags := RulesItem.Action.Community.Community.ElementsAs(ctx, &CommunityItems, false)
							resp.Diagnostics.Append(diags...)
							if !diags.HasError() {
								RulesActionCommunityMap["community"] = CommunityItems
							}
						}
						RulesActionMap["community"] = RulesActionCommunityMap
					}
					if RulesItem.Action.Deny != nil {
						RulesActionMap["deny"] = map[string]interface{}{}
					}
					if !RulesItem.Action.LocalPreference.IsNull() && !RulesItem.Action.LocalPreference.IsUnknown() {
						RulesActionMap["local_preference"] = RulesItem.Action.LocalPreference.ValueInt64()
					}
					if !RulesItem.Action.Metric.IsNull() && !RulesItem.Action.Metric.IsUnknown() {
						RulesActionMap["metric"] = RulesItem.Action.Metric.ValueInt64()
					}
					RulesItemMap["action"] = RulesActionMap
				}
				if RulesItem.Match != nil {
					RulesMatchMap := make(map[string]interface{})
					if !RulesItem.Match.AsPath.IsNull() && !RulesItem.Match.AsPath.IsUnknown() {
						RulesMatchMap["as_path"] = RulesItem.Match.AsPath.ValueString()
					}
					if RulesItem.Match.Community != nil {
						RulesMatchCommunityMap := make(map[string]interface{})
						if !RulesItem.Match.Community.Community.IsNull() && !RulesItem.Match.Community.Community.IsUnknown() {
							var CommunityItems []string
							diags := RulesItem.Match.Community.Community.ElementsAs(ctx, &CommunityItems, false)
							resp.Diagnostics.Append(diags...)
							if !diags.HasError() {
								RulesMatchCommunityMap["community"] = CommunityItems
							}
						}
						RulesMatchMap["community"] = RulesMatchCommunityMap
					}
					if RulesItem.Match.IPPrefixes != nil {
						RulesMatchIPPrefixesMap := make(map[string]interface{})
						if !RulesItem.Match.IPPrefixes.Prefixes.IsNull() && !RulesItem.Match.IPPrefixes.Prefixes.IsUnknown() {
							var PrefixesElems []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
							diags := RulesItem.Match.IPPrefixes.Prefixes.ElementsAs(ctx, &PrefixesElems, false)
							resp.Diagnostics.Append(diags...)
							if !resp.Diagnostics.HasError() && len(PrefixesElems) > 0 {
								var PrefixesList []map[string]interface{}
								for _, PrefixesItem := range PrefixesElems {
									PrefixesItemMap := make(map[string]interface{})
									if PrefixesItem.EqualOrLongerThan != nil {
										PrefixesItemMap["equal_or_longer_than"] = map[string]interface{}{}
									}
									if PrefixesItem.ExactMatch != nil {
										PrefixesItemMap["exact_match"] = map[string]interface{}{}
									}
									if !PrefixesItem.IPPrefixes.IsNull() && !PrefixesItem.IPPrefixes.IsUnknown() {
										PrefixesItemMap["ip_prefixes"] = PrefixesItem.IPPrefixes.ValueString()
									}
									if PrefixesItem.LongerThan != nil {
										PrefixesItemMap["longer_than"] = map[string]interface{}{}
									}
									PrefixesList = append(PrefixesList, PrefixesItemMap)
								}
								RulesMatchIPPrefixesMap["prefixes"] = PrefixesList
							}
						}
						RulesMatchMap["ip_prefixes"] = RulesMatchIPPrefixesMap
					}
					RulesItemMap["match"] = RulesMatchMap
				}
				RulesList = append(RulesList, RulesItemMap)
			}
			apiResource.Spec["rules"] = RulesList
		}
	}

	_, err := r.client.UpdateBGPRoutingPolicy(ctx, apiResource)
	if err != nil {
		var apiErr *xcsherrors.XCSHError
		if errors.As(err, &apiErr) && apiErr.Code == xcsherrors.ErrCodeConflict {
			resp.Diagnostics.AddError(
				"Stale Configuration",
				fmt.Sprintf("F5 XC rejected the update of bgp_routing_policy %q in namespace %q because the object changed after Terraform last refreshed it. The provider sent one replace request using the exact token stored with the reviewed state and did not retry or change private state. Refresh, review the remote changes, and apply again.", data.Name.ValueString(), data.Namespace.ValueString()),
			)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update BGPRoutingPolicy: %s", err))
		return
	}

	// Only now that the write has landed. terraform-plugin-framework persists private
	// state even when the method returns an error (it copies updateResp.Private into the
	// response before checking diagnostics), so recording ownership earlier would be
	// worse than not recording it: dropping a ves.io/ label from the configuration and
	// then failing the update would leave private state claiming the key is unowned while
	// the server still holds it, and Read would filter it out of sight for good.
	//
	// This is not airtight, and cannot be: Client.Put returns json.Unmarshal's error
	// after a 2xx, so an error does not strictly prove the write was rejected. What it
	// does guarantee is the direction of the residual. If the write landed and we return
	// early, ownership stays as it was — an added label keeps being planned, which is
	// visible and self-corrects on the next successful apply. The opposite ordering loses
	// a label silently and permanently. Fail loud rather than fail quiet.

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetBGPRoutingPolicy(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read BGPRoutingPolicy after update: %s", fetchErr))
		return
	}

	// Commit both private-state updates only after PUT and readback succeeded. A 409
	// or failed readback therefore leaves the prior token and label ownership intact.
	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(fetched.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Record Updated Concurrency Token", tokenErr.Error())
		return
	}
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, ownedLabelKeysPrivateKey, ownedLabelKeys)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set computed fields from API response

	// Unmarshal fields from the complete GET response into Terraform state.
	apiResource = fetched
	isImport := false // Update is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if !isImport && (data.Rules.IsNull() || len(data.Rules.Elements()) == 0) {
		data.Rules = types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes})
	} else if listData, ok := apiResource.Spec["rules"].([]interface{}); ok && len(listData) > 0 {
		var RulesList []BGPRoutingPolicyRulesModel
		var existingRulesItems []BGPRoutingPolicyRulesModel
		if !data.Rules.IsNull() && !data.Rules.IsUnknown() {
			data.Rules.ElementsAs(ctx, &existingRulesItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				RulesList = append(RulesList, BGPRoutingPolicyRulesModel{
					Action: func() *BGPRoutingPolicyRulesActionModel {
						if ActionData, ok := itemMap["action"].(map[string]interface{}); ok {
							return &BGPRoutingPolicyRulesActionModel{
								Allow: func() *BGPRoutingPolicyEmptyModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil {
										return existingRulesItems[listIdx].Action.Allow
									}
									if _, ok := ActionData["allow"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyEmptyModel{}
									}
									return nil
								}(),
								AsPath: func() types.String {
									if v, ok := ActionData["as_path"].(string); ok && v != "" {
										return types.StringValue(v)
									}
									return types.StringNull()
								}(),
								Community: func() *BGPRoutingPolicyRulesActionCommunityModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && existingRulesItems[listIdx].Action.Community != nil {
										return existingRulesItems[listIdx].Action.Community
									}
									if CommunityData, ok := ActionData["community"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesActionCommunityModel{
											Community: func() types.List {
												if v, ok := CommunityData["community"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, diags := types.ListValueFrom(ctx, types.StringType, items)
													resp.Diagnostics.Append(diags...)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								Deny: func() *BGPRoutingPolicyEmptyModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil {
										return existingRulesItems[listIdx].Action.Deny
									}
									if _, ok := ActionData["deny"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyEmptyModel{}
									}
									return nil
								}(),
								LocalPreference: func() types.Int64 {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && !existingRulesItems[listIdx].Action.LocalPreference.IsUnknown() {
										return existingRulesItems[listIdx].Action.LocalPreference
									}
									if v, ok := ActionData["local_preference"].(float64); ok && v != 0 {
										return types.Int64Value(int64(v))
									}
									return types.Int64Null()
								}(),
								Metric: func() types.Int64 {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Action != nil && !existingRulesItems[listIdx].Action.Metric.IsUnknown() {
										return existingRulesItems[listIdx].Action.Metric
									}
									if v, ok := ActionData["metric"].(float64); ok && v != 0 {
										return types.Int64Value(int64(v))
									}
									return types.Int64Null()
								}(),
							}
						}
						return nil
					}(),
					Match: func() *BGPRoutingPolicyRulesMatchModel {
						if MatchData, ok := itemMap["match"].(map[string]interface{}); ok {
							return &BGPRoutingPolicyRulesMatchModel{
								AsPath: func() types.String {
									if v, ok := MatchData["as_path"].(string); ok && v != "" {
										return types.StringValue(v)
									}
									return types.StringNull()
								}(),
								Community: func() *BGPRoutingPolicyRulesMatchCommunityModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.Community != nil {
										return existingRulesItems[listIdx].Match.Community
									}
									if CommunityData, ok := MatchData["community"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesMatchCommunityModel{
											Community: func() types.List {
												if v, ok := CommunityData["community"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, diags := types.ListValueFrom(ctx, types.StringType, items)
													resp.Diagnostics.Append(diags...)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								IPPrefixes: func() *BGPRoutingPolicyRulesMatchIPPrefixesModel {
									if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil {
										return existingRulesItems[listIdx].Match.IPPrefixes
									}
									if IPPrefixesData, ok := MatchData["ip_prefixes"].(map[string]interface{}); ok {
										return &BGPRoutingPolicyRulesMatchIPPrefixesModel{
											Prefixes: func() types.List {
												if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil && (existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsNull() || len(existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.Elements()) == 0) {
													return types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes})
												}
												var PrefixesExisting []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
												if !isImport && len(existingRulesItems) > listIdx && existingRulesItems[listIdx].Match != nil && existingRulesItems[listIdx].Match.IPPrefixes != nil && !existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsNull() && !existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.IsUnknown() {
													existingRulesItems[listIdx].Match.IPPrefixes.Prefixes.ElementsAs(ctx, &PrefixesExisting, false)
												}
												if rawList, ok := IPPrefixesData["prefixes"].([]interface{}); ok && len(rawList) > 0 {
													var PrefixesResult []BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel
													for PrefixesIdx, PrefixesItem := range rawList {
														_ = PrefixesIdx
														if PrefixesItemMap, ok := PrefixesItem.(map[string]interface{}); ok {
															PrefixesResult = append(PrefixesResult, BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModel{
																EqualOrLongerThan: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].EqualOrLongerThan
																	}
																	if _, ok := PrefixesItemMap["equal_or_longer_than"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
																ExactMatch: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].ExactMatch
																	}
																	if _, ok := PrefixesItemMap["exact_match"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
																IPPrefixes: func() types.String {
																	if v, ok := PrefixesItemMap["ip_prefixes"].(string); ok && v != "" {
																		return types.StringValue(v)
																	}
																	return types.StringNull()
																}(),
																LongerThan: func() *BGPRoutingPolicyEmptyModel {
																	if !isImport && len(PrefixesExisting) > PrefixesIdx {
																		return PrefixesExisting[PrefixesIdx].LongerThan
																	}
																	if _, ok := PrefixesItemMap["longer_than"].(map[string]interface{}); ok {
																		return &BGPRoutingPolicyEmptyModel{}
																	}
																	return nil
																}(),
															})
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes}, PrefixesResult)
													return listVal
												}
												return types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesMatchIPPrefixesPrefixesModelAttrTypes})
											}(),
										}
									}
									return nil
								}(),
							}
						}
						return nil
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes}, RulesList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Rules = listVal
		}
	} else {
		data.Rules = types.ListNull(types.ObjectType{AttrTypes: BGPRoutingPolicyRulesModelAttrTypes})
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *BGPRoutingPolicyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data BGPRoutingPolicyResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

	// Delete with bounded retry on transient referential BAD_REQUEST: during teardown a
	// resource can briefly still be referenced by another object (a healthcheck by an origin
	// pool, an origin pool by a load balancer, etc.), which the API rejects with 400 until
	// the referrer is gone. NOT_FOUND/404 (already deleted) and 501 (delete unsupported) are
	// terminal and handled after the loop.
	var err error
	for attempt := 0; ; attempt++ {
		err = r.client.DeleteBGPRoutingPolicy(ctx, data.Namespace.ValueString(), data.Name.ValueString())
		if err == nil {
			break
		}
		msg := err.Error()
		transient := (strings.Contains(msg, "400") || strings.Contains(msg, "BAD_REQUEST")) &&
			!strings.Contains(msg, "NOT_FOUND") && !strings.Contains(msg, "404") && !strings.Contains(msg, "501")
		if !transient || attempt >= 5 {
			break
		}
		tflog.Warn(ctx, "BGPRoutingPolicy delete hit transient BAD_REQUEST (likely still referenced); retrying", map[string]interface{}{
			"name":      data.Name.ValueString(),
			"namespace": data.Namespace.ValueString(),
			"attempt":   attempt + 1,
		})
		select {
		case <-ctx.Done():
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Timed out retrying delete of BGPRoutingPolicy (still referenced): %s", err))
			return
		case <-time.After(5 * time.Second):
		}
	}
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "BGPRoutingPolicy already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "BGPRoutingPolicy delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete BGPRoutingPolicy: %s", err))
		return
	}
}

func (r *BGPRoutingPolicyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
