// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC enriched API response-operation contract

package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
)

var _ datasource.DataSource = &BotPeerStatusDataSource{}
var _ datasource.DataSourceWithConfigure = &BotPeerStatusDataSource{}

func NewBotPeerStatusDataSource() datasource.DataSource { return &BotPeerStatusDataSource{} }

type BotPeerStatusDataSource struct{ client *client.Client }
type BotPeerStatusDataSourceModel struct {
	Namespace types.String `tfsdk:"namespace"`
	HasPeers  types.Bool   `tfsdk:"has_peers"`
}

func (d *BotPeerStatusDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_bot_peer_status"
}
func (d *BotPeerStatusDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{MarkdownDescription: "Resource creation operation.",
		Attributes: map[string]schema.Attribute{
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace. namespace is used to scope the query. Only virtual_host in given namespace will be considered.",
				Required:            true,
			},
			"has_peers": schema.BoolAttribute{
				MarkdownDescription: "Has peers status. The tenat has peers or not.",
				Computed:            true,
			},
		},
	}
}
func (d *BotPeerStatusDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	configured, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = configured
}
func (d *BotPeerStatusDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data BotPeerStatusDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiPath := "/api/shape/bot/namespaces/{namespace}/v2/reporting/peers/check"
	apiPath = strings.ReplaceAll(apiPath, "{namespace}", url.PathEscape(data.Namespace.ValueString()))
	queryValues := url.Values{}
	if encoded := queryValues.Encode(); encoded != "" {
		apiPath += "?" + encoded
	}
	body := map[string]interface{}{}
	if !data.Namespace.IsNull() && !data.Namespace.IsUnknown() {
		body["namespace"] = data.Namespace.ValueString()
	}
	apiResult := map[string]interface{}{}
	if err := d.client.Post(ctx, apiPath, body, &apiResult); err != nil {
		resp.Diagnostics.AddError("Client Error", "Unable to invoke response operation. Raw API diagnostics are suppressed.")
		return
	}
	apiResource := struct{ Spec map[string]interface{} }{Spec: apiResult}
	isImport := true
	_ = isImport
	if err := client.ValidateResponseFields(apiResult, []client.ResponseField{
		{Name: "has_peers", Type: "boolean", Required: false, MinLength: 0, Format: "", Pattern: ""},
	}); err != nil {
		resp.Diagnostics.AddError("Incomplete API Response", err.Error())
		return
	}
	if v, ok := apiResource.Spec["has_peers"].(bool); ok {
		data.HasPeers = types.BoolValue(v)
	} else {
		data.HasPeers = types.BoolNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
