// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
	xcsherrors "github.com/f5-sales-demo/terraform-provider-xcsh/internal/errors"
	inttimeouts "github.com/f5-sales-demo/terraform-provider-xcsh/internal/timeouts"
	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &CminstanceResource{}
	_ resource.ResourceWithConfigure      = &CminstanceResource{}
	_ resource.ResourceWithImportState    = &CminstanceResource{}
	_ resource.ResourceWithModifyPlan     = &CminstanceResource{}
	_ resource.ResourceWithValidateConfig = &CminstanceResource{}
)

func NewCminstanceResource() resource.Resource {
	return &CminstanceResource{}
}

type CminstanceResource struct {
	client *client.Client
}

// CminstanceEmptyModel represents empty nested blocks
type CminstanceEmptyModel struct {
}

// CminstanceAPITokenModel represents api_token block
type CminstanceAPITokenModel struct {
	BlindfoldSecretInfo *CminstanceAPITokenBlindfoldSecretInfoModel `tfsdk:"blindfold_secret_info"`
	ClearSecretInfo     *CminstanceAPITokenClearSecretInfoModel     `tfsdk:"clear_secret_info"`
}

// CminstanceAPITokenModelAttrTypes defines the attribute types for CminstanceAPITokenModel
var CminstanceAPITokenModelAttrTypes = map[string]attr.Type{
	"blindfold_secret_info": types.ObjectType{AttrTypes: CminstanceAPITokenBlindfoldSecretInfoModelAttrTypes},
	"clear_secret_info":     types.ObjectType{AttrTypes: CminstanceAPITokenClearSecretInfoModelAttrTypes},
}

// CminstanceAPITokenBlindfoldSecretInfoModel represents blindfold_secret_info block
type CminstanceAPITokenBlindfoldSecretInfoModel struct {
	DecryptionProvider types.String `tfsdk:"decryption_provider"`
	Location           types.String `tfsdk:"location"`
	StoreProvider      types.String `tfsdk:"store_provider"`
}

// CminstanceAPITokenBlindfoldSecretInfoModelAttrTypes defines the attribute types for CminstanceAPITokenBlindfoldSecretInfoModel
var CminstanceAPITokenBlindfoldSecretInfoModelAttrTypes = map[string]attr.Type{
	"decryption_provider": types.StringType,
	"location":            types.StringType,
	"store_provider":      types.StringType,
}

// CminstanceAPITokenClearSecretInfoModel represents clear_secret_info block
type CminstanceAPITokenClearSecretInfoModel struct {
	Provider types.String `tfsdk:"provider_ref"`
	URL      types.String `tfsdk:"url"`
}

// CminstanceAPITokenClearSecretInfoModelAttrTypes defines the attribute types for CminstanceAPITokenClearSecretInfoModel
var CminstanceAPITokenClearSecretInfoModelAttrTypes = map[string]attr.Type{
	"provider_ref": types.StringType,
	"url":          types.StringType,
}

// CminstanceIPModel represents ip block
type CminstanceIPModel struct {
	Addr types.String `tfsdk:"addr"`
}

// CminstanceIPModelAttrTypes defines the attribute types for CminstanceIPModel
var CminstanceIPModelAttrTypes = map[string]attr.Type{
	"addr": types.StringType,
}

// CminstancePasswordModel represents password block
type CminstancePasswordModel struct {
	BlindfoldSecretInfo *CminstancePasswordBlindfoldSecretInfoModel `tfsdk:"blindfold_secret_info"`
	ClearSecretInfo     *CminstancePasswordClearSecretInfoModel     `tfsdk:"clear_secret_info"`
}

// CminstancePasswordModelAttrTypes defines the attribute types for CminstancePasswordModel
var CminstancePasswordModelAttrTypes = map[string]attr.Type{
	"blindfold_secret_info": types.ObjectType{AttrTypes: CminstancePasswordBlindfoldSecretInfoModelAttrTypes},
	"clear_secret_info":     types.ObjectType{AttrTypes: CminstancePasswordClearSecretInfoModelAttrTypes},
}

// CminstancePasswordBlindfoldSecretInfoModel represents blindfold_secret_info block
type CminstancePasswordBlindfoldSecretInfoModel struct {
	DecryptionProvider types.String `tfsdk:"decryption_provider"`
	Location           types.String `tfsdk:"location"`
	StoreProvider      types.String `tfsdk:"store_provider"`
}

// CminstancePasswordBlindfoldSecretInfoModelAttrTypes defines the attribute types for CminstancePasswordBlindfoldSecretInfoModel
var CminstancePasswordBlindfoldSecretInfoModelAttrTypes = map[string]attr.Type{
	"decryption_provider": types.StringType,
	"location":            types.StringType,
	"store_provider":      types.StringType,
}

// CminstancePasswordClearSecretInfoModel represents clear_secret_info block
type CminstancePasswordClearSecretInfoModel struct {
	Provider types.String `tfsdk:"provider_ref"`
	URL      types.String `tfsdk:"url"`
}

// CminstancePasswordClearSecretInfoModelAttrTypes defines the attribute types for CminstancePasswordClearSecretInfoModel
var CminstancePasswordClearSecretInfoModelAttrTypes = map[string]attr.Type{
	"provider_ref": types.StringType,
	"url":          types.StringType,
}

type CminstanceResourceModel struct {
	Name        types.String             `tfsdk:"name"`
	Namespace   types.String             `tfsdk:"namespace"`
	Port        types.Int64              `tfsdk:"port"`
	Username    types.String             `tfsdk:"username"`
	Annotations types.Map                `tfsdk:"annotations"`
	Description types.String             `tfsdk:"description"`
	Disable     types.Bool               `tfsdk:"disable"`
	Labels      types.Map                `tfsdk:"labels"`
	ID          types.String             `tfsdk:"id"`
	Timeouts    timeouts.Value           `tfsdk:"timeouts"`
	APIToken    *CminstanceAPITokenModel `tfsdk:"api_token"`
	IP          *CminstanceIPModel       `tfsdk:"ip"`
	Password    *CminstancePasswordModel `tfsdk:"password"`
}

func (r *CminstanceResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cminstance"
}

func (r *CminstanceResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages App type will create the configuration in namespace metadata.namespace in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the Cminstance. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the Cminstance is created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"port": schema.Int64Attribute{
				MarkdownDescription: "Port of the Central Manager instance to connect to.",
				Required:            true,
				Validators: []validator.Int64{
					int64validator.Between(1, 65535),
				},
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Username for the Central Manager instance.",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(4, 128),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true administratively disables the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"api_token": schema.SingleNestedBlock{
				MarkdownDescription: "SecretType is used in an object to indicate a sensitive/confidential field.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"blindfold_secret_info": schema.SingleNestedBlock{
						MarkdownDescription: "BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management.",
						Attributes: map[string]schema.Attribute{
							"decryption_provider": schema.StringAttribute{
								MarkdownDescription: "Name of the Secret Management Access object that contains information about the backend Secret Management service.",
								Optional:            true,
							},
							"location": schema.StringAttribute{
								MarkdownDescription: "Location is the uri_ref. It could be in URL format for string:/// Or it could be a path if the store provider is an HTTP/HTTPS location.",
								Optional:            true,
								Validators: []validator.String{
									stringvalidator.LengthBetween(4, 131072),
								},
							},
							"store_provider": schema.StringAttribute{
								MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
								Optional:            true,
							},
						},
					},
					"clear_secret_info": schema.SingleNestedBlock{
						MarkdownDescription: "ClearSecretInfoType specifies information about the Secret that is not encrypted.",
						Attributes: map[string]schema.Attribute{
							"provider_ref": schema.StringAttribute{
								MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
								Optional:            true,
							},
							"url": schema.StringAttribute{
								MarkdownDescription: "URL of the secret. Currently supported URL schemes is string:///. For string:/// scheme, Secret needs to be encoded Base64 format. When asked for this secret, caller will GET Secret bytes after Base64 decoding.",
								Optional:            true,
								Validators: []validator.String{
									stringvalidator.LengthBetween(1, 131072),
								},
							},
						},
					},
				},
			},
			"ip": schema.SingleNestedBlock{
				MarkdownDescription: "IPv4 address in dotted decimal notation (e.g., 192.0.2.1).",
				Attributes: map[string]schema.Attribute{
					"addr": schema.StringAttribute{
						MarkdownDescription: "IPv4 Address in string form with dot-decimal notation.",
						Optional:            true,
						Validators: []validator.String{
							stringvalidator.LengthAtMost(1024),
							validators.IPv4Validator(),
						},
					},
				},
			},
			"password": schema.SingleNestedBlock{
				MarkdownDescription: "SecretType is used in an object to indicate a sensitive/confidential field.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"blindfold_secret_info": schema.SingleNestedBlock{
						MarkdownDescription: "BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management.",
						Attributes: map[string]schema.Attribute{
							"decryption_provider": schema.StringAttribute{
								MarkdownDescription: "Name of the Secret Management Access object that contains information about the backend Secret Management service.",
								Optional:            true,
							},
							"location": schema.StringAttribute{
								MarkdownDescription: "Location is the uri_ref. It could be in URL format for string:/// Or it could be a path if the store provider is an HTTP/HTTPS location.",
								Optional:            true,
								Validators: []validator.String{
									stringvalidator.LengthBetween(4, 131072),
								},
							},
							"store_provider": schema.StringAttribute{
								MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
								Optional:            true,
							},
						},
					},
					"clear_secret_info": schema.SingleNestedBlock{
						MarkdownDescription: "ClearSecretInfoType specifies information about the Secret that is not encrypted.",
						Attributes: map[string]schema.Attribute{
							"provider_ref": schema.StringAttribute{
								MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
								Optional:            true,
							},
							"url": schema.StringAttribute{
								MarkdownDescription: "URL of the secret. Currently supported URL schemes is string:///. For string:/// scheme, Secret needs to be encoded Base64 format. When asked for this secret, caller will GET Secret bytes after Base64 decoding.",
								Optional:            true,
								Validators: []validator.String{
									stringvalidator.LengthBetween(1, 131072),
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *CminstanceResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *CminstanceResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data CminstanceResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *CminstanceResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This permanently deletes the cminstance from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan CminstanceResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *CminstanceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CminstanceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating cminstance", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.Cminstance{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	// Capture which label keys the configuration declared, so Read can tell a label this
	// configuration owns from one the platform added (#1398). Create and Update are the
	// only places the configuration is visible; Read sees prior state, and prior state is
	// not evidence of ownership because providers up to 3.81.1 wrote the platform's own
	// labels into it.
	//
	// Captured here, written to private state only after the API call succeeds — see the
	// note at the write site.
	ownedLabelKeys, ownedLabelErr := encodeOwnedLabelKeys(configLabelKeys(createReq.Metadata.Labels))
	if ownedLabelErr != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Owned Label Keys",
			"Could not encode the configuration's label keys for private state: "+ownedLabelErr.Error()+
				"\n\nWithout this record the read-back cannot distinguish a label this "+
				"configuration owns from one the platform authored, and a label in the "+
				"ves.io/ namespace would never converge.",
		)
		return
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.Port.IsNull() && !data.Port.IsUnknown() {
		createReq.Spec["port"] = data.Port.ValueInt64()
	}
	if !data.Username.IsNull() && !data.Username.IsUnknown() {
		createReq.Spec["username"] = data.Username.ValueString()
	}
	if data.APIToken != nil {
		APITokenMap := make(map[string]interface{})
		if data.APIToken.BlindfoldSecretInfo != nil {
			APITokenBlindfoldSecretInfoMap := make(map[string]interface{})
			if !data.APIToken.BlindfoldSecretInfo.DecryptionProvider.IsNull() && !data.APIToken.BlindfoldSecretInfo.DecryptionProvider.IsUnknown() {
				APITokenBlindfoldSecretInfoMap["decryption_provider"] = data.APIToken.BlindfoldSecretInfo.DecryptionProvider.ValueString()
			}
			if !data.APIToken.BlindfoldSecretInfo.Location.IsNull() && !data.APIToken.BlindfoldSecretInfo.Location.IsUnknown() {
				APITokenBlindfoldSecretInfoMap["location"] = data.APIToken.BlindfoldSecretInfo.Location.ValueString()
			}
			if !data.APIToken.BlindfoldSecretInfo.StoreProvider.IsNull() && !data.APIToken.BlindfoldSecretInfo.StoreProvider.IsUnknown() {
				APITokenBlindfoldSecretInfoMap["store_provider"] = data.APIToken.BlindfoldSecretInfo.StoreProvider.ValueString()
			}
			APITokenMap["blindfold_secret_info"] = APITokenBlindfoldSecretInfoMap
		}
		if data.APIToken.ClearSecretInfo != nil {
			APITokenClearSecretInfoMap := make(map[string]interface{})
			if !data.APIToken.ClearSecretInfo.Provider.IsNull() && !data.APIToken.ClearSecretInfo.Provider.IsUnknown() {
				APITokenClearSecretInfoMap["provider"] = data.APIToken.ClearSecretInfo.Provider.ValueString()
			}
			if !data.APIToken.ClearSecretInfo.URL.IsNull() && !data.APIToken.ClearSecretInfo.URL.IsUnknown() {
				APITokenClearSecretInfoMap["url"] = data.APIToken.ClearSecretInfo.URL.ValueString()
			}
			APITokenMap["clear_secret_info"] = APITokenClearSecretInfoMap
		}
		createReq.Spec["api_token"] = APITokenMap
	}
	if data.IP != nil {
		IPMap := make(map[string]interface{})
		if !data.IP.Addr.IsNull() && !data.IP.Addr.IsUnknown() {
			IPMap["addr"] = data.IP.Addr.ValueString()
		}
		createReq.Spec["ip"] = IPMap
	}
	if data.Password != nil {
		PasswordMap := make(map[string]interface{})
		if data.Password.BlindfoldSecretInfo != nil {
			PasswordBlindfoldSecretInfoMap := make(map[string]interface{})
			if !data.Password.BlindfoldSecretInfo.DecryptionProvider.IsNull() && !data.Password.BlindfoldSecretInfo.DecryptionProvider.IsUnknown() {
				PasswordBlindfoldSecretInfoMap["decryption_provider"] = data.Password.BlindfoldSecretInfo.DecryptionProvider.ValueString()
			}
			if !data.Password.BlindfoldSecretInfo.Location.IsNull() && !data.Password.BlindfoldSecretInfo.Location.IsUnknown() {
				PasswordBlindfoldSecretInfoMap["location"] = data.Password.BlindfoldSecretInfo.Location.ValueString()
			}
			if !data.Password.BlindfoldSecretInfo.StoreProvider.IsNull() && !data.Password.BlindfoldSecretInfo.StoreProvider.IsUnknown() {
				PasswordBlindfoldSecretInfoMap["store_provider"] = data.Password.BlindfoldSecretInfo.StoreProvider.ValueString()
			}
			PasswordMap["blindfold_secret_info"] = PasswordBlindfoldSecretInfoMap
		}
		if data.Password.ClearSecretInfo != nil {
			PasswordClearSecretInfoMap := make(map[string]interface{})
			if !data.Password.ClearSecretInfo.Provider.IsNull() && !data.Password.ClearSecretInfo.Provider.IsUnknown() {
				PasswordClearSecretInfoMap["provider"] = data.Password.ClearSecretInfo.Provider.ValueString()
			}
			if !data.Password.ClearSecretInfo.URL.IsNull() && !data.Password.ClearSecretInfo.URL.IsUnknown() {
				PasswordClearSecretInfoMap["url"] = data.Password.ClearSecretInfo.URL.ValueString()
			}
			PasswordMap["clear_secret_info"] = PasswordClearSecretInfoMap
		}
		createReq.Spec["password"] = PasswordMap
	}

	apiResource, err := r.client.CreateCminstance(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create Cminstance: %s", err))
		return
	}

	// The concurrency token is declared only on GET responses. Read back the object
	// after creation and record that exact server-assigned value for the next replace.
	apiResource, err = r.client.GetCminstance(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Concurrency Token After Create",
			fmt.Sprintf("The object was created, but its server-assigned concurrency token could not be read. Refresh the resource before updating it: %s", err),
		)
		return
	}
	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(apiResource.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Record Concurrency Token After Create", tokenErr.Error())
		return
	}

	// Only now that the write has landed. terraform-plugin-framework persists private
	// state even when the method returns an error (it copies createResp.Private into the
	// response before checking diagnostics), so recording ownership earlier would claim
	// keys the server never received.
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, ownedLabelKeysPrivateKey, ownedLabelKeys)...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["port"].(float64); ok {
		data.Port = types.Int64Value(int64(v))
	} else {
		data.Port = types.Int64Null()
	}
	if v, ok := apiResource.Spec["username"].(string); ok && v != "" {
		data.Username = types.StringValue(v)
	} else {
		data.Username = types.StringNull()
	}
	if blockData, ok := apiResource.Spec["api_token"].(map[string]interface{}); ok && (isImport || data.APIToken != nil) {
		data.APIToken = &CminstanceAPITokenModel{
			BlindfoldSecretInfo: func() *CminstanceAPITokenBlindfoldSecretInfoModel {
				if !isImport && data.APIToken != nil && data.APIToken.BlindfoldSecretInfo != nil {
					return data.APIToken.BlindfoldSecretInfo
				}
				if BlindfoldSecretInfoData, ok := blockData["blindfold_secret_info"].(map[string]interface{}); ok {
					return &CminstanceAPITokenBlindfoldSecretInfoModel{
						DecryptionProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						Location: func() types.String {
							if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						StoreProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
			ClearSecretInfo: func() *CminstanceAPITokenClearSecretInfoModel {
				if !isImport && data.APIToken != nil && data.APIToken.ClearSecretInfo != nil {
					return data.APIToken.ClearSecretInfo
				}
				if ClearSecretInfoData, ok := blockData["clear_secret_info"].(map[string]interface{}); ok {
					return &CminstanceAPITokenClearSecretInfoModel{
						Provider: func() types.String {
							if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						URL: func() types.String {
							if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ip"].(map[string]interface{}); ok && (isImport || data.IP != nil) {
		data.IP = &CminstanceIPModel{
			Addr: func() types.String {
				if v, ok := blockData["addr"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["password"].(map[string]interface{}); ok && (isImport || data.Password != nil) {
		data.Password = &CminstancePasswordModel{
			BlindfoldSecretInfo: func() *CminstancePasswordBlindfoldSecretInfoModel {
				if !isImport && data.Password != nil && data.Password.BlindfoldSecretInfo != nil {
					return data.Password.BlindfoldSecretInfo
				}
				if BlindfoldSecretInfoData, ok := blockData["blindfold_secret_info"].(map[string]interface{}); ok {
					return &CminstancePasswordBlindfoldSecretInfoModel{
						DecryptionProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						Location: func() types.String {
							if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						StoreProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
			ClearSecretInfo: func() *CminstancePasswordClearSecretInfoModel {
				if !isImport && data.Password != nil && data.Password.ClearSecretInfo != nil {
					return data.Password.ClearSecretInfo
				}
				if ClearSecretInfoData, ok := blockData["clear_secret_info"].(map[string]interface{}); ok {
					return &CminstancePasswordClearSecretInfoModel{
						Provider: func() types.String {
							if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						URL: func() types.String {
							if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
		}
	}

	tflog.Trace(ctx, "created Cminstance resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CminstanceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CminstanceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetCminstance(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "Cminstance not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		// Some F5 XC APIs do not implement GET-by-name (read returns 501 Not
		// Implemented — e.g. the shape/csd domain objects, which support only
		// list/create/delete). Treat that as "cannot refresh" and preserve the
		// prior state rather than erroring, so the resource stays manageable and
		// idempotent (create/delete still work).
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "Cminstance read not implemented by API (501); keeping prior state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read Cminstance: %s", err))
		return
	}

	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(apiResource.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Refresh Concurrency Token", tokenErr.Error())
		return
	}
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// #1286: the API omits an empty metadata map entirely, so "no entries in the
	// response" is ambiguous — it means either "never declared" or "declared empty".
	// Nulling both makes a config that declares labels = {} drift (+ labels = {}) on
	// every plan after apply, with no import involved. Resolve it from the prior
	// value: a known-empty prior map stays an empty map, anything else (null = never
	// declared, or unknown) becomes null. A prior map WITH entries still nulls, so a
	// genuine out-of-band deletion is still reported as drift.
	// The MapValueMust below cannot panic: it panics only on diagnostics, and with nil
	// elements NewMapValue's sole error path (per-element type mismatch) is unreachable.
	priorLabelsEmpty := !data.Labels.IsNull() && !data.Labels.IsUnknown() && len(data.Labels.Elements()) == 0
	priorAnnotationsEmpty := !data.Annotations.IsNull() && !data.Annotations.IsUnknown() && len(data.Annotations.Elements()) == 0

	// Filter out the labels the platform authors itself, which Terraform must not
	// propose deleting just because the configuration does not mention them (#1391) —
	// except any key the configuration declared at the last Create or Update, recorded
	// in private state. Without that exemption a configuration cannot own a label in the
	// ves.io/ namespace at all: the write succeeds, the read-back strips it, and the next
	// plan proposes adding it again, forever (#1398). Prior state cannot serve as the
	// record, because providers up to 3.81.1 wrote the platform's own labels into it.
	ownedLabels := map[string]struct{}{}
	if rawOwned, ownedDiags := req.Private.GetKey(ctx, ownedLabelKeysPrivateKey); !ownedDiags.HasError() {
		ownedLabels = decodeOwnedLabelKeys(rawOwned)
	}
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabelsOwning(apiResource.Metadata.Labels, false, ownedLabels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else if priorLabelsEmpty {
			data.Labels = types.MapValueMust(types.StringType, nil)
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else if priorLabelsEmpty {
		data.Labels = types.MapValueMust(types.StringType, nil)
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else if priorAnnotationsEmpty {
		data.Annotations = types.MapValueMust(types.StringType, nil)
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["port"].(float64); ok {
		data.Port = types.Int64Value(int64(v))
	} else {
		data.Port = types.Int64Null()
	}
	if v, ok := apiResource.Spec["username"].(string); ok && v != "" {
		data.Username = types.StringValue(v)
	} else {
		data.Username = types.StringNull()
	}
	if blockData, ok := apiResource.Spec["api_token"].(map[string]interface{}); ok && (isImport || data.APIToken != nil) {
		data.APIToken = &CminstanceAPITokenModel{
			BlindfoldSecretInfo: func() *CminstanceAPITokenBlindfoldSecretInfoModel {
				if !isImport && data.APIToken != nil && data.APIToken.BlindfoldSecretInfo != nil {
					return data.APIToken.BlindfoldSecretInfo
				}
				if BlindfoldSecretInfoData, ok := blockData["blindfold_secret_info"].(map[string]interface{}); ok {
					return &CminstanceAPITokenBlindfoldSecretInfoModel{
						DecryptionProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						Location: func() types.String {
							if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						StoreProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
			ClearSecretInfo: func() *CminstanceAPITokenClearSecretInfoModel {
				if !isImport && data.APIToken != nil && data.APIToken.ClearSecretInfo != nil {
					return data.APIToken.ClearSecretInfo
				}
				if ClearSecretInfoData, ok := blockData["clear_secret_info"].(map[string]interface{}); ok {
					return &CminstanceAPITokenClearSecretInfoModel{
						Provider: func() types.String {
							if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						URL: func() types.String {
							if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ip"].(map[string]interface{}); ok && (isImport || data.IP != nil) {
		data.IP = &CminstanceIPModel{
			Addr: func() types.String {
				if v, ok := blockData["addr"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["password"].(map[string]interface{}); ok && (isImport || data.Password != nil) {
		data.Password = &CminstancePasswordModel{
			BlindfoldSecretInfo: func() *CminstancePasswordBlindfoldSecretInfoModel {
				if !isImport && data.Password != nil && data.Password.BlindfoldSecretInfo != nil {
					return data.Password.BlindfoldSecretInfo
				}
				if BlindfoldSecretInfoData, ok := blockData["blindfold_secret_info"].(map[string]interface{}); ok {
					return &CminstancePasswordBlindfoldSecretInfoModel{
						DecryptionProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						Location: func() types.String {
							if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						StoreProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
			ClearSecretInfo: func() *CminstancePasswordClearSecretInfoModel {
				if !isImport && data.Password != nil && data.Password.ClearSecretInfo != nil {
					return data.Password.ClearSecretInfo
				}
				if ClearSecretInfoData, ok := blockData["clear_secret_info"].(map[string]interface{}); ok {
					return &CminstancePasswordClearSecretInfoModel{
						Provider: func() types.String {
							if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						URL: func() types.String {
							if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
		}
	}

	// The import marker is a one-shot signal for the import Read only. Clear it so every
	// subsequent refresh runs as a normal Read with drift-preservation; otherwise the
	// resource stays in "import mode" forever and re-reads server-managed fields the user
	// never configured, producing perpetual plan drift.
	if isImport {
		resp.Diagnostics.Append(resp.Private.SetKey(ctx, "isImport", nil)...)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CminstanceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data CminstanceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	rawConcurrencyToken, tokenDiags := req.Private.GetKey(ctx, concurrencyTokenPrivateKey)
	resp.Diagnostics.Append(tokenDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	concurrencyToken, tokenErr := decodeConcurrencyToken(rawConcurrencyToken)
	if tokenErr != nil {
		resp.Diagnostics.AddError(
			"Refresh Required Before Update",
			"The update was not sent because this resource has no usable concurrency token from its last read. Run terraform refresh (or terraform plan with refresh enabled), review the refreshed configuration, and apply again. The provider will not fetch and silently adopt a newer token during a write. Details: "+tokenErr.Error(),
		)
		return
	}

	apiResource := &client.Cminstance{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}
	apiResource.ResourceVersion = concurrencyToken

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	// Re-capture ownership on every update, because the configuration's label set can
	// change: a key added here becomes owned, and a key removed stops being owned so the
	// next Read filters it again if it lives in a platform namespace (#1398).
	//
	// Captured HERE, before the platform's own discovery labels are merged in below —
	// merging first would record those as configuration-owned and reintroduce exactly the
	// #1391 bug this pairs with. Written to private state only after the API call
	// succeeds; see the note at the write site.
	ownedLabelKeys, ownedLabelErr := encodeOwnedLabelKeys(configLabelKeys(apiResource.Metadata.Labels))
	if ownedLabelErr != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Owned Label Keys",
			"Could not encode the configuration's label keys for private state: "+ownedLabelErr.Error()+
				"\n\nWithout this record the read-back cannot distinguish a label this "+
				"configuration owns from one the platform authored, and a label in the "+
				"ves.io/ namespace would never converge.",
		)
		return
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.Port.IsNull() && !data.Port.IsUnknown() {
		apiResource.Spec["port"] = data.Port.ValueInt64()
	}
	if !data.Username.IsNull() && !data.Username.IsUnknown() {
		apiResource.Spec["username"] = data.Username.ValueString()
	}
	if data.APIToken != nil {
		APITokenMap := make(map[string]interface{})
		if data.APIToken.BlindfoldSecretInfo != nil {
			APITokenBlindfoldSecretInfoMap := make(map[string]interface{})
			if !data.APIToken.BlindfoldSecretInfo.DecryptionProvider.IsNull() && !data.APIToken.BlindfoldSecretInfo.DecryptionProvider.IsUnknown() {
				APITokenBlindfoldSecretInfoMap["decryption_provider"] = data.APIToken.BlindfoldSecretInfo.DecryptionProvider.ValueString()
			}
			if !data.APIToken.BlindfoldSecretInfo.Location.IsNull() && !data.APIToken.BlindfoldSecretInfo.Location.IsUnknown() {
				APITokenBlindfoldSecretInfoMap["location"] = data.APIToken.BlindfoldSecretInfo.Location.ValueString()
			}
			if !data.APIToken.BlindfoldSecretInfo.StoreProvider.IsNull() && !data.APIToken.BlindfoldSecretInfo.StoreProvider.IsUnknown() {
				APITokenBlindfoldSecretInfoMap["store_provider"] = data.APIToken.BlindfoldSecretInfo.StoreProvider.ValueString()
			}
			APITokenMap["blindfold_secret_info"] = APITokenBlindfoldSecretInfoMap
		}
		if data.APIToken.ClearSecretInfo != nil {
			APITokenClearSecretInfoMap := make(map[string]interface{})
			if !data.APIToken.ClearSecretInfo.Provider.IsNull() && !data.APIToken.ClearSecretInfo.Provider.IsUnknown() {
				APITokenClearSecretInfoMap["provider"] = data.APIToken.ClearSecretInfo.Provider.ValueString()
			}
			if !data.APIToken.ClearSecretInfo.URL.IsNull() && !data.APIToken.ClearSecretInfo.URL.IsUnknown() {
				APITokenClearSecretInfoMap["url"] = data.APIToken.ClearSecretInfo.URL.ValueString()
			}
			APITokenMap["clear_secret_info"] = APITokenClearSecretInfoMap
		}
		apiResource.Spec["api_token"] = APITokenMap
	}
	if data.IP != nil {
		IPMap := make(map[string]interface{})
		if !data.IP.Addr.IsNull() && !data.IP.Addr.IsUnknown() {
			IPMap["addr"] = data.IP.Addr.ValueString()
		}
		apiResource.Spec["ip"] = IPMap
	}
	if data.Password != nil {
		PasswordMap := make(map[string]interface{})
		if data.Password.BlindfoldSecretInfo != nil {
			PasswordBlindfoldSecretInfoMap := make(map[string]interface{})
			if !data.Password.BlindfoldSecretInfo.DecryptionProvider.IsNull() && !data.Password.BlindfoldSecretInfo.DecryptionProvider.IsUnknown() {
				PasswordBlindfoldSecretInfoMap["decryption_provider"] = data.Password.BlindfoldSecretInfo.DecryptionProvider.ValueString()
			}
			if !data.Password.BlindfoldSecretInfo.Location.IsNull() && !data.Password.BlindfoldSecretInfo.Location.IsUnknown() {
				PasswordBlindfoldSecretInfoMap["location"] = data.Password.BlindfoldSecretInfo.Location.ValueString()
			}
			if !data.Password.BlindfoldSecretInfo.StoreProvider.IsNull() && !data.Password.BlindfoldSecretInfo.StoreProvider.IsUnknown() {
				PasswordBlindfoldSecretInfoMap["store_provider"] = data.Password.BlindfoldSecretInfo.StoreProvider.ValueString()
			}
			PasswordMap["blindfold_secret_info"] = PasswordBlindfoldSecretInfoMap
		}
		if data.Password.ClearSecretInfo != nil {
			PasswordClearSecretInfoMap := make(map[string]interface{})
			if !data.Password.ClearSecretInfo.Provider.IsNull() && !data.Password.ClearSecretInfo.Provider.IsUnknown() {
				PasswordClearSecretInfoMap["provider"] = data.Password.ClearSecretInfo.Provider.ValueString()
			}
			if !data.Password.ClearSecretInfo.URL.IsNull() && !data.Password.ClearSecretInfo.URL.IsUnknown() {
				PasswordClearSecretInfoMap["url"] = data.Password.ClearSecretInfo.URL.ValueString()
			}
			PasswordMap["clear_secret_info"] = PasswordClearSecretInfoMap
		}
		apiResource.Spec["password"] = PasswordMap
	}

	_, err := r.client.UpdateCminstance(ctx, apiResource)
	if err != nil {
		var apiErr *xcsherrors.XCSHError
		if errors.As(err, &apiErr) && apiErr.Code == xcsherrors.ErrCodeConflict {
			resp.Diagnostics.AddError(
				"Stale Configuration",
				fmt.Sprintf("F5 XC rejected the update of cminstance %q in namespace %q because the object changed after Terraform last refreshed it. The provider sent one replace request using the exact token stored with the reviewed state and did not retry or change private state. Refresh, review the remote changes, and apply again.", data.Name.ValueString(), data.Namespace.ValueString()),
			)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update Cminstance: %s", err))
		return
	}

	// Only now that the write has landed. terraform-plugin-framework persists private
	// state even when the method returns an error (it copies updateResp.Private into the
	// response before checking diagnostics), so recording ownership earlier would be
	// worse than not recording it: dropping a ves.io/ label from the configuration and
	// then failing the update would leave private state claiming the key is unowned while
	// the server still holds it, and Read would filter it out of sight for good.
	//
	// This is not airtight, and cannot be: Client.Put returns json.Unmarshal's error
	// after a 2xx, so an error does not strictly prove the write was rejected. What it
	// does guarantee is the direction of the residual. If the write landed and we return
	// early, ownership stays as it was — an added label keeps being planned, which is
	// visible and self-corrects on the next successful apply. The opposite ordering loses
	// a label silently and permanently. Fail loud rather than fail quiet.

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetCminstance(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read Cminstance after update: %s", fetchErr))
		return
	}

	// Commit both private-state updates only after PUT and readback succeeded. A 409
	// or failed readback therefore leaves the prior token and label ownership intact.
	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(fetched.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Record Updated Concurrency Token", tokenErr.Error())
		return
	}
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, ownedLabelKeysPrivateKey, ownedLabelKeys)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set computed fields from API response

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["port"].(float64); ok {
		data.Port = types.Int64Value(int64(v))
	} else {
		data.Port = types.Int64Null()
	}
	if v, ok := apiResource.Spec["username"].(string); ok && v != "" {
		data.Username = types.StringValue(v)
	} else {
		data.Username = types.StringNull()
	}
	if blockData, ok := apiResource.Spec["api_token"].(map[string]interface{}); ok && (isImport || data.APIToken != nil) {
		data.APIToken = &CminstanceAPITokenModel{
			BlindfoldSecretInfo: func() *CminstanceAPITokenBlindfoldSecretInfoModel {
				if !isImport && data.APIToken != nil && data.APIToken.BlindfoldSecretInfo != nil {
					return data.APIToken.BlindfoldSecretInfo
				}
				if BlindfoldSecretInfoData, ok := blockData["blindfold_secret_info"].(map[string]interface{}); ok {
					return &CminstanceAPITokenBlindfoldSecretInfoModel{
						DecryptionProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						Location: func() types.String {
							if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						StoreProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
			ClearSecretInfo: func() *CminstanceAPITokenClearSecretInfoModel {
				if !isImport && data.APIToken != nil && data.APIToken.ClearSecretInfo != nil {
					return data.APIToken.ClearSecretInfo
				}
				if ClearSecretInfoData, ok := blockData["clear_secret_info"].(map[string]interface{}); ok {
					return &CminstanceAPITokenClearSecretInfoModel{
						Provider: func() types.String {
							if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						URL: func() types.String {
							if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ip"].(map[string]interface{}); ok && (isImport || data.IP != nil) {
		data.IP = &CminstanceIPModel{
			Addr: func() types.String {
				if v, ok := blockData["addr"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["password"].(map[string]interface{}); ok && (isImport || data.Password != nil) {
		data.Password = &CminstancePasswordModel{
			BlindfoldSecretInfo: func() *CminstancePasswordBlindfoldSecretInfoModel {
				if !isImport && data.Password != nil && data.Password.BlindfoldSecretInfo != nil {
					return data.Password.BlindfoldSecretInfo
				}
				if BlindfoldSecretInfoData, ok := blockData["blindfold_secret_info"].(map[string]interface{}); ok {
					return &CminstancePasswordBlindfoldSecretInfoModel{
						DecryptionProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						Location: func() types.String {
							if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						StoreProvider: func() types.String {
							if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
			ClearSecretInfo: func() *CminstancePasswordClearSecretInfoModel {
				if !isImport && data.Password != nil && data.Password.ClearSecretInfo != nil {
					return data.Password.ClearSecretInfo
				}
				if ClearSecretInfoData, ok := blockData["clear_secret_info"].(map[string]interface{}); ok {
					return &CminstancePasswordClearSecretInfoModel{
						Provider: func() types.String {
							if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						URL: func() types.String {
							if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CminstanceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data CminstanceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

	// Delete with bounded retry on transient referential BAD_REQUEST: during teardown a
	// resource can briefly still be referenced by another object (a healthcheck by an origin
	// pool, an origin pool by a load balancer, etc.), which the API rejects with 400 until
	// the referrer is gone. NOT_FOUND/404 (already deleted) and 501 (delete unsupported) are
	// terminal and handled after the loop.
	var err error
	for attempt := 0; ; attempt++ {
		err = r.client.DeleteCminstance(ctx, data.Namespace.ValueString(), data.Name.ValueString())
		if err == nil {
			break
		}
		msg := err.Error()
		transient := (strings.Contains(msg, "400") || strings.Contains(msg, "BAD_REQUEST")) &&
			!strings.Contains(msg, "NOT_FOUND") && !strings.Contains(msg, "404") && !strings.Contains(msg, "501")
		if !transient || attempt >= 5 {
			break
		}
		tflog.Warn(ctx, "Cminstance delete hit transient BAD_REQUEST (likely still referenced); retrying", map[string]interface{}{
			"name":      data.Name.ValueString(),
			"namespace": data.Namespace.ValueString(),
			"attempt":   attempt + 1,
		})
		select {
		case <-ctx.Done():
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Timed out retrying delete of Cminstance (still referenced): %s", err))
			return
		case <-time.After(5 * time.Second):
		}
	}
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "Cminstance already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "Cminstance delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete Cminstance: %s", err))
		return
	}
}

func (r *CminstanceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
