// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
	inttimeouts "github.com/f5-sales-demo/terraform-provider-xcsh/internal/timeouts"
	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &K8SClusterRoleResource{}
	_ resource.ResourceWithConfigure      = &K8SClusterRoleResource{}
	_ resource.ResourceWithImportState    = &K8SClusterRoleResource{}
	_ resource.ResourceWithModifyPlan     = &K8SClusterRoleResource{}
	_ resource.ResourceWithValidateConfig = &K8SClusterRoleResource{}
)

func NewK8SClusterRoleResource() resource.Resource {
	return &K8SClusterRoleResource{}
}

type K8SClusterRoleResource struct {
	client *client.Client
}

// K8SClusterRoleEmptyModel represents empty nested blocks
type K8SClusterRoleEmptyModel struct {
}

// K8SClusterRoleK8SClusterRoleSelectorModel represents k8s_cluster_role_selector block
type K8SClusterRoleK8SClusterRoleSelectorModel struct {
	Expressions types.List `tfsdk:"expressions"`
}

// K8SClusterRoleK8SClusterRoleSelectorModelAttrTypes defines the attribute types for K8SClusterRoleK8SClusterRoleSelectorModel
var K8SClusterRoleK8SClusterRoleSelectorModelAttrTypes = map[string]attr.Type{
	"expressions": types.ListType{ElemType: types.StringType},
}

// K8SClusterRolePolicyRuleListModel represents policy_rule_list block
type K8SClusterRolePolicyRuleListModel struct {
	PolicyRule []K8SClusterRolePolicyRuleListPolicyRuleModel `tfsdk:"policy_rule"`
}

// K8SClusterRolePolicyRuleListModelAttrTypes defines the attribute types for K8SClusterRolePolicyRuleListModel
var K8SClusterRolePolicyRuleListModelAttrTypes = map[string]attr.Type{
	"policy_rule": types.ListType{ElemType: types.ObjectType{AttrTypes: K8SClusterRolePolicyRuleListPolicyRuleModelAttrTypes}},
}

// K8SClusterRolePolicyRuleListPolicyRuleModel represents policy_rule block
type K8SClusterRolePolicyRuleListPolicyRuleModel struct {
	NonResourceURLList *K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel `tfsdk:"non_resource_url_list"`
	ResourceList       *K8SClusterRolePolicyRuleListPolicyRuleResourceListModel       `tfsdk:"resource_list"`
}

// K8SClusterRolePolicyRuleListPolicyRuleModelAttrTypes defines the attribute types for K8SClusterRolePolicyRuleListPolicyRuleModel
var K8SClusterRolePolicyRuleListPolicyRuleModelAttrTypes = map[string]attr.Type{
	"non_resource_url_list": types.ObjectType{AttrTypes: K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModelAttrTypes},
	"resource_list":         types.ObjectType{AttrTypes: K8SClusterRolePolicyRuleListPolicyRuleResourceListModelAttrTypes},
}

// K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel represents non_resource_url_list block
type K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel struct {
	Urls  types.List `tfsdk:"urls"`
	Verbs types.List `tfsdk:"verbs"`
}

// K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModelAttrTypes defines the attribute types for K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel
var K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModelAttrTypes = map[string]attr.Type{
	"urls":  types.ListType{ElemType: types.StringType},
	"verbs": types.ListType{ElemType: types.StringType},
}

// K8SClusterRolePolicyRuleListPolicyRuleResourceListModel represents resource_list block
type K8SClusterRolePolicyRuleListPolicyRuleResourceListModel struct {
	APIGroups         types.List `tfsdk:"api_groups"`
	ResourceInstances types.List `tfsdk:"resource_instances"`
	ResourceTypes     types.List `tfsdk:"resource_types"`
	Verbs             types.List `tfsdk:"verbs"`
}

// K8SClusterRolePolicyRuleListPolicyRuleResourceListModelAttrTypes defines the attribute types for K8SClusterRolePolicyRuleListPolicyRuleResourceListModel
var K8SClusterRolePolicyRuleListPolicyRuleResourceListModelAttrTypes = map[string]attr.Type{
	"api_groups":         types.ListType{ElemType: types.StringType},
	"resource_instances": types.ListType{ElemType: types.StringType},
	"resource_types":     types.ListType{ElemType: types.StringType},
	"verbs":              types.ListType{ElemType: types.StringType},
}

type K8SClusterRoleResourceModel struct {
	Name                   types.String                               `tfsdk:"name"`
	Namespace              types.String                               `tfsdk:"namespace"`
	Annotations            types.Map                                  `tfsdk:"annotations"`
	Description            types.String                               `tfsdk:"description"`
	Disable                types.Bool                                 `tfsdk:"disable"`
	Labels                 types.Map                                  `tfsdk:"labels"`
	ID                     types.String                               `tfsdk:"id"`
	Yaml                   types.String                               `tfsdk:"yaml"`
	Timeouts               timeouts.Value                             `tfsdk:"timeouts"`
	K8SClusterRoleSelector *K8SClusterRoleK8SClusterRoleSelectorModel `tfsdk:"k8s_cluster_role_selector"`
	PolicyRuleList         *K8SClusterRolePolicyRuleListModel         `tfsdk:"policy_rule_list"`
}

func (r *K8SClusterRoleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_k8s_cluster_role"
}

func (r *K8SClusterRoleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages k8s_cluster_role will create the object in the storage backend for namespace metadata.namespace. in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the K8S Cluster Role. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace for the K8S Cluster Role. The F5 XC API restricts this resource to the system namespace; it defaults to that value and may be omitted.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("system"),
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
					stringvalidator.OneOf("system"),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"yaml": schema.StringAttribute{
				MarkdownDescription: "Exclusive with [k8s_cluster_role_selector policy_rule_list] K8s YAML for ClusterRole.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 4096),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"k8s_cluster_role_selector": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: k8s_cluster_role_selector, policy_rule_list, yaml] Type can be used to establish a 'selector reference' from one object(called selector) to a set of other objects(called selectees) based on the value of expressions. A label selector is a label query over a set of resources. An empty label selector matches all objects.",
				Attributes: map[string]schema.Attribute{
					"expressions": schema.ListAttribute{
						MarkdownDescription: "Expressions contains the Kubernetes style label expression for selections.",
						Optional:            true,
						ElementType:         types.StringType,
						Validators: []validator.List{
							listvalidator.SizeAtMost(1),
						},
					},
				},
			},
			"policy_rule_list": schema.SingleNestedBlock{
				MarkdownDescription: "Policy Rule List. List of rules for role permissions.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"policy_rule": schema.ListNestedBlock{
						MarkdownDescription: "List of rules for role permissions .",
						NestedObject: schema.NestedBlockObject{
							Attributes: map[string]schema.Attribute{},
							Blocks: map[string]schema.Block{
								"non_resource_url_list": schema.SingleNestedBlock{
									MarkdownDescription: "Permissions for URL(s) that do not represent K8s resource.",
									Attributes: map[string]schema.Attribute{
										"urls": schema.ListAttribute{
											MarkdownDescription: "Allowed URL(s) that do not represent any K8s resource. URL can be suffix or regex.",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeBetween(1, 16),
											},
										},
										"verbs": schema.ListAttribute{
											MarkdownDescription: "Allowed list of verbs(operations) on resources. Use VerbAll for all operations .",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeBetween(1, 16),
											},
										},
									},
								},
								"resource_list": schema.SingleNestedBlock{
									MarkdownDescription: "List of resources in terms of API groups/resource types/resource instances and verbs allowed.",
									Attributes: map[string]schema.Attribute{
										"api_groups": schema.ListAttribute{
											MarkdownDescription: "Allowed list of API group that contains resources, all resources of a given API group .",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeBetween(1, 16),
											},
										},
										"resource_instances": schema.ListAttribute{
											MarkdownDescription: "Allowed list of resource instances within the resource types.",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeAtMost(16),
											},
										},
										"resource_types": schema.ListAttribute{
											MarkdownDescription: "Allowed list of resource types within the API groups.",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeBetween(1, 16),
											},
										},
										"verbs": schema.ListAttribute{
											MarkdownDescription: "Allowed list of verbs(operations) on resources. Use * for all operations .",
											Optional:            true,
											ElementType:         types.StringType,
											Validators: []validator.List{
												listvalidator.SizeBetween(1, 16),
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *K8SClusterRoleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *K8SClusterRoleResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data K8SClusterRoleResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *K8SClusterRoleResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the k8s_cluster_role from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan K8SClusterRoleResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *K8SClusterRoleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data K8SClusterRoleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating k8s_cluster_role", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.K8SClusterRole{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.K8SClusterRoleSelector != nil {
		K8SClusterRoleSelectorMap := make(map[string]interface{})
		if !data.K8SClusterRoleSelector.Expressions.IsNull() && !data.K8SClusterRoleSelector.Expressions.IsUnknown() {
			var ExpressionsItems []string
			diags := data.K8SClusterRoleSelector.Expressions.ElementsAs(ctx, &ExpressionsItems, false)
			if !diags.HasError() {
				K8SClusterRoleSelectorMap["expressions"] = ExpressionsItems
			}
		}
		createReq.Spec["k8s_cluster_role_selector"] = K8SClusterRoleSelectorMap
	}
	if data.PolicyRuleList != nil {
		PolicyRuleListMap := make(map[string]interface{})
		if len(data.PolicyRuleList.PolicyRule) > 0 {
			var PolicyRuleList []map[string]interface{}
			for _, PolicyRuleItem := range data.PolicyRuleList.PolicyRule {
				PolicyRuleItemMap := make(map[string]interface{})
				if PolicyRuleItem.NonResourceURLList != nil {
					NonResourceURLListMap := make(map[string]interface{})
					if !PolicyRuleItem.NonResourceURLList.Urls.IsNull() && !PolicyRuleItem.NonResourceURLList.Urls.IsUnknown() {
						var UrlsItems []string
						diags := PolicyRuleItem.NonResourceURLList.Urls.ElementsAs(ctx, &UrlsItems, false)
						if !diags.HasError() {
							NonResourceURLListMap["urls"] = UrlsItems
						}
					}
					if !PolicyRuleItem.NonResourceURLList.Verbs.IsNull() && !PolicyRuleItem.NonResourceURLList.Verbs.IsUnknown() {
						var VerbsItems []string
						diags := PolicyRuleItem.NonResourceURLList.Verbs.ElementsAs(ctx, &VerbsItems, false)
						if !diags.HasError() {
							NonResourceURLListMap["verbs"] = VerbsItems
						}
					}
					PolicyRuleItemMap["non_resource_url_list"] = NonResourceURLListMap
				}
				if PolicyRuleItem.ResourceList != nil {
					ResourceListMap := make(map[string]interface{})
					if !PolicyRuleItem.ResourceList.APIGroups.IsNull() && !PolicyRuleItem.ResourceList.APIGroups.IsUnknown() {
						var APIGroupsItems []string
						diags := PolicyRuleItem.ResourceList.APIGroups.ElementsAs(ctx, &APIGroupsItems, false)
						if !diags.HasError() {
							ResourceListMap["api_groups"] = APIGroupsItems
						}
					}
					if !PolicyRuleItem.ResourceList.ResourceInstances.IsNull() && !PolicyRuleItem.ResourceList.ResourceInstances.IsUnknown() {
						var ResourceInstancesItems []string
						diags := PolicyRuleItem.ResourceList.ResourceInstances.ElementsAs(ctx, &ResourceInstancesItems, false)
						if !diags.HasError() {
							ResourceListMap["resource_instances"] = ResourceInstancesItems
						}
					}
					if !PolicyRuleItem.ResourceList.ResourceTypes.IsNull() && !PolicyRuleItem.ResourceList.ResourceTypes.IsUnknown() {
						var ResourceTypesItems []string
						diags := PolicyRuleItem.ResourceList.ResourceTypes.ElementsAs(ctx, &ResourceTypesItems, false)
						if !diags.HasError() {
							ResourceListMap["resource_types"] = ResourceTypesItems
						}
					}
					if !PolicyRuleItem.ResourceList.Verbs.IsNull() && !PolicyRuleItem.ResourceList.Verbs.IsUnknown() {
						var VerbsItems []string
						diags := PolicyRuleItem.ResourceList.Verbs.ElementsAs(ctx, &VerbsItems, false)
						if !diags.HasError() {
							ResourceListMap["verbs"] = VerbsItems
						}
					}
					PolicyRuleItemMap["resource_list"] = ResourceListMap
				}
				PolicyRuleList = append(PolicyRuleList, PolicyRuleItemMap)
			}
			PolicyRuleListMap["policy_rule"] = PolicyRuleList
		}
		createReq.Spec["policy_rule_list"] = PolicyRuleListMap
	}
	if !data.Yaml.IsNull() && !data.Yaml.IsUnknown() {
		createReq.Spec["yaml"] = data.Yaml.ValueString()
	}

	apiResource, err := r.client.CreateK8SClusterRole(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create K8SClusterRole: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if blockData, ok := apiResource.Spec["k8s_cluster_role_selector"].(map[string]interface{}); ok && (isImport || data.K8SClusterRoleSelector != nil) {
		data.K8SClusterRoleSelector = &K8SClusterRoleK8SClusterRoleSelectorModel{
			Expressions: func() types.List {
				if v, ok := blockData["expressions"].([]interface{}); ok && len(v) > 0 {
					var items []string
					for _, item := range v {
						if s, ok := item.(string); ok {
							items = append(items, s)
						}
					}
					listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
					return listVal
				}
				return types.ListNull(types.StringType)
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["policy_rule_list"].(map[string]interface{}); ok && (isImport || data.PolicyRuleList != nil) {
		data.PolicyRuleList = &K8SClusterRolePolicyRuleListModel{
			PolicyRule: func() []K8SClusterRolePolicyRuleListPolicyRuleModel {
				if !isImport && data.PolicyRuleList != nil && len(data.PolicyRuleList.PolicyRule) == 0 {
					return nil
				}
				if rawList, ok := blockData["policy_rule"].([]interface{}); ok && len(rawList) > 0 {
					var PolicyRuleResult []K8SClusterRolePolicyRuleListPolicyRuleModel
					for _, PolicyRuleItem := range rawList {
						if PolicyRuleItemMap, ok := PolicyRuleItem.(map[string]interface{}); ok {
							PolicyRuleResult = append(PolicyRuleResult, K8SClusterRolePolicyRuleListPolicyRuleModel{
								NonResourceURLList: func() *K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel {
									if NonResourceURLListData, ok := PolicyRuleItemMap["non_resource_url_list"].(map[string]interface{}); ok {
										return &K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel{
											Urls: func() types.List {
												if v, ok := NonResourceURLListData["urls"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											Verbs: func() types.List {
												if v, ok := NonResourceURLListData["verbs"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								ResourceList: func() *K8SClusterRolePolicyRuleListPolicyRuleResourceListModel {
									if ResourceListData, ok := PolicyRuleItemMap["resource_list"].(map[string]interface{}); ok {
										return &K8SClusterRolePolicyRuleListPolicyRuleResourceListModel{
											APIGroups: func() types.List {
												if v, ok := ResourceListData["api_groups"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											ResourceInstances: func() types.List {
												if v, ok := ResourceListData["resource_instances"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											ResourceTypes: func() types.List {
												if v, ok := ResourceListData["resource_types"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											Verbs: func() types.List {
												if v, ok := ResourceListData["verbs"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
							})
						}
					}
					return PolicyRuleResult
				}
				return nil
			}(),
		}
	}
	if v, ok := apiResource.Spec["yaml"].(string); ok && v != "" {
		data.Yaml = types.StringValue(v)
	} else {
		data.Yaml = types.StringNull()
	}

	tflog.Trace(ctx, "created K8SClusterRole resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *K8SClusterRoleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data K8SClusterRoleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetK8SClusterRole(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "K8SClusterRole not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		// Some F5 XC APIs do not implement GET-by-name (read returns 501 Not
		// Implemented — e.g. the shape/csd domain objects, which support only
		// list/create/delete). Treat that as "cannot refresh" and preserve the
		// prior state rather than erroring, so the resource stays manageable and
		// idempotent (create/delete still work).
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "K8SClusterRole read not implemented by API (501); keeping prior state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read K8SClusterRole: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if blockData, ok := apiResource.Spec["k8s_cluster_role_selector"].(map[string]interface{}); ok && (isImport || data.K8SClusterRoleSelector != nil) {
		data.K8SClusterRoleSelector = &K8SClusterRoleK8SClusterRoleSelectorModel{
			Expressions: func() types.List {
				if v, ok := blockData["expressions"].([]interface{}); ok && len(v) > 0 {
					var items []string
					for _, item := range v {
						if s, ok := item.(string); ok {
							items = append(items, s)
						}
					}
					listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
					return listVal
				}
				return types.ListNull(types.StringType)
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["policy_rule_list"].(map[string]interface{}); ok && (isImport || data.PolicyRuleList != nil) {
		data.PolicyRuleList = &K8SClusterRolePolicyRuleListModel{
			PolicyRule: func() []K8SClusterRolePolicyRuleListPolicyRuleModel {
				if !isImport && data.PolicyRuleList != nil && len(data.PolicyRuleList.PolicyRule) == 0 {
					return nil
				}
				if rawList, ok := blockData["policy_rule"].([]interface{}); ok && len(rawList) > 0 {
					var PolicyRuleResult []K8SClusterRolePolicyRuleListPolicyRuleModel
					for _, PolicyRuleItem := range rawList {
						if PolicyRuleItemMap, ok := PolicyRuleItem.(map[string]interface{}); ok {
							PolicyRuleResult = append(PolicyRuleResult, K8SClusterRolePolicyRuleListPolicyRuleModel{
								NonResourceURLList: func() *K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel {
									if NonResourceURLListData, ok := PolicyRuleItemMap["non_resource_url_list"].(map[string]interface{}); ok {
										return &K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel{
											Urls: func() types.List {
												if v, ok := NonResourceURLListData["urls"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											Verbs: func() types.List {
												if v, ok := NonResourceURLListData["verbs"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								ResourceList: func() *K8SClusterRolePolicyRuleListPolicyRuleResourceListModel {
									if ResourceListData, ok := PolicyRuleItemMap["resource_list"].(map[string]interface{}); ok {
										return &K8SClusterRolePolicyRuleListPolicyRuleResourceListModel{
											APIGroups: func() types.List {
												if v, ok := ResourceListData["api_groups"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											ResourceInstances: func() types.List {
												if v, ok := ResourceListData["resource_instances"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											ResourceTypes: func() types.List {
												if v, ok := ResourceListData["resource_types"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											Verbs: func() types.List {
												if v, ok := ResourceListData["verbs"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
							})
						}
					}
					return PolicyRuleResult
				}
				return nil
			}(),
		}
	}
	if v, ok := apiResource.Spec["yaml"].(string); ok && v != "" {
		data.Yaml = types.StringValue(v)
	} else {
		data.Yaml = types.StringNull()
	}

	// The import marker is a one-shot signal for the import Read only. Clear it so every
	// subsequent refresh runs as a normal Read with drift-preservation; otherwise the
	// resource stays in "import mode" forever and re-reads server-managed fields the user
	// never configured, producing perpetual plan drift.
	if isImport {
		resp.Diagnostics.Append(resp.Private.SetKey(ctx, "isImport", nil)...)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *K8SClusterRoleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data K8SClusterRoleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.K8SClusterRole{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.K8SClusterRoleSelector != nil {
		K8SClusterRoleSelectorMap := make(map[string]interface{})
		if !data.K8SClusterRoleSelector.Expressions.IsNull() && !data.K8SClusterRoleSelector.Expressions.IsUnknown() {
			var ExpressionsItems []string
			diags := data.K8SClusterRoleSelector.Expressions.ElementsAs(ctx, &ExpressionsItems, false)
			if !diags.HasError() {
				K8SClusterRoleSelectorMap["expressions"] = ExpressionsItems
			}
		}
		apiResource.Spec["k8s_cluster_role_selector"] = K8SClusterRoleSelectorMap
	}
	if data.PolicyRuleList != nil {
		PolicyRuleListMap := make(map[string]interface{})
		if len(data.PolicyRuleList.PolicyRule) > 0 {
			var PolicyRuleList []map[string]interface{}
			for _, PolicyRuleItem := range data.PolicyRuleList.PolicyRule {
				PolicyRuleItemMap := make(map[string]interface{})
				if PolicyRuleItem.NonResourceURLList != nil {
					NonResourceURLListMap := make(map[string]interface{})
					if !PolicyRuleItem.NonResourceURLList.Urls.IsNull() && !PolicyRuleItem.NonResourceURLList.Urls.IsUnknown() {
						var UrlsItems []string
						diags := PolicyRuleItem.NonResourceURLList.Urls.ElementsAs(ctx, &UrlsItems, false)
						if !diags.HasError() {
							NonResourceURLListMap["urls"] = UrlsItems
						}
					}
					if !PolicyRuleItem.NonResourceURLList.Verbs.IsNull() && !PolicyRuleItem.NonResourceURLList.Verbs.IsUnknown() {
						var VerbsItems []string
						diags := PolicyRuleItem.NonResourceURLList.Verbs.ElementsAs(ctx, &VerbsItems, false)
						if !diags.HasError() {
							NonResourceURLListMap["verbs"] = VerbsItems
						}
					}
					PolicyRuleItemMap["non_resource_url_list"] = NonResourceURLListMap
				}
				if PolicyRuleItem.ResourceList != nil {
					ResourceListMap := make(map[string]interface{})
					if !PolicyRuleItem.ResourceList.APIGroups.IsNull() && !PolicyRuleItem.ResourceList.APIGroups.IsUnknown() {
						var APIGroupsItems []string
						diags := PolicyRuleItem.ResourceList.APIGroups.ElementsAs(ctx, &APIGroupsItems, false)
						if !diags.HasError() {
							ResourceListMap["api_groups"] = APIGroupsItems
						}
					}
					if !PolicyRuleItem.ResourceList.ResourceInstances.IsNull() && !PolicyRuleItem.ResourceList.ResourceInstances.IsUnknown() {
						var ResourceInstancesItems []string
						diags := PolicyRuleItem.ResourceList.ResourceInstances.ElementsAs(ctx, &ResourceInstancesItems, false)
						if !diags.HasError() {
							ResourceListMap["resource_instances"] = ResourceInstancesItems
						}
					}
					if !PolicyRuleItem.ResourceList.ResourceTypes.IsNull() && !PolicyRuleItem.ResourceList.ResourceTypes.IsUnknown() {
						var ResourceTypesItems []string
						diags := PolicyRuleItem.ResourceList.ResourceTypes.ElementsAs(ctx, &ResourceTypesItems, false)
						if !diags.HasError() {
							ResourceListMap["resource_types"] = ResourceTypesItems
						}
					}
					if !PolicyRuleItem.ResourceList.Verbs.IsNull() && !PolicyRuleItem.ResourceList.Verbs.IsUnknown() {
						var VerbsItems []string
						diags := PolicyRuleItem.ResourceList.Verbs.ElementsAs(ctx, &VerbsItems, false)
						if !diags.HasError() {
							ResourceListMap["verbs"] = VerbsItems
						}
					}
					PolicyRuleItemMap["resource_list"] = ResourceListMap
				}
				PolicyRuleList = append(PolicyRuleList, PolicyRuleItemMap)
			}
			PolicyRuleListMap["policy_rule"] = PolicyRuleList
		}
		apiResource.Spec["policy_rule_list"] = PolicyRuleListMap
	}
	if !data.Yaml.IsNull() && !data.Yaml.IsUnknown() {
		apiResource.Spec["yaml"] = data.Yaml.ValueString()
	}

	_, err := r.client.UpdateK8SClusterRole(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update K8SClusterRole: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetK8SClusterRole(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read K8SClusterRole after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response
	if v, ok := fetched.Spec["yaml"].(string); ok && v != "" {
		data.Yaml = types.StringValue(v)
	} else if data.Yaml.IsUnknown() {
		// API didn't return value and plan was unknown - set to null
		data.Yaml = types.StringNull()
	}
	// If plan had a value, preserve it

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if blockData, ok := apiResource.Spec["k8s_cluster_role_selector"].(map[string]interface{}); ok && (isImport || data.K8SClusterRoleSelector != nil) {
		data.K8SClusterRoleSelector = &K8SClusterRoleK8SClusterRoleSelectorModel{
			Expressions: func() types.List {
				if v, ok := blockData["expressions"].([]interface{}); ok && len(v) > 0 {
					var items []string
					for _, item := range v {
						if s, ok := item.(string); ok {
							items = append(items, s)
						}
					}
					listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
					return listVal
				}
				return types.ListNull(types.StringType)
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["policy_rule_list"].(map[string]interface{}); ok && (isImport || data.PolicyRuleList != nil) {
		data.PolicyRuleList = &K8SClusterRolePolicyRuleListModel{
			PolicyRule: func() []K8SClusterRolePolicyRuleListPolicyRuleModel {
				if !isImport && data.PolicyRuleList != nil && len(data.PolicyRuleList.PolicyRule) == 0 {
					return nil
				}
				if rawList, ok := blockData["policy_rule"].([]interface{}); ok && len(rawList) > 0 {
					var PolicyRuleResult []K8SClusterRolePolicyRuleListPolicyRuleModel
					for _, PolicyRuleItem := range rawList {
						if PolicyRuleItemMap, ok := PolicyRuleItem.(map[string]interface{}); ok {
							PolicyRuleResult = append(PolicyRuleResult, K8SClusterRolePolicyRuleListPolicyRuleModel{
								NonResourceURLList: func() *K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel {
									if NonResourceURLListData, ok := PolicyRuleItemMap["non_resource_url_list"].(map[string]interface{}); ok {
										return &K8SClusterRolePolicyRuleListPolicyRuleNonResourceURLListModel{
											Urls: func() types.List {
												if v, ok := NonResourceURLListData["urls"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											Verbs: func() types.List {
												if v, ok := NonResourceURLListData["verbs"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
								ResourceList: func() *K8SClusterRolePolicyRuleListPolicyRuleResourceListModel {
									if ResourceListData, ok := PolicyRuleItemMap["resource_list"].(map[string]interface{}); ok {
										return &K8SClusterRolePolicyRuleListPolicyRuleResourceListModel{
											APIGroups: func() types.List {
												if v, ok := ResourceListData["api_groups"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											ResourceInstances: func() types.List {
												if v, ok := ResourceListData["resource_instances"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											ResourceTypes: func() types.List {
												if v, ok := ResourceListData["resource_types"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
											Verbs: func() types.List {
												if v, ok := ResourceListData["verbs"].([]interface{}); ok && len(v) > 0 {
													var items []string
													for _, item := range v {
														if s, ok := item.(string); ok {
															items = append(items, s)
														}
													}
													listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
													return listVal
												}
												return types.ListNull(types.StringType)
											}(),
										}
									}
									return nil
								}(),
							})
						}
					}
					return PolicyRuleResult
				}
				return nil
			}(),
		}
	}
	if v, ok := apiResource.Spec["yaml"].(string); ok && v != "" {
		data.Yaml = types.StringValue(v)
	} else {
		data.Yaml = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *K8SClusterRoleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data K8SClusterRoleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

	// Delete with bounded retry on transient referential BAD_REQUEST: during teardown a
	// resource can briefly still be referenced by another object (a healthcheck by an origin
	// pool, an origin pool by a load balancer, etc.), which the API rejects with 400 until
	// the referrer is gone. NOT_FOUND/404 (already deleted) and 501 (delete unsupported) are
	// terminal and handled after the loop.
	var err error
	for attempt := 0; ; attempt++ {
		err = r.client.DeleteK8SClusterRole(ctx, data.Namespace.ValueString(), data.Name.ValueString())
		if err == nil {
			break
		}
		msg := err.Error()
		transient := (strings.Contains(msg, "400") || strings.Contains(msg, "BAD_REQUEST")) &&
			!strings.Contains(msg, "NOT_FOUND") && !strings.Contains(msg, "404") && !strings.Contains(msg, "501")
		if !transient || attempt >= 5 {
			break
		}
		tflog.Warn(ctx, "K8SClusterRole delete hit transient BAD_REQUEST (likely still referenced); retrying", map[string]interface{}{
			"name":      data.Name.ValueString(),
			"namespace": data.Namespace.ValueString(),
			"attempt":   attempt + 1,
		})
		select {
		case <-ctx.Done():
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Timed out retrying delete of K8SClusterRole (still referenced): %s", err))
			return
		case <-time.After(5 * time.Second):
		}
	}
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "K8SClusterRole already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "K8SClusterRole delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete K8SClusterRole: %s", err))
		return
	}
}

func (r *K8SClusterRoleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
