// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
)

var (
	_ datasource.DataSource              = &LogReceiverDataSource{}
	_ datasource.DataSourceWithConfigure = &LogReceiverDataSource{}
)

func NewLogReceiverDataSource() datasource.DataSource {
	return &LogReceiverDataSource{}
}

type LogReceiverDataSource struct {
	client *client.Client
}

type LogReceiverDataSourceModel struct {
	ID          types.String            `tfsdk:"id"`
	Name        types.String            `tfsdk:"name"`
	Namespace   types.String            `tfsdk:"namespace"`
	Description types.String            `tfsdk:"description"`
	Labels      types.Map               `tfsdk:"labels"`
	Annotations types.Map               `tfsdk:"annotations"`
	SiteLocal   *LogReceiverEmptyModel  `tfsdk:"site_local"`
	Syslog      *LogReceiverSyslogModel `tfsdk:"syslog"`
}

func (d *LogReceiverDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_log_receiver"
}

func (d *LogReceiverDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages new Log Receiver object in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the LogReceiver.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the LogReceiver exists.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description of the LogReceiver.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels applied to this resource.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations applied to this resource.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"site_local": schema.SingleNestedAttribute{
				MarkdownDescription: "Enable this option",
				Attributes:          map[string]schema.Attribute{},
				Computed:            true,
			},
			"syslog": schema.SingleNestedAttribute{
				MarkdownDescription: "Syslog Server Configuration. Configuration for syslog server.",
				Attributes: map[string]schema.Attribute{
					"syslog_rfc5424": schema.Int64Attribute{
						MarkdownDescription: "Exclusive with [] Select RFC5424 syslog format and maximum message length.",
						Computed:            true,
					},
					"tcp_server": schema.SingleNestedAttribute{
						MarkdownDescription: "TCP Server name and Port Number. Name and port number for a TCP server.",
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								MarkdownDescription: "Port Number. Port number used for communication.",
								Computed:            true,
							},
							"server_name": schema.StringAttribute{
								MarkdownDescription: "Server name is fully qualified domain name or IP address of the server.",
								Computed:            true,
							},
						},
						Computed: true,
					},
					"tls_server": schema.SingleNestedAttribute{
						MarkdownDescription: "TLS config for client of discovery service.",
						Attributes: map[string]schema.Attribute{
							"default_https_port": schema.ObjectAttribute{
								MarkdownDescription: "Enable this option",
								Computed:            true,
								AttributeTypes:      map[string]attr.Type{},
							},
							"default_syslog_tls_port": schema.ObjectAttribute{
								MarkdownDescription: "Enable this option",
								Computed:            true,
								AttributeTypes:      map[string]attr.Type{},
							},
							"mtls_disabled": schema.ObjectAttribute{
								MarkdownDescription: "Enable this option",
								Computed:            true,
								AttributeTypes:      map[string]attr.Type{},
							},
							"mtls_enable": schema.SingleNestedAttribute{
								MarkdownDescription: "Configuration parameter for mtls enable.",
								Attributes: map[string]schema.Attribute{
									"certificate": schema.StringAttribute{
										MarkdownDescription: "Client certificate is PEM-encoded certificate or certificate-chain.",
										Computed:            true,
									},
									"key_url": schema.SingleNestedAttribute{
										MarkdownDescription: "SecretType is used in an object to indicate a sensitive/confidential field.",
										Attributes: map[string]schema.Attribute{
											"blindfold_secret_info": schema.SingleNestedAttribute{
												MarkdownDescription: "BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management.",
												Attributes: map[string]schema.Attribute{
													"decryption_provider": schema.StringAttribute{
														MarkdownDescription: "Name of the Secret Management Access object that contains information about the backend Secret Management service.",
														Computed:            true,
													},
													"location": schema.StringAttribute{
														MarkdownDescription: "Location is the uri_ref. It could be in URL format for string:/// Or it could be a path if the store provider is an HTTP/HTTPS location.",
														Computed:            true,
														Sensitive:           true,
													},
													"store_provider": schema.StringAttribute{
														MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
														Computed:            true,
													},
												},
												Computed: true,
											},
											"clear_secret_info": schema.SingleNestedAttribute{
												MarkdownDescription: "ClearSecretInfoType specifies information about the Secret that is not encrypted.",
												Attributes: map[string]schema.Attribute{
													"provider_ref": schema.StringAttribute{
														MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
														Computed:            true,
													},
													"url": schema.StringAttribute{
														MarkdownDescription: "URL of the secret. Currently supported URL schemes is string:///. For string:/// scheme, Secret needs to be encoded Base64 format. When asked for this secret, caller will GET Secret bytes after Base64 decoding.",
														Computed:            true,
														Sensitive:           true,
													},
												},
												Computed: true,
											},
										},
										Computed: true,
									},
								},
								Computed: true,
							},
							"port": schema.Int64Attribute{
								MarkdownDescription: "Exclusive with [default_https_port default_syslog_tls_port] Custom port number used for communication.",
								Computed:            true,
							},
							"server_name": schema.StringAttribute{
								MarkdownDescription: "ServerName is passed to the server for SNI and is used in the client to check server certificates against.",
								Computed:            true,
							},
							"trusted_ca_url": schema.StringAttribute{
								MarkdownDescription: "Exclusive with [volterra_ca] The URL or value for trusted Server CA certificate or certificate chain Certificates in PEM format including the PEM headers.",
								Computed:            true,
							},
							"volterra_ca": schema.ObjectAttribute{
								MarkdownDescription: "Configuration parameter for volterra ca.",
								Computed:            true,
								AttributeTypes:      map[string]attr.Type{},
							},
						},
						Computed: true,
					},
					"udp_server": schema.SingleNestedAttribute{
						MarkdownDescription: "UDP Server Name and Port Number. Name and port number for a UDP server.",
						Attributes: map[string]schema.Attribute{
							"port": schema.Int64Attribute{
								MarkdownDescription: "Port Number. Port number used for communication.",
								Computed:            true,
							},
							"server_name": schema.StringAttribute{
								MarkdownDescription: "Server name is fully qualified domain name or IP address of the server.",
								Computed:            true,
							},
						},
						Computed: true,
					},
				},
				Computed: true,
			},
		},
	}
}

func (d *LogReceiverDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *LogReceiverDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data LogReceiverDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	namespace := data.Namespace.ValueString()
	resource, err := d.client.GetLogReceiver(ctx, namespace, data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read LogReceiver: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	if resource.Metadata.Namespace != "" {
		data.Namespace = types.StringValue(resource.Metadata.Namespace)
	} else {
		data.Namespace = types.StringValue(namespace)
	}
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Prefix filtering only, never the discovery labels (#1391). A data source cannot
	// propose deleting anything, so filtering them here would buy no convergence and
	// would only hide hw-model and friends from a caller that asked for the object.
	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels, false)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}
	apiResource := resource
	isImport := true
	if _, ok := apiResource.Spec["site_local"].(map[string]interface{}); ok && isImport && data.SiteLocal == nil {
		data.SiteLocal = &LogReceiverEmptyModel{}
	}
	if blockData, ok := apiResource.Spec["syslog"].(map[string]interface{}); ok && (isImport || data.Syslog != nil) {
		data.Syslog = &LogReceiverSyslogModel{
			SyslogRfc5424: func() types.Int64 {
				if v, ok := blockData["syslog_rfc5424"].(float64); ok && v != 0 {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
			TCPServer: func() *LogReceiverSyslogTCPServerModel {
				if TCPServerData, ok := blockData["tcp_server"].(map[string]interface{}); ok {
					return &LogReceiverSyslogTCPServerModel{
						Port: func() types.Int64 {
							if v, ok := TCPServerData["port"].(float64); ok && v != 0 {
								return types.Int64Value(int64(v))
							}
							return types.Int64Null()
						}(),
						ServerName: func() types.String {
							if v, ok := TCPServerData["server_name"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
			TLSServer: func() *LogReceiverSyslogTLSServerModel {
				if TLSServerData, ok := blockData["tls_server"].(map[string]interface{}); ok {
					return &LogReceiverSyslogTLSServerModel{
						DefaultHTTPSPort: func() types.Object {
							if !isImport && data.Syslog != nil && data.Syslog.TLSServer != nil && !data.Syslog.TLSServer.DefaultHTTPSPort.IsUnknown() {
								return data.Syslog.TLSServer.DefaultHTTPSPort
							}
							if _, ok := TLSServerData["default_https_port"].(map[string]interface{}); ok {
								return types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})
							}
							return types.ObjectNull(map[string]attr.Type{})
						}(),
						DefaultSyslogTLSPort: func() types.Object {
							if !isImport && data.Syslog != nil && data.Syslog.TLSServer != nil && !data.Syslog.TLSServer.DefaultSyslogTLSPort.IsUnknown() {
								return data.Syslog.TLSServer.DefaultSyslogTLSPort
							}
							if _, ok := TLSServerData["default_syslog_tls_port"].(map[string]interface{}); ok {
								return types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})
							}
							return types.ObjectNull(map[string]attr.Type{})
						}(),
						MtlsDisabled: func() types.Object {
							if !isImport && data.Syslog != nil && data.Syslog.TLSServer != nil && !data.Syslog.TLSServer.MtlsDisabled.IsUnknown() {
								return data.Syslog.TLSServer.MtlsDisabled
							}
							if _, ok := TLSServerData["mtls_disabled"].(map[string]interface{}); ok {
								return types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})
							}
							return types.ObjectNull(map[string]attr.Type{})
						}(),
						MtlsEnable: func() *LogReceiverSyslogTLSServerMtlsEnableModel {
							if MtlsEnableData, ok := TLSServerData["mtls_enable"].(map[string]interface{}); ok {
								return &LogReceiverSyslogTLSServerMtlsEnableModel{
									Certificate: func() types.String {
										if v, ok := MtlsEnableData["certificate"].(string); ok && v != "" {
											return types.StringValue(v)
										}
										return types.StringNull()
									}(),
									KeyURL: func() *LogReceiverSyslogTLSServerMtlsEnableKeyURLModel {
										if KeyURLData, ok := MtlsEnableData["key_url"].(map[string]interface{}); ok {
											return &LogReceiverSyslogTLSServerMtlsEnableKeyURLModel{
												BlindfoldSecretInfo: func() *LogReceiverSyslogTLSServerMtlsEnableKeyURLBlindfoldSecretInfoModel {
													if BlindfoldSecretInfoData, ok := KeyURLData["blindfold_secret_info"].(map[string]interface{}); ok {
														return &LogReceiverSyslogTLSServerMtlsEnableKeyURLBlindfoldSecretInfoModel{
															DecryptionProvider: func() types.String {
																if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
																	return types.StringValue(v)
																}
																return types.StringNull()
															}(),
															Location: func() types.String {
																if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
																	return types.StringValue(v)
																}
																return types.StringNull()
															}(),
															StoreProvider: func() types.String {
																if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
																	return types.StringValue(v)
																}
																return types.StringNull()
															}(),
														}
													}
													return nil
												}(),
												ClearSecretInfo: func() *LogReceiverSyslogTLSServerMtlsEnableKeyURLClearSecretInfoModel {
													if ClearSecretInfoData, ok := KeyURLData["clear_secret_info"].(map[string]interface{}); ok {
														return &LogReceiverSyslogTLSServerMtlsEnableKeyURLClearSecretInfoModel{
															Provider: func() types.String {
																if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
																	return types.StringValue(v)
																}
																return types.StringNull()
															}(),
															URL: func() types.String {
																if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
																	return types.StringValue(v)
																}
																return types.StringNull()
															}(),
														}
													}
													return nil
												}(),
											}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
						Port: func() types.Int64 {
							if v, ok := TLSServerData["port"].(float64); ok && v != 0 {
								return types.Int64Value(int64(v))
							}
							return types.Int64Null()
						}(),
						ServerName: func() types.String {
							if v, ok := TLSServerData["server_name"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						TrustedCAURL: func() types.String {
							if v, ok := TLSServerData["trusted_ca_url"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
						VolterraCA: func() types.Object {
							if !isImport && data.Syslog != nil && data.Syslog.TLSServer != nil && !data.Syslog.TLSServer.VolterraCA.IsUnknown() {
								return data.Syslog.TLSServer.VolterraCA
							}
							if _, ok := TLSServerData["volterra_ca"].(map[string]interface{}); ok {
								return types.ObjectValueMust(map[string]attr.Type{}, map[string]attr.Value{})
							}
							return types.ObjectNull(map[string]attr.Type{})
						}(),
					}
				}
				return nil
			}(),
			UDPServer: func() *LogReceiverSyslogUDPServerModel {
				if UDPServerData, ok := blockData["udp_server"].(map[string]interface{}); ok {
					return &LogReceiverSyslogUDPServerModel{
						Port: func() types.Int64 {
							if v, ok := UDPServerData["port"].(float64); ok && v != 0 {
								return types.Int64Value(int64(v))
							}
							return types.Int64Null()
						}(),
						ServerName: func() types.String {
							if v, ok := UDPServerData["server_name"].(string); ok && v != "" {
								return types.StringValue(v)
							}
							return types.StringNull()
						}(),
					}
				}
				return nil
			}(),
		}
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
