// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"regexp"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
	xcsherrors "github.com/f5-sales-demo/terraform-provider-xcsh/internal/errors"
	inttimeouts "github.com/f5-sales-demo/terraform-provider-xcsh/internal/timeouts"
	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &RateLimiterResource{}
	_ resource.ResourceWithConfigure      = &RateLimiterResource{}
	_ resource.ResourceWithImportState    = &RateLimiterResource{}
	_ resource.ResourceWithModifyPlan     = &RateLimiterResource{}
	_ resource.ResourceWithValidateConfig = &RateLimiterResource{}
)

func NewRateLimiterResource() resource.Resource {
	return &RateLimiterResource{}
}

type RateLimiterResource struct {
	client *client.Client
}

// RateLimiterEmptyModel represents empty nested blocks
type RateLimiterEmptyModel struct {
}

// RateLimiterLimitsModel represents limits block
type RateLimiterLimitsModel struct {
	BurstMultiplier  types.Int64                        `tfsdk:"burst_multiplier"`
	PeriodMultiplier types.Int64                        `tfsdk:"period_multiplier"`
	TotalNumber      types.Int64                        `tfsdk:"total_number"`
	Unit             types.String                       `tfsdk:"unit"`
	ActionBlock      *RateLimiterLimitsActionBlockModel `tfsdk:"action_block"`
	Disabled         *RateLimiterEmptyModel             `tfsdk:"disabled"`
	LeakyBucket      *RateLimiterEmptyModel             `tfsdk:"leaky_bucket"`
	TokenBucket      *RateLimiterEmptyModel             `tfsdk:"token_bucket"`
}

// RateLimiterLimitsModelAttrTypes defines the attribute types for RateLimiterLimitsModel
var RateLimiterLimitsModelAttrTypes = map[string]attr.Type{
	"burst_multiplier":  types.Int64Type,
	"period_multiplier": types.Int64Type,
	"total_number":      types.Int64Type,
	"unit":              types.StringType,
	"action_block":      types.ObjectType{AttrTypes: RateLimiterLimitsActionBlockModelAttrTypes},
	"disabled":          types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"leaky_bucket":      types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"token_bucket":      types.ObjectType{AttrTypes: map[string]attr.Type{}},
}

// RateLimiterLimitsActionBlockModel represents action_block block
type RateLimiterLimitsActionBlockModel struct {
	Hours   *RateLimiterLimitsActionBlockHoursModel   `tfsdk:"hours"`
	Minutes *RateLimiterLimitsActionBlockMinutesModel `tfsdk:"minutes"`
	Seconds *RateLimiterLimitsActionBlockSecondsModel `tfsdk:"seconds"`
}

// RateLimiterLimitsActionBlockModelAttrTypes defines the attribute types for RateLimiterLimitsActionBlockModel
var RateLimiterLimitsActionBlockModelAttrTypes = map[string]attr.Type{
	"hours":   types.ObjectType{AttrTypes: RateLimiterLimitsActionBlockHoursModelAttrTypes},
	"minutes": types.ObjectType{AttrTypes: RateLimiterLimitsActionBlockMinutesModelAttrTypes},
	"seconds": types.ObjectType{AttrTypes: RateLimiterLimitsActionBlockSecondsModelAttrTypes},
}

// RateLimiterLimitsActionBlockHoursModel represents hours block
type RateLimiterLimitsActionBlockHoursModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// RateLimiterLimitsActionBlockHoursModelAttrTypes defines the attribute types for RateLimiterLimitsActionBlockHoursModel
var RateLimiterLimitsActionBlockHoursModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

// RateLimiterLimitsActionBlockMinutesModel represents minutes block
type RateLimiterLimitsActionBlockMinutesModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// RateLimiterLimitsActionBlockMinutesModelAttrTypes defines the attribute types for RateLimiterLimitsActionBlockMinutesModel
var RateLimiterLimitsActionBlockMinutesModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

// RateLimiterLimitsActionBlockSecondsModel represents seconds block
type RateLimiterLimitsActionBlockSecondsModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// RateLimiterLimitsActionBlockSecondsModelAttrTypes defines the attribute types for RateLimiterLimitsActionBlockSecondsModel
var RateLimiterLimitsActionBlockSecondsModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

// RateLimiterUserIdentificationModel represents user_identification block
type RateLimiterUserIdentificationModel struct {
	Kind      types.String `tfsdk:"kind"`
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
	Uid       types.String `tfsdk:"uid"`
}

// RateLimiterUserIdentificationModelAttrTypes defines the attribute types for RateLimiterUserIdentificationModel
var RateLimiterUserIdentificationModelAttrTypes = map[string]attr.Type{
	"kind":      types.StringType,
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
	"uid":       types.StringType,
}

type RateLimiterResourceModel struct {
	Name               types.String   `tfsdk:"name"`
	Namespace          types.String   `tfsdk:"namespace"`
	Annotations        types.Map      `tfsdk:"annotations"`
	Description        types.String   `tfsdk:"description"`
	Disable            types.Bool     `tfsdk:"disable"`
	Labels             types.Map      `tfsdk:"labels"`
	ID                 types.String   `tfsdk:"id"`
	Timeouts           timeouts.Value `tfsdk:"timeouts"`
	Limits             types.List     `tfsdk:"limits"`
	UserIdentification types.List     `tfsdk:"user_identification"`
}

func (r *RateLimiterResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_rate_limiter"
}

func (r *RateLimiterResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages rate_limiter creates a new object in the storage backend for metadata.namespace in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the Rate Limiter. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the Rate Limiter is created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true administratively disables the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"limits": schema.ListNestedBlock{
				MarkdownDescription: "List of RateLimitValues that specifies the total number of allowed requests for each specified period.",
				Validators:          []validator.List{validators.RequiredListObjectAttributes("total_number")},

				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"burst_multiplier": schema.Int64Attribute{
							MarkdownDescription: "The maximum burst of requests to accommodate, expressed as a multiple of the rate.",
							Optional:            true,
							Validators: []validator.Int64{
								int64validator.Between(1, 100),
							},
						},
						"period_multiplier": schema.Int64Attribute{
							MarkdownDescription: "Setting, combined with Per Period units, provides a duration.",
							Optional:            true,
							Validators: []validator.Int64{
								int64validator.AtLeast(0),
							},
						},
						"total_number": schema.Int64Attribute{
							MarkdownDescription: "The total number of allowed requests per rate-limiting period.",
							Optional:            true,
							Validators: []validator.Int64{
								int64validator.Between(1, 8192),
							},
						},
						"unit": schema.StringAttribute{
							MarkdownDescription: "[Enum: SECOND|MINUTE|HOUR] Unit for the period per which the rate limit is applied. - SECOND: Second Rate limit period unit is seconds - MINUTE: Minute Rate limit period unit is minutes - HOUR: Hour Rate limit period unit is hours - DAY: Day Rate limit period unit is days. Possible values are `SECOND`, `MINUTE`, `HOUR`. Defaults to `SECOND`.",
							Optional:            true,
							Validators: []validator.String{
								stringvalidator.OneOf("SECOND", "MINUTE", "HOUR"),
							},
						},
					},
					Blocks: map[string]schema.Block{
						"action_block": schema.SingleNestedBlock{
							MarkdownDescription: "Action where a user is blocked from making further requests after exceeding rate limit threshold.",
							Attributes:          map[string]schema.Attribute{},
							Blocks: map[string]schema.Block{
								"hours": schema.SingleNestedBlock{
									MarkdownDescription: "Hours. Input Duration Hours.",
									Attributes: map[string]schema.Attribute{
										"duration": schema.Int64Attribute{
											MarkdownDescription: "Duration. Configuration parameter for duration",
											Optional:            true,
											Validators: []validator.Int64{
												int64validator.Between(1, 48),
											},
										},
									},
								},
								"minutes": schema.SingleNestedBlock{
									MarkdownDescription: "Minutes. Input Duration Minutes.",
									Attributes: map[string]schema.Attribute{
										"duration": schema.Int64Attribute{
											MarkdownDescription: "Duration. Configuration parameter for duration",
											Optional:            true,
											Validators: []validator.Int64{
												int64validator.Between(1, 60),
											},
										},
									},
								},
								"seconds": schema.SingleNestedBlock{
									MarkdownDescription: "Seconds. Input Duration Seconds.",
									Attributes: map[string]schema.Attribute{
										"duration": schema.Int64Attribute{
											MarkdownDescription: "Duration. Configuration parameter for duration",
											Optional:            true,
											Validators: []validator.Int64{
												int64validator.Between(1, 300),
											},
										},
									},
								},
							},
						},
						"disabled": schema.SingleNestedBlock{
							MarkdownDescription: "Enable this option",
						},
						"leaky_bucket": schema.SingleNestedBlock{
							MarkdownDescription: "Leaky-Bucket is the default rate limiter algorithm for F5.",
						},
						"token_bucket": schema.SingleNestedBlock{
							MarkdownDescription: "Token-Bucket is a rate limiter algorithm that is stricter with enforcing limits.",
						},
					},
				},
			},
			"user_identification": schema.ListNestedBlock{
				MarkdownDescription: "Reference to user_identification object. The rules in the user_identification object are evaluated to determine the user identifier to be rate limited. Defaults to `[]`. Server applies default when omitted.",

				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"kind": schema.StringAttribute{
							MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then kind will hold the referred object's kind (e.g. 'route').",
							Computed:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
							Optional:            true,
						},
						"namespace": schema.StringAttribute{
							MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
							Optional:            true,
							Computed:            true,
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
							Validators: []validator.String{
								stringvalidator.LengthBetween(1, 63),
								stringvalidator.RegexMatches(regexp.MustCompile(`^[a-z]([-a-z0-9]*[a-z0-9])?$`), ""),
							},
						},
						"tenant": schema.StringAttribute{
							MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
							Computed:            true,
						},
						"uid": schema.StringAttribute{
							MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then uid will hold the referred object's(e.g. Route's) uid.",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (r *RateLimiterResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *RateLimiterResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data RateLimiterResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *RateLimiterResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This permanently deletes the rate_limiter from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan RateLimiterResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *RateLimiterResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data RateLimiterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating rate_limiter", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.RateLimiter{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	// Capture which label keys the configuration declared, so Read can tell a label this
	// configuration owns from one the platform added (#1398). Create and Update are the
	// only places the configuration is visible; Read sees prior state, and prior state is
	// not evidence of ownership because providers up to 3.81.1 wrote the platform's own
	// labels into it.
	//
	// Captured here, written to private state only after the API call succeeds — see the
	// note at the write site.
	ownedLabelKeys, ownedLabelErr := encodeOwnedLabelKeys(configLabelKeys(createReq.Metadata.Labels))
	if ownedLabelErr != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Owned Label Keys",
			"Could not encode the configuration's label keys for private state: "+ownedLabelErr.Error()+
				"\n\nWithout this record the read-back cannot distinguish a label this "+
				"configuration owns from one the platform authored, and a label in the "+
				"ves.io/ namespace would never converge.",
		)
		return
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.Limits.IsNull() && !data.Limits.IsUnknown() {
		var LimitsElems []RateLimiterLimitsModel
		diags := data.Limits.ElementsAs(ctx, &LimitsElems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(LimitsElems) > 0 {
			var LimitsList []map[string]interface{}
			for _, LimitsItem := range LimitsElems {
				LimitsItemMap := make(map[string]interface{})
				if LimitsItem.ActionBlock != nil {
					LimitsActionBlockMap := make(map[string]interface{})
					if LimitsItem.ActionBlock.Hours != nil {
						LimitsActionBlockHoursMap := make(map[string]interface{})
						if !LimitsItem.ActionBlock.Hours.Duration.IsNull() && !LimitsItem.ActionBlock.Hours.Duration.IsUnknown() {
							LimitsActionBlockHoursMap["duration"] = LimitsItem.ActionBlock.Hours.Duration.ValueInt64()
						}
						LimitsActionBlockMap["hours"] = LimitsActionBlockHoursMap
					}
					if LimitsItem.ActionBlock.Minutes != nil {
						LimitsActionBlockMinutesMap := make(map[string]interface{})
						if !LimitsItem.ActionBlock.Minutes.Duration.IsNull() && !LimitsItem.ActionBlock.Minutes.Duration.IsUnknown() {
							LimitsActionBlockMinutesMap["duration"] = LimitsItem.ActionBlock.Minutes.Duration.ValueInt64()
						}
						LimitsActionBlockMap["minutes"] = LimitsActionBlockMinutesMap
					}
					if LimitsItem.ActionBlock.Seconds != nil {
						LimitsActionBlockSecondsMap := make(map[string]interface{})
						if !LimitsItem.ActionBlock.Seconds.Duration.IsNull() && !LimitsItem.ActionBlock.Seconds.Duration.IsUnknown() {
							LimitsActionBlockSecondsMap["duration"] = LimitsItem.ActionBlock.Seconds.Duration.ValueInt64()
						}
						LimitsActionBlockMap["seconds"] = LimitsActionBlockSecondsMap
					}
					LimitsItemMap["action_block"] = LimitsActionBlockMap
				}
				if !LimitsItem.BurstMultiplier.IsNull() && !LimitsItem.BurstMultiplier.IsUnknown() {
					LimitsItemMap["burst_multiplier"] = LimitsItem.BurstMultiplier.ValueInt64()
				}
				if LimitsItem.Disabled != nil {
					LimitsItemMap["disabled"] = map[string]interface{}{}
				}
				if LimitsItem.LeakyBucket != nil {
					LimitsItemMap["leaky_bucket"] = map[string]interface{}{}
				}
				if !LimitsItem.PeriodMultiplier.IsNull() && !LimitsItem.PeriodMultiplier.IsUnknown() {
					LimitsItemMap["period_multiplier"] = LimitsItem.PeriodMultiplier.ValueInt64()
				}
				if LimitsItem.TokenBucket != nil {
					LimitsItemMap["token_bucket"] = map[string]interface{}{}
				}
				if !LimitsItem.TotalNumber.IsNull() && !LimitsItem.TotalNumber.IsUnknown() {
					LimitsItemMap["total_number"] = LimitsItem.TotalNumber.ValueInt64()
				}
				if !LimitsItem.Unit.IsNull() && !LimitsItem.Unit.IsUnknown() {
					LimitsItemMap["unit"] = LimitsItem.Unit.ValueString()
				}
				LimitsList = append(LimitsList, LimitsItemMap)
			}
			createReq.Spec["limits"] = LimitsList
		}
	}
	if !data.UserIdentification.IsNull() && !data.UserIdentification.IsUnknown() {
		var UserIdentificationElems []RateLimiterUserIdentificationModel
		diags := data.UserIdentification.ElementsAs(ctx, &UserIdentificationElems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(UserIdentificationElems) > 0 {
			var UserIdentificationList []map[string]interface{}
			for _, UserIdentificationItem := range UserIdentificationElems {
				UserIdentificationItemMap := make(map[string]interface{})
				if !UserIdentificationItem.Name.IsNull() && !UserIdentificationItem.Name.IsUnknown() {
					UserIdentificationItemMap["name"] = UserIdentificationItem.Name.ValueString()
				}
				if !UserIdentificationItem.Namespace.IsNull() && !UserIdentificationItem.Namespace.IsUnknown() {
					UserIdentificationItemMap["namespace"] = UserIdentificationItem.Namespace.ValueString()
				}
				UserIdentificationList = append(UserIdentificationList, UserIdentificationItemMap)
			}
			createReq.Spec["user_identification"] = UserIdentificationList
		}
	}

	_, err := r.client.CreateRateLimiter(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create RateLimiter: %s", err))
		return
	}

	// The concurrency token is declared only on GET responses. Read back the object
	// after creation and record that exact server-assigned value for the next replace.
	apiResource, err := r.client.GetRateLimiter(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Concurrency Token After Create",
			fmt.Sprintf("The object was created, but its server-assigned concurrency token could not be read. Refresh the resource before updating it: %s", err),
		)
		return
	}
	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(apiResource.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Record Concurrency Token After Create", tokenErr.Error())
		return
	}

	// Only now that the write has landed. terraform-plugin-framework persists private
	// state even when the method returns an error (it copies createResp.Private into the
	// response before checking diagnostics), so recording ownership earlier would claim
	// keys the server never received.
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, ownedLabelKeysPrivateKey, ownedLabelKeys)...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if !isImport && (data.Limits.IsNull() || len(data.Limits.Elements()) == 0) {
		data.Limits = types.ListNull(types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes})
	} else if listData, ok := apiResource.Spec["limits"].([]interface{}); ok && len(listData) > 0 {
		var LimitsList []RateLimiterLimitsModel
		var existingLimitsItems []RateLimiterLimitsModel
		if !data.Limits.IsNull() && !data.Limits.IsUnknown() {
			data.Limits.ElementsAs(ctx, &existingLimitsItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				LimitsList = append(LimitsList, RateLimiterLimitsModel{
					ActionBlock: func() *RateLimiterLimitsActionBlockModel {
						if ActionBlockData, ok := itemMap["action_block"].(map[string]interface{}); ok {
							return &RateLimiterLimitsActionBlockModel{
								Hours: func() *RateLimiterLimitsActionBlockHoursModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Hours != nil {
										return existingLimitsItems[listIdx].ActionBlock.Hours
									}
									if HoursData, ok := ActionBlockData["hours"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockHoursModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Hours != nil && !existingLimitsItems[listIdx].ActionBlock.Hours.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Hours.Duration
												}
												if v, ok := HoursData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
								Minutes: func() *RateLimiterLimitsActionBlockMinutesModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Minutes != nil {
										return existingLimitsItems[listIdx].ActionBlock.Minutes
									}
									if MinutesData, ok := ActionBlockData["minutes"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockMinutesModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Minutes != nil && !existingLimitsItems[listIdx].ActionBlock.Minutes.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Minutes.Duration
												}
												if v, ok := MinutesData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
								Seconds: func() *RateLimiterLimitsActionBlockSecondsModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Seconds != nil {
										return existingLimitsItems[listIdx].ActionBlock.Seconds
									}
									if SecondsData, ok := ActionBlockData["seconds"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockSecondsModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Seconds != nil && !existingLimitsItems[listIdx].ActionBlock.Seconds.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Seconds.Duration
												}
												if v, ok := SecondsData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
							}
						}
						return nil
					}(),
					BurstMultiplier: func() types.Int64 {
						if v, ok := itemMap["burst_multiplier"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					Disabled: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].Disabled
						}
						if _, ok := itemMap["disabled"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					LeakyBucket: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].LeakyBucket
						}
						if _, ok := itemMap["leaky_bucket"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					PeriodMultiplier: func() types.Int64 {
						if v, ok := itemMap["period_multiplier"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					TokenBucket: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].TokenBucket
						}
						if _, ok := itemMap["token_bucket"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					TotalNumber: func() types.Int64 {
						if v, ok := itemMap["total_number"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					Unit: func() types.String {
						if v, ok := itemMap["unit"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes}, LimitsList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Limits = listVal
		}
	} else {
		data.Limits = types.ListNull(types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes})
	}
	if !isImport && (data.UserIdentification.IsNull() || len(data.UserIdentification.Elements()) == 0) {
		data.UserIdentification = types.ListNull(types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes})
	} else if listData, ok := apiResource.Spec["user_identification"].([]interface{}); ok && len(listData) > 0 {
		var UserIdentificationList []RateLimiterUserIdentificationModel
		var existingUserIdentificationItems []RateLimiterUserIdentificationModel
		if !data.UserIdentification.IsNull() && !data.UserIdentification.IsUnknown() {
			data.UserIdentification.ElementsAs(ctx, &existingUserIdentificationItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				UserIdentificationList = append(UserIdentificationList, RateLimiterUserIdentificationModel{
					Kind: func() types.String {
						if v, ok := itemMap["kind"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Name: func() types.String {
						if v, ok := itemMap["name"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Namespace: func() types.String {
						if v, ok := itemMap["namespace"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Tenant: func() types.String {
						if v, ok := itemMap["tenant"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Uid: func() types.String {
						if v, ok := itemMap["uid"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes}, UserIdentificationList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.UserIdentification = listVal
		}
	} else {
		data.UserIdentification = types.ListNull(types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes})
	}

	tflog.Trace(ctx, "created RateLimiter resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RateLimiterResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data RateLimiterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetRateLimiter(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "RateLimiter not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		// Some F5 XC APIs do not implement GET-by-name (read returns 501 Not
		// Implemented — e.g. the shape/csd domain objects, which support only
		// list/create/delete). Treat that as "cannot refresh" and preserve the
		// prior state rather than erroring, so the resource stays manageable and
		// idempotent (create/delete still work).
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "RateLimiter read not implemented by API (501); keeping prior state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read RateLimiter: %s", err))
		return
	}

	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(apiResource.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Refresh Concurrency Token", tokenErr.Error())
		return
	}
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// #1286: the API omits an empty metadata map entirely, so "no entries in the
	// response" is ambiguous — it means either "never declared" or "declared empty".
	// Nulling both makes a config that declares labels = {} drift (+ labels = {}) on
	// every plan after apply, with no import involved. Resolve it from the prior
	// value: a known-empty prior map stays an empty map, anything else (null = never
	// declared, or unknown) becomes null. A prior map WITH entries still nulls, so a
	// genuine out-of-band deletion is still reported as drift.
	// The MapValueMust below cannot panic: it panics only on diagnostics, and with nil
	// elements NewMapValue's sole error path (per-element type mismatch) is unreachable.
	priorLabelsEmpty := !data.Labels.IsNull() && !data.Labels.IsUnknown() && len(data.Labels.Elements()) == 0
	priorAnnotationsEmpty := !data.Annotations.IsNull() && !data.Annotations.IsUnknown() && len(data.Annotations.Elements()) == 0

	// Filter out the labels the platform authors itself, which Terraform must not
	// propose deleting just because the configuration does not mention them (#1391) —
	// except any key the configuration declared at the last Create or Update, recorded
	// in private state. Without that exemption a configuration cannot own a label in the
	// ves.io/ namespace at all: the write succeeds, the read-back strips it, and the next
	// plan proposes adding it again, forever (#1398). Prior state cannot serve as the
	// record, because providers up to 3.81.1 wrote the platform's own labels into it.
	ownedLabels := map[string]struct{}{}
	if rawOwned, ownedDiags := req.Private.GetKey(ctx, ownedLabelKeysPrivateKey); !ownedDiags.HasError() {
		ownedLabels = decodeOwnedLabelKeys(rawOwned)
	}
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabelsOwning(apiResource.Metadata.Labels, false, ownedLabels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else if priorLabelsEmpty {
			data.Labels = types.MapValueMust(types.StringType, nil)
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else if priorLabelsEmpty {
		data.Labels = types.MapValueMust(types.StringType, nil)
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else if priorAnnotationsEmpty {
		data.Annotations = types.MapValueMust(types.StringType, nil)
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if !isImport && (data.Limits.IsNull() || len(data.Limits.Elements()) == 0) {
		data.Limits = types.ListNull(types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes})
	} else if listData, ok := apiResource.Spec["limits"].([]interface{}); ok && len(listData) > 0 {
		var LimitsList []RateLimiterLimitsModel
		var existingLimitsItems []RateLimiterLimitsModel
		if !data.Limits.IsNull() && !data.Limits.IsUnknown() {
			data.Limits.ElementsAs(ctx, &existingLimitsItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				LimitsList = append(LimitsList, RateLimiterLimitsModel{
					ActionBlock: func() *RateLimiterLimitsActionBlockModel {
						if ActionBlockData, ok := itemMap["action_block"].(map[string]interface{}); ok {
							return &RateLimiterLimitsActionBlockModel{
								Hours: func() *RateLimiterLimitsActionBlockHoursModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Hours != nil {
										return existingLimitsItems[listIdx].ActionBlock.Hours
									}
									if HoursData, ok := ActionBlockData["hours"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockHoursModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Hours != nil && !existingLimitsItems[listIdx].ActionBlock.Hours.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Hours.Duration
												}
												if v, ok := HoursData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
								Minutes: func() *RateLimiterLimitsActionBlockMinutesModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Minutes != nil {
										return existingLimitsItems[listIdx].ActionBlock.Minutes
									}
									if MinutesData, ok := ActionBlockData["minutes"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockMinutesModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Minutes != nil && !existingLimitsItems[listIdx].ActionBlock.Minutes.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Minutes.Duration
												}
												if v, ok := MinutesData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
								Seconds: func() *RateLimiterLimitsActionBlockSecondsModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Seconds != nil {
										return existingLimitsItems[listIdx].ActionBlock.Seconds
									}
									if SecondsData, ok := ActionBlockData["seconds"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockSecondsModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Seconds != nil && !existingLimitsItems[listIdx].ActionBlock.Seconds.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Seconds.Duration
												}
												if v, ok := SecondsData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
							}
						}
						return nil
					}(),
					BurstMultiplier: func() types.Int64 {
						if v, ok := itemMap["burst_multiplier"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					Disabled: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].Disabled
						}
						if _, ok := itemMap["disabled"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					LeakyBucket: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].LeakyBucket
						}
						if _, ok := itemMap["leaky_bucket"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					PeriodMultiplier: func() types.Int64 {
						if v, ok := itemMap["period_multiplier"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					TokenBucket: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].TokenBucket
						}
						if _, ok := itemMap["token_bucket"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					TotalNumber: func() types.Int64 {
						if v, ok := itemMap["total_number"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					Unit: func() types.String {
						if v, ok := itemMap["unit"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes}, LimitsList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Limits = listVal
		}
	} else {
		data.Limits = types.ListNull(types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes})
	}
	if !isImport && (data.UserIdentification.IsNull() || len(data.UserIdentification.Elements()) == 0) {
		data.UserIdentification = types.ListNull(types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes})
	} else if listData, ok := apiResource.Spec["user_identification"].([]interface{}); ok && len(listData) > 0 {
		var UserIdentificationList []RateLimiterUserIdentificationModel
		var existingUserIdentificationItems []RateLimiterUserIdentificationModel
		if !data.UserIdentification.IsNull() && !data.UserIdentification.IsUnknown() {
			data.UserIdentification.ElementsAs(ctx, &existingUserIdentificationItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				UserIdentificationList = append(UserIdentificationList, RateLimiterUserIdentificationModel{
					Kind: func() types.String {
						if v, ok := itemMap["kind"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Name: func() types.String {
						if v, ok := itemMap["name"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Namespace: func() types.String {
						if v, ok := itemMap["namespace"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Tenant: func() types.String {
						if v, ok := itemMap["tenant"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Uid: func() types.String {
						if v, ok := itemMap["uid"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes}, UserIdentificationList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.UserIdentification = listVal
		}
	} else {
		data.UserIdentification = types.ListNull(types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes})
	}

	// The import marker is a one-shot signal for the import Read only. Clear it so every
	// subsequent refresh runs as a normal Read with drift-preservation; otherwise the
	// resource stays in "import mode" forever and re-reads server-managed fields the user
	// never configured, producing perpetual plan drift.
	if isImport {
		resp.Diagnostics.Append(resp.Private.SetKey(ctx, "isImport", nil)...)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RateLimiterResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data RateLimiterResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	rawConcurrencyToken, tokenDiags := req.Private.GetKey(ctx, concurrencyTokenPrivateKey)
	resp.Diagnostics.Append(tokenDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	concurrencyToken, tokenErr := decodeConcurrencyToken(rawConcurrencyToken)
	if tokenErr != nil {
		resp.Diagnostics.AddError(
			"Refresh Required Before Update",
			"The update was not sent because this resource has no usable concurrency token from its last read. Run terraform refresh (or terraform plan with refresh enabled), review the refreshed configuration, and apply again. The provider will not fetch and silently adopt a newer token during a write. Details: "+tokenErr.Error(),
		)
		return
	}

	apiResource := &client.RateLimiter{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}
	apiResource.ResourceVersion = concurrencyToken

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	// Re-capture ownership on every update, because the configuration's label set can
	// change: a key added here becomes owned, and a key removed stops being owned so the
	// next Read filters it again if it lives in a platform namespace (#1398).
	//
	// Captured HERE, before the platform's own discovery labels are merged in below —
	// merging first would record those as configuration-owned and reintroduce exactly the
	// #1391 bug this pairs with. Written to private state only after the API call
	// succeeds; see the note at the write site.
	ownedLabelKeys, ownedLabelErr := encodeOwnedLabelKeys(configLabelKeys(apiResource.Metadata.Labels))
	if ownedLabelErr != nil {
		resp.Diagnostics.AddError(
			"Unable to Record Owned Label Keys",
			"Could not encode the configuration's label keys for private state: "+ownedLabelErr.Error()+
				"\n\nWithout this record the read-back cannot distinguish a label this "+
				"configuration owns from one the platform authored, and a label in the "+
				"ves.io/ namespace would never converge.",
		)
		return
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.Limits.IsNull() && !data.Limits.IsUnknown() {
		var LimitsElems []RateLimiterLimitsModel
		diags := data.Limits.ElementsAs(ctx, &LimitsElems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(LimitsElems) > 0 {
			var LimitsList []map[string]interface{}
			for _, LimitsItem := range LimitsElems {
				LimitsItemMap := make(map[string]interface{})
				if LimitsItem.ActionBlock != nil {
					LimitsActionBlockMap := make(map[string]interface{})
					if LimitsItem.ActionBlock.Hours != nil {
						LimitsActionBlockHoursMap := make(map[string]interface{})
						if !LimitsItem.ActionBlock.Hours.Duration.IsNull() && !LimitsItem.ActionBlock.Hours.Duration.IsUnknown() {
							LimitsActionBlockHoursMap["duration"] = LimitsItem.ActionBlock.Hours.Duration.ValueInt64()
						}
						LimitsActionBlockMap["hours"] = LimitsActionBlockHoursMap
					}
					if LimitsItem.ActionBlock.Minutes != nil {
						LimitsActionBlockMinutesMap := make(map[string]interface{})
						if !LimitsItem.ActionBlock.Minutes.Duration.IsNull() && !LimitsItem.ActionBlock.Minutes.Duration.IsUnknown() {
							LimitsActionBlockMinutesMap["duration"] = LimitsItem.ActionBlock.Minutes.Duration.ValueInt64()
						}
						LimitsActionBlockMap["minutes"] = LimitsActionBlockMinutesMap
					}
					if LimitsItem.ActionBlock.Seconds != nil {
						LimitsActionBlockSecondsMap := make(map[string]interface{})
						if !LimitsItem.ActionBlock.Seconds.Duration.IsNull() && !LimitsItem.ActionBlock.Seconds.Duration.IsUnknown() {
							LimitsActionBlockSecondsMap["duration"] = LimitsItem.ActionBlock.Seconds.Duration.ValueInt64()
						}
						LimitsActionBlockMap["seconds"] = LimitsActionBlockSecondsMap
					}
					LimitsItemMap["action_block"] = LimitsActionBlockMap
				}
				if !LimitsItem.BurstMultiplier.IsNull() && !LimitsItem.BurstMultiplier.IsUnknown() {
					LimitsItemMap["burst_multiplier"] = LimitsItem.BurstMultiplier.ValueInt64()
				}
				if LimitsItem.Disabled != nil {
					LimitsItemMap["disabled"] = map[string]interface{}{}
				}
				if LimitsItem.LeakyBucket != nil {
					LimitsItemMap["leaky_bucket"] = map[string]interface{}{}
				}
				if !LimitsItem.PeriodMultiplier.IsNull() && !LimitsItem.PeriodMultiplier.IsUnknown() {
					LimitsItemMap["period_multiplier"] = LimitsItem.PeriodMultiplier.ValueInt64()
				}
				if LimitsItem.TokenBucket != nil {
					LimitsItemMap["token_bucket"] = map[string]interface{}{}
				}
				if !LimitsItem.TotalNumber.IsNull() && !LimitsItem.TotalNumber.IsUnknown() {
					LimitsItemMap["total_number"] = LimitsItem.TotalNumber.ValueInt64()
				}
				if !LimitsItem.Unit.IsNull() && !LimitsItem.Unit.IsUnknown() {
					LimitsItemMap["unit"] = LimitsItem.Unit.ValueString()
				}
				LimitsList = append(LimitsList, LimitsItemMap)
			}
			apiResource.Spec["limits"] = LimitsList
		}
	}
	if !data.UserIdentification.IsNull() && !data.UserIdentification.IsUnknown() {
		var UserIdentificationElems []RateLimiterUserIdentificationModel
		diags := data.UserIdentification.ElementsAs(ctx, &UserIdentificationElems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(UserIdentificationElems) > 0 {
			var UserIdentificationList []map[string]interface{}
			for _, UserIdentificationItem := range UserIdentificationElems {
				UserIdentificationItemMap := make(map[string]interface{})
				if !UserIdentificationItem.Name.IsNull() && !UserIdentificationItem.Name.IsUnknown() {
					UserIdentificationItemMap["name"] = UserIdentificationItem.Name.ValueString()
				}
				if !UserIdentificationItem.Namespace.IsNull() && !UserIdentificationItem.Namespace.IsUnknown() {
					UserIdentificationItemMap["namespace"] = UserIdentificationItem.Namespace.ValueString()
				}
				UserIdentificationList = append(UserIdentificationList, UserIdentificationItemMap)
			}
			apiResource.Spec["user_identification"] = UserIdentificationList
		}
	}

	_, err := r.client.UpdateRateLimiter(ctx, apiResource)
	if err != nil {
		var apiErr *xcsherrors.XCSHError
		if errors.As(err, &apiErr) && apiErr.Code == xcsherrors.ErrCodeConflict {
			resp.Diagnostics.AddError(
				"Stale Configuration",
				fmt.Sprintf("F5 XC rejected the update of rate_limiter %q in namespace %q because the object changed after Terraform last refreshed it. The provider sent one replace request using the exact token stored with the reviewed state and did not retry or change private state. Refresh, review the remote changes, and apply again.", data.Name.ValueString(), data.Namespace.ValueString()),
			)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update RateLimiter: %s", err))
		return
	}

	// Only now that the write has landed. terraform-plugin-framework persists private
	// state even when the method returns an error (it copies updateResp.Private into the
	// response before checking diagnostics), so recording ownership earlier would be
	// worse than not recording it: dropping a ves.io/ label from the configuration and
	// then failing the update would leave private state claiming the key is unowned while
	// the server still holds it, and Read would filter it out of sight for good.
	//
	// This is not airtight, and cannot be: Client.Put returns json.Unmarshal's error
	// after a 2xx, so an error does not strictly prove the write was rejected. What it
	// does guarantee is the direction of the residual. If the write landed and we return
	// early, ownership stays as it was — an added label keeps being planned, which is
	// visible and self-corrects on the next successful apply. The opposite ordering loses
	// a label silently and permanently. Fail loud rather than fail quiet.

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetRateLimiter(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read RateLimiter after update: %s", fetchErr))
		return
	}

	// Commit both private-state updates only after PUT and readback succeeded. A 409
	// or failed readback therefore leaves the prior token and label ownership intact.
	concurrencyTokenPrivate, tokenErr := encodeConcurrencyToken(fetched.ResourceVersion)
	if tokenErr != nil {
		resp.Diagnostics.AddError("Unable to Record Updated Concurrency Token", tokenErr.Error())
		return
	}
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, concurrencyTokenPrivateKey, concurrencyTokenPrivate)...)
	resp.Diagnostics.Append(resp.Private.SetKey(ctx, ownedLabelKeysPrivateKey, ownedLabelKeys)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Set computed fields from API response

	// Unmarshal fields from the complete GET response into Terraform state.
	apiResource = fetched
	isImport := false // Update is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if !isImport && (data.Limits.IsNull() || len(data.Limits.Elements()) == 0) {
		data.Limits = types.ListNull(types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes})
	} else if listData, ok := apiResource.Spec["limits"].([]interface{}); ok && len(listData) > 0 {
		var LimitsList []RateLimiterLimitsModel
		var existingLimitsItems []RateLimiterLimitsModel
		if !data.Limits.IsNull() && !data.Limits.IsUnknown() {
			data.Limits.ElementsAs(ctx, &existingLimitsItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				LimitsList = append(LimitsList, RateLimiterLimitsModel{
					ActionBlock: func() *RateLimiterLimitsActionBlockModel {
						if ActionBlockData, ok := itemMap["action_block"].(map[string]interface{}); ok {
							return &RateLimiterLimitsActionBlockModel{
								Hours: func() *RateLimiterLimitsActionBlockHoursModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Hours != nil {
										return existingLimitsItems[listIdx].ActionBlock.Hours
									}
									if HoursData, ok := ActionBlockData["hours"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockHoursModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Hours != nil && !existingLimitsItems[listIdx].ActionBlock.Hours.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Hours.Duration
												}
												if v, ok := HoursData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
								Minutes: func() *RateLimiterLimitsActionBlockMinutesModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Minutes != nil {
										return existingLimitsItems[listIdx].ActionBlock.Minutes
									}
									if MinutesData, ok := ActionBlockData["minutes"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockMinutesModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Minutes != nil && !existingLimitsItems[listIdx].ActionBlock.Minutes.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Minutes.Duration
												}
												if v, ok := MinutesData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
								Seconds: func() *RateLimiterLimitsActionBlockSecondsModel {
									if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Seconds != nil {
										return existingLimitsItems[listIdx].ActionBlock.Seconds
									}
									if SecondsData, ok := ActionBlockData["seconds"].(map[string]interface{}); ok {
										return &RateLimiterLimitsActionBlockSecondsModel{
											Duration: func() types.Int64 {
												if !isImport && len(existingLimitsItems) > listIdx && existingLimitsItems[listIdx].ActionBlock != nil && existingLimitsItems[listIdx].ActionBlock.Seconds != nil && !existingLimitsItems[listIdx].ActionBlock.Seconds.Duration.IsUnknown() {
													return existingLimitsItems[listIdx].ActionBlock.Seconds.Duration
												}
												if v, ok := SecondsData["duration"].(float64); ok && v != 0 {
													return types.Int64Value(int64(v))
												}
												return types.Int64Null()
											}(),
										}
									}
									return nil
								}(),
							}
						}
						return nil
					}(),
					BurstMultiplier: func() types.Int64 {
						if v, ok := itemMap["burst_multiplier"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					Disabled: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].Disabled
						}
						if _, ok := itemMap["disabled"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					LeakyBucket: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].LeakyBucket
						}
						if _, ok := itemMap["leaky_bucket"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					PeriodMultiplier: func() types.Int64 {
						if v, ok := itemMap["period_multiplier"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					TokenBucket: func() *RateLimiterEmptyModel {
						if !isImport && len(existingLimitsItems) > listIdx {
							return existingLimitsItems[listIdx].TokenBucket
						}
						if _, ok := itemMap["token_bucket"].(map[string]interface{}); ok {
							return &RateLimiterEmptyModel{}
						}
						return nil
					}(),
					TotalNumber: func() types.Int64 {
						if v, ok := itemMap["total_number"].(float64); ok && v != 0 {
							return types.Int64Value(int64(v))
						}
						return types.Int64Null()
					}(),
					Unit: func() types.String {
						if v, ok := itemMap["unit"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes}, LimitsList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Limits = listVal
		}
	} else {
		data.Limits = types.ListNull(types.ObjectType{AttrTypes: RateLimiterLimitsModelAttrTypes})
	}
	if !isImport && (data.UserIdentification.IsNull() || len(data.UserIdentification.Elements()) == 0) {
		data.UserIdentification = types.ListNull(types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes})
	} else if listData, ok := apiResource.Spec["user_identification"].([]interface{}); ok && len(listData) > 0 {
		var UserIdentificationList []RateLimiterUserIdentificationModel
		var existingUserIdentificationItems []RateLimiterUserIdentificationModel
		if !data.UserIdentification.IsNull() && !data.UserIdentification.IsUnknown() {
			data.UserIdentification.ElementsAs(ctx, &existingUserIdentificationItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx
			if itemMap, ok := item.(map[string]interface{}); ok {
				UserIdentificationList = append(UserIdentificationList, RateLimiterUserIdentificationModel{
					Kind: func() types.String {
						if v, ok := itemMap["kind"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Name: func() types.String {
						if v, ok := itemMap["name"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Namespace: func() types.String {
						if v, ok := itemMap["namespace"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Tenant: func() types.String {
						if v, ok := itemMap["tenant"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
					Uid: func() types.String {
						if v, ok := itemMap["uid"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes}, UserIdentificationList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.UserIdentification = listVal
		}
	} else {
		data.UserIdentification = types.ListNull(types.ObjectType{AttrTypes: RateLimiterUserIdentificationModelAttrTypes})
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RateLimiterResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data RateLimiterResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

	// Delete with bounded retry on transient referential BAD_REQUEST: during teardown a
	// resource can briefly still be referenced by another object (a healthcheck by an origin
	// pool, an origin pool by a load balancer, etc.), which the API rejects with 400 until
	// the referrer is gone. NOT_FOUND/404 (already deleted) and 501 (delete unsupported) are
	// terminal and handled after the loop.
	var err error
	for attempt := 0; ; attempt++ {
		err = r.client.DeleteRateLimiter(ctx, data.Namespace.ValueString(), data.Name.ValueString())
		if err == nil {
			break
		}
		msg := err.Error()
		transient := (strings.Contains(msg, "400") || strings.Contains(msg, "BAD_REQUEST")) &&
			!strings.Contains(msg, "NOT_FOUND") && !strings.Contains(msg, "404") && !strings.Contains(msg, "501")
		if !transient || attempt >= 5 {
			break
		}
		tflog.Warn(ctx, "RateLimiter delete hit transient BAD_REQUEST (likely still referenced); retrying", map[string]interface{}{
			"name":      data.Name.ValueString(),
			"namespace": data.Namespace.ValueString(),
			"attempt":   attempt + 1,
		})
		select {
		case <-ctx.Done():
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Timed out retrying delete of RateLimiter (still referenced): %s", err))
			return
		case <-time.After(5 * time.Second):
		}
	}
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "RateLimiter already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "RateLimiter delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete RateLimiter: %s", err))
		return
	}
}

func (r *RateLimiterResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
