// Code generated from api-specs-enriched v7.0.9 smsv2-contract.json. DO NOT EDIT.

package provider

const (
	smsv2ContractID        = "f5xc-smsv2-api/v1"
	smsv2ContractVersion   = "7.0.0"
	smsv2APIReleaseTag     = "v7.0.9"
	smsv2SourceCommit      = "1c4f4eb8dd6cd9c440c241b995a6c0ef1bcd23ab"
	smsv2TelemetrySchemaID = "f5xc-smsv2-aws-tgw-telemetry/v2"
)

var smsv2ContractCapabilities = map[string]string{"aws_ce_create": "available", "aws_node_configuration": "available", "runtime_status": "available", "site_upgrade": "available", "tgw_connect": "available"}
var smsv2AWSNodeConfigurationJSON = "{\"availability\":\"evidence_backed\",\"enforcement\":\"required\",\"field_paths\":[\"resource_version\",\"spec.aws.not_managed.node_list[]\",\"spec.aws.not_managed.node_list[].hostname\",\"spec.aws.not_managed.node_list[].interface_list[]\",\"spec.aws.not_managed.node_list[].interface_list[].ethernet_interface.device\",\"spec.aws.not_managed.node_list[].interface_list[].ethernet_interface.mac\"],\"invariants\":{\"device_source\":\"observed_registration_only\",\"ha\":\"disabled\",\"interface_count\":2,\"interface_role_cardinality\":\"exactly_one_each\",\"interface_roles\":[\"slo\",\"sli\"],\"mac_normalization\":\"ieee802_lowercase_colon\",\"node_count\":1},\"mapping\":{\"cardinality\":\"one_to_one\",\"device_policy\":\"observed_only\",\"device_value_path\":\"interfaces[].device\",\"join_key\":\"normalized_mac\",\"mac_value_path\":\"interfaces[].mac\",\"registration_source\":\"site_registration_hardware_inventory\",\"terraform_mac_source\":\"aws_network_interface.mac_address\"},\"operation\":{\"method\":\"PUT\",\"operation_id\":\"ves.io.schema.views.securemesh_site_v2.API.Replace\",\"path\":\"/api/config/namespaces/{metadata.namespace}/securemesh_site_v2s/{metadata.name}\",\"request_schema\":\"securemesh_site_v2ReplaceRequest\"},\"provenance\":{\"evidence_receipt_sha256\":\"a5e423f8223bce56b83b74d0c546072984240761d392f15b664920e9fbfeec29\",\"issue\":\"f5-sales-demo/api-specs-enriched#1776\",\"probe_date\":\"2026-09-17\",\"source_commit\":\"3be0310daf3658bc90383048cc18ab6447d18e35\",\"source_spec_sha256\":\"c6145b7096d7b08416732c8ebbd80e83be1902f73096ba08309e360d9a746eec\"},\"strategy\":\"discovery_rebuild\",\"unsupported_reasons\":{\"ambiguous_mapping\":\"aws_node_configuration_mapping_ambiguous\",\"direct_rebuild_mode_transition\":\"aws_node_configuration_discovery_rebuild_requires_distinct_site\",\"guessed_device\":\"aws_node_configuration_device_must_be_observed\",\"incomplete_request_semantics\":\"aws_node_configuration_request_semantics_incomplete\",\"malformed_mac\":\"aws_node_configuration_mac_malformed\",\"missing_mapping\":\"aws_node_configuration_mapping_missing\",\"multi_node_or_ha_input\":\"aws_node_configuration_requires_single_non_ha_node\"}}"
var smsv2KVMImageResolutionJSON = "{\"availability\":\"evidence_backed\",\"configuration_get\":{\"method\":\"GET\",\"operation_id\":\"ves.io.schema.views.securemesh_site_v2.API.Get\",\"path\":\"/api/config/namespaces/system/securemesh_site_v2s/{site_name}\"},\"configuration_list\":{\"method\":\"GET\",\"operation_id\":\"ves.io.schema.views.securemesh_site_v2.API.List\",\"path\":\"/api/config/namespaces/system/securemesh_site_v2s\"},\"enforcement\":\"required\",\"identity\":{\"configuration_matches\":1,\"configuration_name\":\"items[].name\",\"configuration_uid\":\"items[].uid\",\"owner_kind\":\"items[].owner_view.kind\",\"owner_matches\":1,\"owner_uid\":\"items[].owner_view.uid\",\"request_uid\":\"site_uid\",\"required_owner_kind\":\"securemesh_site_v2\",\"site_uid\":\"items[].uid\"},\"namespace\":\"system\",\"provenance\":{\"receipt_path\":\"config/evidence/kvm-site-image-resolution-20260919.json\",\"receipt_sha256\":\"fa4ed98befc906a3522cf37c13502931e976e36064217e9d45430de7e3104c34\",\"source_commit\":\"5c33dcf51eb8bee24e2ca1856e32cb5fef2a286f\",\"source_issue\":\"f5-sales-demo/api-specs-enriched#1805\",\"upstream_spec_sha256\":\"b36cd80bf6394741bdc8ba88ef175251129ae12be8b8f2d6eed2676227f704ef\"},\"query\":{\"method\":\"POST\",\"operation_id\":\"ves.io.schema.virtual_appliance.SoftwareVersionOsImageCustomApi.GetImage\",\"path\":\"/api/maurice/software_os_version\",\"request_cardinality\":1,\"request_field\":\"uids\",\"request_schema\":\"virtual_applianceGetImageRequest\",\"response_schema\":\"virtual_applianceGetImageResponse\",\"side_effects\":\"none\"},\"replaces_operation\":\"ves.io.schema.registration.CustomAPI.GetImageDownloadUrl\",\"response\":{\"download_url\":\"download_image_link\",\"error\":\"error_description\",\"image_name\":\"copy_image_name\",\"mapping\":\"images\",\"mapping_key\":\"site_uid\",\"md5\":\"image_md5_sum\"},\"site_list\":{\"method\":\"GET\",\"operation_id\":\"ves.io.schema.site.API.List\",\"path\":\"/api/config/namespaces/system/sites\"},\"strategy\":\"site_uid_os_image\",\"terraform_data_source\":\"site_image\",\"validation\":{\"boot_acceptance_required\":true,\"caller_supplied_uid\":false,\"download_hosts\":[\"downloads.volterra.io\"],\"download_scheme\":\"https\",\"md5_pattern\":\"^[0-9a-fA-F]{32}$\",\"reject_nonempty_error\":true,\"require_complete_image_fields\":true,\"require_current_owner_mapping\":true,\"required_platform_field\":\"spec.kvm\",\"static_fallback\":false,\"verify_artifact_checksum\":true}}"
var smsv2ContractF5XCAuthorities = []string{"smsv2_configuration", "runtime_health", "bgp_peers", "bgp_routes", "simplified_routes", "site_upgrade_observation"}
var smsv2ContractAWSAuthorities = []string{"eni", "transit_gateway", "transit_gateway_connect", "gre_endpoints", "bgp_inside_cidrs", "autonomous_system_numbers"}
var smsv2AzureRouteServerEBGPMultihop = smsv2CapabilityBoundaryContract{
	Availability: "unavailable",
	Enforcement:  "reject_before_mutation",
	Reason:       "no_schema_valid_ebgp_multihop_request_control",
	Source: smsv2CapabilitySourceContract{
		Repository:  "f5-sales-demo/api-specs-enriched",
		Commit:      "322c202ed49c8cfcd5015a524f3195bbd2a8f2bc",
		AssetPath:   "docs/specifications/api/network.json",
		AssetSHA256: "sha256:a7398d85475409c93750a04ccdec7c0b1a7ae12bc362ebfbc76866275904762a",
		SchemaPaths: []string{"components.schemas.bgpPeer", "components.schemas.bgpPeerExternal", "components.schemas.bgpBgpParameters"},
	},
}
