// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/client"
	inttimeouts "github.com/f5-sales-demo/terraform-provider-xcsh/internal/timeouts"
	"github.com/f5-sales-demo/terraform-provider-xcsh/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &TunnelResource{}
	_ resource.ResourceWithConfigure      = &TunnelResource{}
	_ resource.ResourceWithImportState    = &TunnelResource{}
	_ resource.ResourceWithModifyPlan     = &TunnelResource{}
	_ resource.ResourceWithValidateConfig = &TunnelResource{}
)

func NewTunnelResource() resource.Resource {
	return &TunnelResource{}
}

type TunnelResource struct {
	client *client.Client
}

// TunnelEmptyModel represents empty nested blocks
type TunnelEmptyModel struct {
}

// TunnelLocalIPModel represents local_ip block
type TunnelLocalIPModel struct {
	Intf      *TunnelLocalIPIntfModel      `tfsdk:"intf"`
	IPAddress *TunnelLocalIPIPAddressModel `tfsdk:"ip_address"`
}

// TunnelLocalIPModelAttrTypes defines the attribute types for TunnelLocalIPModel
var TunnelLocalIPModelAttrTypes = map[string]attr.Type{
	"intf":       types.ObjectType{AttrTypes: TunnelLocalIPIntfModelAttrTypes},
	"ip_address": types.ObjectType{AttrTypes: TunnelLocalIPIPAddressModelAttrTypes},
}

// TunnelLocalIPIntfModel represents intf block
type TunnelLocalIPIntfModel struct {
	LocalIntf types.List `tfsdk:"local_intf"`
}

// TunnelLocalIPIntfModelAttrTypes defines the attribute types for TunnelLocalIPIntfModel
var TunnelLocalIPIntfModelAttrTypes = map[string]attr.Type{
	"local_intf": types.ListType{ElemType: types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes}},
}

// TunnelLocalIPIntfLocalIntfModel represents local_intf block
type TunnelLocalIPIntfLocalIntfModel struct {
	Kind      types.String `tfsdk:"kind"`
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
	Uid       types.String `tfsdk:"uid"`
}

// TunnelLocalIPIntfLocalIntfModelAttrTypes defines the attribute types for TunnelLocalIPIntfLocalIntfModel
var TunnelLocalIPIntfLocalIntfModelAttrTypes = map[string]attr.Type{
	"kind":      types.StringType,
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
	"uid":       types.StringType,
}

// TunnelLocalIPIPAddressModel represents ip_address block
type TunnelLocalIPIPAddressModel struct {
	Auto               *TunnelEmptyModel                              `tfsdk:"auto"`
	IPAddress          *TunnelLocalIPIPAddressIPAddressModel          `tfsdk:"ip_address"`
	VirtualNetworkType *TunnelLocalIPIPAddressVirtualNetworkTypeModel `tfsdk:"virtual_network_type"`
}

// TunnelLocalIPIPAddressModelAttrTypes defines the attribute types for TunnelLocalIPIPAddressModel
var TunnelLocalIPIPAddressModelAttrTypes = map[string]attr.Type{
	"auto":                 types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"ip_address":           types.ObjectType{AttrTypes: TunnelLocalIPIPAddressIPAddressModelAttrTypes},
	"virtual_network_type": types.ObjectType{AttrTypes: TunnelLocalIPIPAddressVirtualNetworkTypeModelAttrTypes},
}

// TunnelLocalIPIPAddressIPAddressModel represents ip_address block
type TunnelLocalIPIPAddressIPAddressModel struct {
	Ipv4 *TunnelLocalIPIPAddressIPAddressIpv4Model `tfsdk:"ipv4"`
	Ipv6 *TunnelLocalIPIPAddressIPAddressIpv6Model `tfsdk:"ipv6"`
}

// TunnelLocalIPIPAddressIPAddressModelAttrTypes defines the attribute types for TunnelLocalIPIPAddressIPAddressModel
var TunnelLocalIPIPAddressIPAddressModelAttrTypes = map[string]attr.Type{
	"ipv4": types.ObjectType{AttrTypes: TunnelLocalIPIPAddressIPAddressIpv4ModelAttrTypes},
	"ipv6": types.ObjectType{AttrTypes: TunnelLocalIPIPAddressIPAddressIpv6ModelAttrTypes},
}

// TunnelLocalIPIPAddressIPAddressIpv4Model represents ipv4 block
type TunnelLocalIPIPAddressIPAddressIpv4Model struct {
	Addr types.String `tfsdk:"addr"`
}

// TunnelLocalIPIPAddressIPAddressIpv4ModelAttrTypes defines the attribute types for TunnelLocalIPIPAddressIPAddressIpv4Model
var TunnelLocalIPIPAddressIPAddressIpv4ModelAttrTypes = map[string]attr.Type{
	"addr": types.StringType,
}

// TunnelLocalIPIPAddressIPAddressIpv6Model represents ipv6 block
type TunnelLocalIPIPAddressIPAddressIpv6Model struct {
	Addr types.String `tfsdk:"addr"`
}

// TunnelLocalIPIPAddressIPAddressIpv6ModelAttrTypes defines the attribute types for TunnelLocalIPIPAddressIPAddressIpv6Model
var TunnelLocalIPIPAddressIPAddressIpv6ModelAttrTypes = map[string]attr.Type{
	"addr": types.StringType,
}

// TunnelLocalIPIPAddressVirtualNetworkTypeModel represents virtual_network_type block
type TunnelLocalIPIPAddressVirtualNetworkTypeModel struct {
	Public          *TunnelEmptyModel `tfsdk:"public"`
	SiteLocal       *TunnelEmptyModel `tfsdk:"site_local"`
	SiteLocalInside *TunnelEmptyModel `tfsdk:"site_local_inside"`
}

// TunnelLocalIPIPAddressVirtualNetworkTypeModelAttrTypes defines the attribute types for TunnelLocalIPIPAddressVirtualNetworkTypeModel
var TunnelLocalIPIPAddressVirtualNetworkTypeModelAttrTypes = map[string]attr.Type{
	"public":            types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"site_local":        types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"site_local_inside": types.ObjectType{AttrTypes: map[string]attr.Type{}},
}

// TunnelParamsModel represents params block
type TunnelParamsModel struct {
	Ipsec *TunnelParamsIpsecModel `tfsdk:"ipsec"`
}

// TunnelParamsModelAttrTypes defines the attribute types for TunnelParamsModel
var TunnelParamsModelAttrTypes = map[string]attr.Type{
	"ipsec": types.ObjectType{AttrTypes: TunnelParamsIpsecModelAttrTypes},
}

// TunnelParamsIpsecModel represents ipsec block
type TunnelParamsIpsecModel struct {
	IpsecPsk *TunnelParamsIpsecIpsecPskModel `tfsdk:"ipsec_psk"`
}

// TunnelParamsIpsecModelAttrTypes defines the attribute types for TunnelParamsIpsecModel
var TunnelParamsIpsecModelAttrTypes = map[string]attr.Type{
	"ipsec_psk": types.ObjectType{AttrTypes: TunnelParamsIpsecIpsecPskModelAttrTypes},
}

// TunnelParamsIpsecIpsecPskModel represents ipsec_psk block
type TunnelParamsIpsecIpsecPskModel struct {
	BlindfoldSecretInfo *TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel `tfsdk:"blindfold_secret_info"`
	ClearSecretInfo     *TunnelParamsIpsecIpsecPskClearSecretInfoModel     `tfsdk:"clear_secret_info"`
}

// TunnelParamsIpsecIpsecPskModelAttrTypes defines the attribute types for TunnelParamsIpsecIpsecPskModel
var TunnelParamsIpsecIpsecPskModelAttrTypes = map[string]attr.Type{
	"blindfold_secret_info": types.ObjectType{AttrTypes: TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModelAttrTypes},
	"clear_secret_info":     types.ObjectType{AttrTypes: TunnelParamsIpsecIpsecPskClearSecretInfoModelAttrTypes},
}

// TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel represents blindfold_secret_info block
type TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel struct {
	DecryptionProvider types.String `tfsdk:"decryption_provider"`
	Location           types.String `tfsdk:"location"`
	StoreProvider      types.String `tfsdk:"store_provider"`
}

// TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModelAttrTypes defines the attribute types for TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel
var TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModelAttrTypes = map[string]attr.Type{
	"decryption_provider": types.StringType,
	"location":            types.StringType,
	"store_provider":      types.StringType,
}

// TunnelParamsIpsecIpsecPskClearSecretInfoModel represents clear_secret_info block
type TunnelParamsIpsecIpsecPskClearSecretInfoModel struct {
	Provider types.String `tfsdk:"provider_ref"`
	URL      types.String `tfsdk:"url"`
}

// TunnelParamsIpsecIpsecPskClearSecretInfoModelAttrTypes defines the attribute types for TunnelParamsIpsecIpsecPskClearSecretInfoModel
var TunnelParamsIpsecIpsecPskClearSecretInfoModelAttrTypes = map[string]attr.Type{
	"provider_ref": types.StringType,
	"url":          types.StringType,
}

// TunnelRemoteIPModel represents remote_ip block
type TunnelRemoteIPModel struct {
	Endpoints *TunnelRemoteIPEndpointsModel `tfsdk:"endpoints"`
	IP        *TunnelRemoteIPIPModel        `tfsdk:"ip"`
}

// TunnelRemoteIPModelAttrTypes defines the attribute types for TunnelRemoteIPModel
var TunnelRemoteIPModelAttrTypes = map[string]attr.Type{
	"endpoints": types.ObjectType{AttrTypes: TunnelRemoteIPEndpointsModelAttrTypes},
	"ip":        types.ObjectType{AttrTypes: TunnelRemoteIPIPModelAttrTypes},
}

// TunnelRemoteIPEndpointsModel represents endpoints block
type TunnelRemoteIPEndpointsModel struct {
	Endpoints *TunnelEmptyModel `tfsdk:"endpoints"`
}

// TunnelRemoteIPEndpointsModelAttrTypes defines the attribute types for TunnelRemoteIPEndpointsModel
var TunnelRemoteIPEndpointsModelAttrTypes = map[string]attr.Type{
	"endpoints": types.ObjectType{AttrTypes: map[string]attr.Type{}},
}

// TunnelRemoteIPIPModel represents ip block
type TunnelRemoteIPIPModel struct {
	Ipv4 *TunnelRemoteIPIPIpv4Model `tfsdk:"ipv4"`
	Ipv6 *TunnelRemoteIPIPIpv6Model `tfsdk:"ipv6"`
}

// TunnelRemoteIPIPModelAttrTypes defines the attribute types for TunnelRemoteIPIPModel
var TunnelRemoteIPIPModelAttrTypes = map[string]attr.Type{
	"ipv4": types.ObjectType{AttrTypes: TunnelRemoteIPIPIpv4ModelAttrTypes},
	"ipv6": types.ObjectType{AttrTypes: TunnelRemoteIPIPIpv6ModelAttrTypes},
}

// TunnelRemoteIPIPIpv4Model represents ipv4 block
type TunnelRemoteIPIPIpv4Model struct {
	Addr types.String `tfsdk:"addr"`
}

// TunnelRemoteIPIPIpv4ModelAttrTypes defines the attribute types for TunnelRemoteIPIPIpv4Model
var TunnelRemoteIPIPIpv4ModelAttrTypes = map[string]attr.Type{
	"addr": types.StringType,
}

// TunnelRemoteIPIPIpv6Model represents ipv6 block
type TunnelRemoteIPIPIpv6Model struct {
	Addr types.String `tfsdk:"addr"`
}

// TunnelRemoteIPIPIpv6ModelAttrTypes defines the attribute types for TunnelRemoteIPIPIpv6Model
var TunnelRemoteIPIPIpv6ModelAttrTypes = map[string]attr.Type{
	"addr": types.StringType,
}

type TunnelResourceModel struct {
	Name        types.String         `tfsdk:"name"`
	Namespace   types.String         `tfsdk:"namespace"`
	Annotations types.Map            `tfsdk:"annotations"`
	Description types.String         `tfsdk:"description"`
	Disable     types.Bool           `tfsdk:"disable"`
	Labels      types.Map            `tfsdk:"labels"`
	ID          types.String         `tfsdk:"id"`
	TunnelType  types.String         `tfsdk:"tunnel_type"`
	Timeouts    timeouts.Value       `tfsdk:"timeouts"`
	LocalIP     *TunnelLocalIPModel  `tfsdk:"local_ip"`
	Params      *TunnelParamsModel   `tfsdk:"params"`
	RemoteIP    *TunnelRemoteIPModel `tfsdk:"remote_ip"`
}

func (r *TunnelResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tunnel"
}

func (r *TunnelResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages tunnel in a given namespace. If one already exist it will give a error. in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the Tunnel. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the Tunnel will be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"tunnel_type": schema.StringAttribute{
				MarkdownDescription: "[Enum: IPSEC_PSK|GRE] Supported tunnel types are IPsec IPsec tunnel type with PSK GRE tunnel type. Possible values are `IPSEC_PSK`, `GRE`. Defaults to `IPSEC_PSK`.",
				Required:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("IPSEC_PSK", "GRE"),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"local_ip": schema.SingleNestedBlock{
				MarkdownDescription: "Defines the OPTIONS to select local IP address and virtual network for tunnel object OPTIONS available are - 1. Local Interface - Network Interface from which IP address and network will be selected 2. IP Address - IP address and network can be configured explicitly.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"intf": schema.SingleNestedBlock{
						MarkdownDescription: "Provides the local interface to pick up source IP and network for transporting encapsulated packet.",
						Attributes:          map[string]schema.Attribute{},
						Blocks: map[string]schema.Block{
							"local_intf": schema.ListNestedBlock{
								MarkdownDescription: "Local interface to be used for filling in source information of IP and network for transport.",
								NestedObject: schema.NestedBlockObject{
									Attributes: map[string]schema.Attribute{
										"kind": schema.StringAttribute{
											MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then kind will hold the referred object's kind (e.g. 'route').",
											Computed:            true,
										},
										"name": schema.StringAttribute{
											MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
											Optional:            true,
										},
										"namespace": schema.StringAttribute{
											MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
											Optional:            true,
											Computed:            true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
											Validators: []validator.String{
												stringvalidator.LengthBetween(1, 63),
												stringvalidator.RegexMatches(regexp.MustCompile(`^[a-z]([-a-z0-9]*[a-z0-9])?$`), ""),
											},
										},
										"tenant": schema.StringAttribute{
											MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
											Computed:            true,
										},
										"uid": schema.StringAttribute{
											MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then uid will hold the referred object's(e.g. Route's) uid.",
											Computed:            true,
										},
									},
								},
							},
						},
					},
					"ip_address": schema.SingleNestedBlock{
						MarkdownDescription: "Provides the configuration to pick up source IP and network for transporting encapsulated packet.",
						Attributes:          map[string]schema.Attribute{},
						Blocks: map[string]schema.Block{
							"auto": schema.SingleNestedBlock{
								MarkdownDescription: "Enable this option",
							},
							"ip_address": schema.SingleNestedBlock{
								MarkdownDescription: "IP Address used to specify an IPv4 or IPv6 address.",
								Attributes:          map[string]schema.Attribute{},
								Blocks: map[string]schema.Block{
									"ipv4": schema.SingleNestedBlock{
										MarkdownDescription: "IPv4 address in dotted decimal notation (e.g., 192.0.2.1).",
										Attributes: map[string]schema.Attribute{
											"addr": schema.StringAttribute{
												MarkdownDescription: "IPv4 Address in string form with dot-decimal notation.",
												Optional:            true,
												Validators: []validator.String{
													stringvalidator.LengthAtMost(1024),
												},
											},
										},
									},
									"ipv6": schema.SingleNestedBlock{
										MarkdownDescription: "IPv6 Address specified as hexadecimal numbers separated by ':'.",
										Attributes: map[string]schema.Attribute{
											"addr": schema.StringAttribute{
												MarkdownDescription: "IPv6 Address in form of string. IPv6 address must be specified as hexadecimal numbers separated by ':' The address can be compacted by suppressing zeros e.g. '2001:db8:0:0:0:0:2:1' becomes '2001:db8::2:1' or '2001:db8:0:0:0:2:0:0' becomes '2001:db8::2::'.",
												Optional:            true,
												Validators: []validator.String{
													stringvalidator.LengthAtMost(1024),
												},
											},
										},
									},
								},
							},
							"virtual_network_type": schema.SingleNestedBlock{
								MarkdownDescription: "Different types of virtual networks understood by the system.",
								Attributes:          map[string]schema.Attribute{},
								Blocks: map[string]schema.Block{
									"public": schema.SingleNestedBlock{
										MarkdownDescription: "Enable this option",
									},
									"site_local": schema.SingleNestedBlock{
										MarkdownDescription: "Enable this option",
									},
									"site_local_inside": schema.SingleNestedBlock{
										MarkdownDescription: "Enable this option",
									},
								},
							},
						},
					},
				},
			},
			"params": schema.SingleNestedBlock{
				MarkdownDescription: "Tunnel configuration parameters for supported encapsulation 1. IPsec is supported with PSK for which PSK can be configured.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"ipsec": schema.SingleNestedBlock{
						MarkdownDescription: "Configuration for IPsec encapsulation are: 1. PSK - pre shared key to be used by IKE.",
						Attributes:          map[string]schema.Attribute{},
						Blocks: map[string]schema.Block{
							"ipsec_psk": schema.SingleNestedBlock{
								MarkdownDescription: "SecretType is used in an object to indicate a sensitive/confidential field.",
								Attributes:          map[string]schema.Attribute{},
								Blocks: map[string]schema.Block{
									"blindfold_secret_info": schema.SingleNestedBlock{
										MarkdownDescription: "BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management.",
										Attributes: map[string]schema.Attribute{
											"decryption_provider": schema.StringAttribute{
												MarkdownDescription: "Name of the Secret Management Access object that contains information about the backend Secret Management service.",
												Optional:            true,
											},
											"location": schema.StringAttribute{
												MarkdownDescription: "Location is the uri_ref. It could be in URL format for string:/// Or it could be a path if the store provider is an HTTP/HTTPS location .",
												Optional:            true,
												Validators: []validator.String{
													stringvalidator.LengthBetween(4, 131072),
												},
											},
											"store_provider": schema.StringAttribute{
												MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
												Optional:            true,
											},
										},
									},
									"clear_secret_info": schema.SingleNestedBlock{
										MarkdownDescription: "ClearSecretInfoType specifies information about the Secret that is not encrypted.",
										Attributes: map[string]schema.Attribute{
											"provider_ref": schema.StringAttribute{
												MarkdownDescription: "Name of the Secret Management Access object that contains information about the store to GET encrypted bytes This field needs to be provided only if the URL scheme is not string:///.",
												Optional:            true,
											},
											"url": schema.StringAttribute{
												MarkdownDescription: "URL of the secret. Currently supported URL schemes is string:///. For string:/// scheme, Secret needs to be encoded Base64 format. When asked for this secret, caller will GET Secret bytes after Base64 decoding.",
												Optional:            true,
												Validators: []validator.String{
													stringvalidator.LengthBetween(1, 131072),
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			"remote_ip": schema.SingleNestedBlock{
				MarkdownDescription: "Defines the OPTIONS to select remote IP address for tunnel object OPTIONS available are - 1. IP Address - Specifies the remote IP to which tunnel has to be connected 2. Remote endpoint - Is a map of IP address on per ver node basis.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"endpoints": schema.SingleNestedBlock{
						MarkdownDescription: "Provides a map of ver node name to remote node attributes Ver node should use these attributes to configure as remote tunnel.",
						Attributes:          map[string]schema.Attribute{},
						Blocks: map[string]schema.Block{
							"endpoints": schema.SingleNestedBlock{
								MarkdownDescription: "Map of remote attributes to which tunnel will be established on per site node basis Every node can have a different attributes and IP address to connect to Key is ver node name and value is Remote node attributes.",
							},
						},
					},
					"ip": schema.SingleNestedBlock{
						MarkdownDescription: "IP Address used to specify an IPv4 or IPv6 address.",
						Attributes:          map[string]schema.Attribute{},
						Blocks: map[string]schema.Block{
							"ipv4": schema.SingleNestedBlock{
								MarkdownDescription: "IPv4 address in dotted decimal notation (e.g., 192.0.2.1).",
								Attributes: map[string]schema.Attribute{
									"addr": schema.StringAttribute{
										MarkdownDescription: "IPv4 Address in string form with dot-decimal notation.",
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.LengthAtMost(1024),
										},
									},
								},
							},
							"ipv6": schema.SingleNestedBlock{
								MarkdownDescription: "IPv6 Address specified as hexadecimal numbers separated by ':'.",
								Attributes: map[string]schema.Attribute{
									"addr": schema.StringAttribute{
										MarkdownDescription: "IPv6 Address in form of string. IPv6 address must be specified as hexadecimal numbers separated by ':' The address can be compacted by suppressing zeros e.g. '2001:db8:0:0:0:0:2:1' becomes '2001:db8::2:1' or '2001:db8:0:0:0:2:0:0' becomes '2001:db8::2::'.",
										Optional:            true,
										Validators: []validator.String{
											stringvalidator.LengthAtMost(1024),
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *TunnelResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *TunnelResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data TunnelResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *TunnelResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the tunnel from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan TunnelResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *TunnelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data TunnelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating tunnel", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.Tunnel{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.LocalIP != nil {
		LocalIPMap := make(map[string]interface{})
		if data.LocalIP.Intf != nil {
			LocalIPIntfMap := make(map[string]interface{})
			if !data.LocalIP.Intf.LocalIntf.IsNull() && !data.LocalIP.Intf.LocalIntf.IsUnknown() {
				var LocalIntfElems []TunnelLocalIPIntfLocalIntfModel
				diags := data.LocalIP.Intf.LocalIntf.ElementsAs(ctx, &LocalIntfElems, false)
				resp.Diagnostics.Append(diags...)
				if !resp.Diagnostics.HasError() && len(LocalIntfElems) > 0 {
					var LocalIntfList []map[string]interface{}
					for _, LocalIntfItem := range LocalIntfElems {
						LocalIntfItemMap := make(map[string]interface{})
						if !LocalIntfItem.Kind.IsNull() && !LocalIntfItem.Kind.IsUnknown() {
							LocalIntfItemMap["kind"] = LocalIntfItem.Kind.ValueString()
						}
						if !LocalIntfItem.Name.IsNull() && !LocalIntfItem.Name.IsUnknown() {
							LocalIntfItemMap["name"] = LocalIntfItem.Name.ValueString()
						}
						if !LocalIntfItem.Namespace.IsNull() && !LocalIntfItem.Namespace.IsUnknown() {
							LocalIntfItemMap["namespace"] = LocalIntfItem.Namespace.ValueString()
						}
						if !LocalIntfItem.Tenant.IsNull() && !LocalIntfItem.Tenant.IsUnknown() {
							LocalIntfItemMap["tenant"] = LocalIntfItem.Tenant.ValueString()
						}
						if !LocalIntfItem.Uid.IsNull() && !LocalIntfItem.Uid.IsUnknown() {
							LocalIntfItemMap["uid"] = LocalIntfItem.Uid.ValueString()
						}
						LocalIntfList = append(LocalIntfList, LocalIntfItemMap)
					}
					LocalIPIntfMap["local_intf"] = LocalIntfList
				}
			}
			LocalIPMap["intf"] = LocalIPIntfMap
		}
		if data.LocalIP.IPAddress != nil {
			LocalIPIPAddressMap := make(map[string]interface{})
			if data.LocalIP.IPAddress.Auto != nil {
				LocalIPIPAddressMap["auto"] = map[string]interface{}{}
			}
			if data.LocalIP.IPAddress.IPAddress != nil {
				LocalIPIPAddressIPAddressMap := make(map[string]interface{})
				if data.LocalIP.IPAddress.IPAddress.Ipv4 != nil {
					LocalIPIPAddressIPAddressIpv4Map := make(map[string]interface{})
					if !data.LocalIP.IPAddress.IPAddress.Ipv4.Addr.IsNull() && !data.LocalIP.IPAddress.IPAddress.Ipv4.Addr.IsUnknown() {
						LocalIPIPAddressIPAddressIpv4Map["addr"] = data.LocalIP.IPAddress.IPAddress.Ipv4.Addr.ValueString()
					}
					LocalIPIPAddressIPAddressMap["ipv4"] = LocalIPIPAddressIPAddressIpv4Map
				}
				if data.LocalIP.IPAddress.IPAddress.Ipv6 != nil {
					LocalIPIPAddressIPAddressIpv6Map := make(map[string]interface{})
					if !data.LocalIP.IPAddress.IPAddress.Ipv6.Addr.IsNull() && !data.LocalIP.IPAddress.IPAddress.Ipv6.Addr.IsUnknown() {
						LocalIPIPAddressIPAddressIpv6Map["addr"] = data.LocalIP.IPAddress.IPAddress.Ipv6.Addr.ValueString()
					}
					LocalIPIPAddressIPAddressMap["ipv6"] = LocalIPIPAddressIPAddressIpv6Map
				}
				LocalIPIPAddressMap["ip_address"] = LocalIPIPAddressIPAddressMap
			}
			if data.LocalIP.IPAddress.VirtualNetworkType != nil {
				LocalIPIPAddressVirtualNetworkTypeMap := make(map[string]interface{})
				if data.LocalIP.IPAddress.VirtualNetworkType.Public != nil {
					LocalIPIPAddressVirtualNetworkTypeMap["public"] = map[string]interface{}{}
				}
				if data.LocalIP.IPAddress.VirtualNetworkType.SiteLocal != nil {
					LocalIPIPAddressVirtualNetworkTypeMap["site_local"] = map[string]interface{}{}
				}
				if data.LocalIP.IPAddress.VirtualNetworkType.SiteLocalInside != nil {
					LocalIPIPAddressVirtualNetworkTypeMap["site_local_inside"] = map[string]interface{}{}
				}
				LocalIPIPAddressMap["virtual_network_type"] = LocalIPIPAddressVirtualNetworkTypeMap
			}
			LocalIPMap["ip_address"] = LocalIPIPAddressMap
		}
		createReq.Spec["local_ip"] = LocalIPMap
	}
	if data.Params != nil {
		ParamsMap := make(map[string]interface{})
		if data.Params.Ipsec != nil {
			ParamsIpsecMap := make(map[string]interface{})
			if data.Params.Ipsec.IpsecPsk != nil {
				ParamsIpsecIpsecPskMap := make(map[string]interface{})
				if data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo != nil {
					ParamsIpsecIpsecPskBlindfoldSecretInfoMap := make(map[string]interface{})
					if !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.DecryptionProvider.IsNull() && !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.DecryptionProvider.IsUnknown() {
						ParamsIpsecIpsecPskBlindfoldSecretInfoMap["decryption_provider"] = data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.DecryptionProvider.ValueString()
					}
					if !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.Location.IsNull() && !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.Location.IsUnknown() {
						ParamsIpsecIpsecPskBlindfoldSecretInfoMap["location"] = data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.Location.ValueString()
					}
					if !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.StoreProvider.IsNull() && !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.StoreProvider.IsUnknown() {
						ParamsIpsecIpsecPskBlindfoldSecretInfoMap["store_provider"] = data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.StoreProvider.ValueString()
					}
					ParamsIpsecIpsecPskMap["blindfold_secret_info"] = ParamsIpsecIpsecPskBlindfoldSecretInfoMap
				}
				if data.Params.Ipsec.IpsecPsk.ClearSecretInfo != nil {
					ParamsIpsecIpsecPskClearSecretInfoMap := make(map[string]interface{})
					if !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.Provider.IsNull() && !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.Provider.IsUnknown() {
						ParamsIpsecIpsecPskClearSecretInfoMap["provider"] = data.Params.Ipsec.IpsecPsk.ClearSecretInfo.Provider.ValueString()
					}
					if !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.URL.IsNull() && !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.URL.IsUnknown() {
						ParamsIpsecIpsecPskClearSecretInfoMap["url"] = data.Params.Ipsec.IpsecPsk.ClearSecretInfo.URL.ValueString()
					}
					ParamsIpsecIpsecPskMap["clear_secret_info"] = ParamsIpsecIpsecPskClearSecretInfoMap
				}
				ParamsIpsecMap["ipsec_psk"] = ParamsIpsecIpsecPskMap
			}
			ParamsMap["ipsec"] = ParamsIpsecMap
		}
		createReq.Spec["params"] = ParamsMap
	}
	if data.RemoteIP != nil {
		RemoteIPMap := make(map[string]interface{})
		if data.RemoteIP.Endpoints != nil {
			RemoteIPEndpointsMap := make(map[string]interface{})
			if data.RemoteIP.Endpoints.Endpoints != nil {
				RemoteIPEndpointsMap["endpoints"] = map[string]interface{}{}
			}
			RemoteIPMap["endpoints"] = RemoteIPEndpointsMap
		}
		if data.RemoteIP.IP != nil {
			RemoteIPIPMap := make(map[string]interface{})
			if data.RemoteIP.IP.Ipv4 != nil {
				RemoteIPIPIpv4Map := make(map[string]interface{})
				if !data.RemoteIP.IP.Ipv4.Addr.IsNull() && !data.RemoteIP.IP.Ipv4.Addr.IsUnknown() {
					RemoteIPIPIpv4Map["addr"] = data.RemoteIP.IP.Ipv4.Addr.ValueString()
				}
				RemoteIPIPMap["ipv4"] = RemoteIPIPIpv4Map
			}
			if data.RemoteIP.IP.Ipv6 != nil {
				RemoteIPIPIpv6Map := make(map[string]interface{})
				if !data.RemoteIP.IP.Ipv6.Addr.IsNull() && !data.RemoteIP.IP.Ipv6.Addr.IsUnknown() {
					RemoteIPIPIpv6Map["addr"] = data.RemoteIP.IP.Ipv6.Addr.ValueString()
				}
				RemoteIPIPMap["ipv6"] = RemoteIPIPIpv6Map
			}
			RemoteIPMap["ip"] = RemoteIPIPMap
		}
		createReq.Spec["remote_ip"] = RemoteIPMap
	}
	if !data.TunnelType.IsNull() && !data.TunnelType.IsUnknown() {
		createReq.Spec["tunnel_type"] = data.TunnelType.ValueString()
	}

	apiResource, err := r.client.CreateTunnel(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create Tunnel: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if blockData, ok := apiResource.Spec["local_ip"].(map[string]interface{}); ok && (isImport || data.LocalIP != nil) {
		data.LocalIP = &TunnelLocalIPModel{
			Intf: func() *TunnelLocalIPIntfModel {
				if IntfData, ok := blockData["intf"].(map[string]interface{}); ok {
					return &TunnelLocalIPIntfModel{
						LocalIntf: func() types.List {
							if !isImport && data.LocalIP != nil && data.LocalIP.Intf != nil && (data.LocalIP.Intf.LocalIntf.IsNull() || len(data.LocalIP.Intf.LocalIntf.Elements()) == 0) {
								return types.ListNull(types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes})
							}
							var LocalIntfExisting []TunnelLocalIPIntfLocalIntfModel
							if !isImport && data.LocalIP != nil && data.LocalIP.Intf != nil && !data.LocalIP.Intf.LocalIntf.IsNull() && !data.LocalIP.Intf.LocalIntf.IsUnknown() {
								data.LocalIP.Intf.LocalIntf.ElementsAs(ctx, &LocalIntfExisting, false)
							}
							if rawList, ok := IntfData["local_intf"].([]interface{}); ok && len(rawList) > 0 {
								var LocalIntfResult []TunnelLocalIPIntfLocalIntfModel
								for LocalIntfIdx, LocalIntfItem := range rawList {
									_ = LocalIntfIdx
									if LocalIntfItemMap, ok := LocalIntfItem.(map[string]interface{}); ok {
										LocalIntfResult = append(LocalIntfResult, TunnelLocalIPIntfLocalIntfModel{
											Kind: func() types.String {
												if v, ok := LocalIntfItemMap["kind"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Name: func() types.String {
												if v, ok := LocalIntfItemMap["name"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Namespace: func() types.String {
												if v, ok := LocalIntfItemMap["namespace"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Tenant: func() types.String {
												if v, ok := LocalIntfItemMap["tenant"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Uid: func() types.String {
												if v, ok := LocalIntfItemMap["uid"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
										})
									}
								}
								listVal, _ := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes}, LocalIntfResult)
								return listVal
							}
							return types.ListNull(types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes})
						}(),
					}
				}
				return nil
			}(),
			IPAddress: func() *TunnelLocalIPIPAddressModel {
				if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil {
					return data.LocalIP.IPAddress
				}
				if IPAddressData, ok := blockData["ip_address"].(map[string]interface{}); ok {
					return &TunnelLocalIPIPAddressModel{
						Auto: func() *TunnelEmptyModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil {
								return data.LocalIP.IPAddress.Auto
							}
							if _, ok := IPAddressData["auto"].(map[string]interface{}); ok {
								return &TunnelEmptyModel{}
							}
							return nil
						}(),
						IPAddress: func() *TunnelLocalIPIPAddressIPAddressModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil {
								return data.LocalIP.IPAddress.IPAddress
							}
							if IPAddressData, ok := IPAddressData["ip_address"].(map[string]interface{}); ok {
								return &TunnelLocalIPIPAddressIPAddressModel{
									Ipv4: func() *TunnelLocalIPIPAddressIPAddressIpv4Model {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil && data.LocalIP.IPAddress.IPAddress.Ipv4 != nil {
											return data.LocalIP.IPAddress.IPAddress.Ipv4
										}
										if Ipv4Data, ok := IPAddressData["ipv4"].(map[string]interface{}); ok {
											return &TunnelLocalIPIPAddressIPAddressIpv4Model{
												Addr: func() types.String {
													if v, ok := Ipv4Data["addr"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
									Ipv6: func() *TunnelLocalIPIPAddressIPAddressIpv6Model {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil && data.LocalIP.IPAddress.IPAddress.Ipv6 != nil {
											return data.LocalIP.IPAddress.IPAddress.Ipv6
										}
										if Ipv6Data, ok := IPAddressData["ipv6"].(map[string]interface{}); ok {
											return &TunnelLocalIPIPAddressIPAddressIpv6Model{
												Addr: func() types.String {
													if v, ok := Ipv6Data["addr"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
						VirtualNetworkType: func() *TunnelLocalIPIPAddressVirtualNetworkTypeModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
								return data.LocalIP.IPAddress.VirtualNetworkType
							}
							if VirtualNetworkTypeData, ok := IPAddressData["virtual_network_type"].(map[string]interface{}); ok {
								return &TunnelLocalIPIPAddressVirtualNetworkTypeModel{
									Public: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.Public
										}
										if _, ok := VirtualNetworkTypeData["public"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
									SiteLocal: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.SiteLocal
										}
										if _, ok := VirtualNetworkTypeData["site_local"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
									SiteLocalInside: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.SiteLocalInside
										}
										if _, ok := VirtualNetworkTypeData["site_local_inside"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["params"].(map[string]interface{}); ok && (isImport || data.Params != nil) {
		data.Params = &TunnelParamsModel{
			Ipsec: func() *TunnelParamsIpsecModel {
				if !isImport && data.Params != nil && data.Params.Ipsec != nil {
					return data.Params.Ipsec
				}
				if IpsecData, ok := blockData["ipsec"].(map[string]interface{}); ok {
					return &TunnelParamsIpsecModel{
						IpsecPsk: func() *TunnelParamsIpsecIpsecPskModel {
							if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil {
								return data.Params.Ipsec.IpsecPsk
							}
							if IpsecPskData, ok := IpsecData["ipsec_psk"].(map[string]interface{}); ok {
								return &TunnelParamsIpsecIpsecPskModel{
									BlindfoldSecretInfo: func() *TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel {
										if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil && data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo != nil {
											return data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo
										}
										if BlindfoldSecretInfoData, ok := IpsecPskData["blindfold_secret_info"].(map[string]interface{}); ok {
											return &TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel{
												DecryptionProvider: func() types.String {
													if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												Location: func() types.String {
													if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												StoreProvider: func() types.String {
													if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
									ClearSecretInfo: func() *TunnelParamsIpsecIpsecPskClearSecretInfoModel {
										if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil && data.Params.Ipsec.IpsecPsk.ClearSecretInfo != nil {
											return data.Params.Ipsec.IpsecPsk.ClearSecretInfo
										}
										if ClearSecretInfoData, ok := IpsecPskData["clear_secret_info"].(map[string]interface{}); ok {
											return &TunnelParamsIpsecIpsecPskClearSecretInfoModel{
												Provider: func() types.String {
													if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												URL: func() types.String {
													if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["remote_ip"].(map[string]interface{}); ok && (isImport || data.RemoteIP != nil) {
		data.RemoteIP = &TunnelRemoteIPModel{
			Endpoints: func() *TunnelRemoteIPEndpointsModel {
				if !isImport && data.RemoteIP != nil && data.RemoteIP.Endpoints != nil {
					return data.RemoteIP.Endpoints
				}
				if EndpointsData, ok := blockData["endpoints"].(map[string]interface{}); ok {
					return &TunnelRemoteIPEndpointsModel{
						Endpoints: func() *TunnelEmptyModel {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.Endpoints != nil {
								return data.RemoteIP.Endpoints.Endpoints
							}
							if _, ok := EndpointsData["endpoints"].(map[string]interface{}); ok {
								return &TunnelEmptyModel{}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
			IP: func() *TunnelRemoteIPIPModel {
				if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil {
					return data.RemoteIP.IP
				}
				if IPData, ok := blockData["ip"].(map[string]interface{}); ok {
					return &TunnelRemoteIPIPModel{
						Ipv4: func() *TunnelRemoteIPIPIpv4Model {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil && data.RemoteIP.IP.Ipv4 != nil {
								return data.RemoteIP.IP.Ipv4
							}
							if Ipv4Data, ok := IPData["ipv4"].(map[string]interface{}); ok {
								return &TunnelRemoteIPIPIpv4Model{
									Addr: func() types.String {
										if v, ok := Ipv4Data["addr"].(string); ok && v != "" {
											return types.StringValue(v)
										}
										return types.StringNull()
									}(),
								}
							}
							return nil
						}(),
						Ipv6: func() *TunnelRemoteIPIPIpv6Model {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil && data.RemoteIP.IP.Ipv6 != nil {
								return data.RemoteIP.IP.Ipv6
							}
							if Ipv6Data, ok := IPData["ipv6"].(map[string]interface{}); ok {
								return &TunnelRemoteIPIPIpv6Model{
									Addr: func() types.String {
										if v, ok := Ipv6Data["addr"].(string); ok && v != "" {
											return types.StringValue(v)
										}
										return types.StringNull()
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if v, ok := apiResource.Spec["tunnel_type"].(string); ok && v != "" {
		data.TunnelType = types.StringValue(v)
	} else {
		data.TunnelType = types.StringNull()
	}

	tflog.Trace(ctx, "created Tunnel resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TunnelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data TunnelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetTunnel(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "Tunnel not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		// Some F5 XC APIs do not implement GET-by-name (read returns 501 Not
		// Implemented — e.g. the shape/csd domain objects, which support only
		// list/create/delete). Treat that as "cannot refresh" and preserve the
		// prior state rather than erroring, so the resource stays manageable and
		// idempotent (create/delete still work).
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "Tunnel read not implemented by API (501); keeping prior state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read Tunnel: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if blockData, ok := apiResource.Spec["local_ip"].(map[string]interface{}); ok && (isImport || data.LocalIP != nil) {
		data.LocalIP = &TunnelLocalIPModel{
			Intf: func() *TunnelLocalIPIntfModel {
				if IntfData, ok := blockData["intf"].(map[string]interface{}); ok {
					return &TunnelLocalIPIntfModel{
						LocalIntf: func() types.List {
							if !isImport && data.LocalIP != nil && data.LocalIP.Intf != nil && (data.LocalIP.Intf.LocalIntf.IsNull() || len(data.LocalIP.Intf.LocalIntf.Elements()) == 0) {
								return types.ListNull(types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes})
							}
							var LocalIntfExisting []TunnelLocalIPIntfLocalIntfModel
							if !isImport && data.LocalIP != nil && data.LocalIP.Intf != nil && !data.LocalIP.Intf.LocalIntf.IsNull() && !data.LocalIP.Intf.LocalIntf.IsUnknown() {
								data.LocalIP.Intf.LocalIntf.ElementsAs(ctx, &LocalIntfExisting, false)
							}
							if rawList, ok := IntfData["local_intf"].([]interface{}); ok && len(rawList) > 0 {
								var LocalIntfResult []TunnelLocalIPIntfLocalIntfModel
								for LocalIntfIdx, LocalIntfItem := range rawList {
									_ = LocalIntfIdx
									if LocalIntfItemMap, ok := LocalIntfItem.(map[string]interface{}); ok {
										LocalIntfResult = append(LocalIntfResult, TunnelLocalIPIntfLocalIntfModel{
											Kind: func() types.String {
												if v, ok := LocalIntfItemMap["kind"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Name: func() types.String {
												if v, ok := LocalIntfItemMap["name"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Namespace: func() types.String {
												if v, ok := LocalIntfItemMap["namespace"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Tenant: func() types.String {
												if v, ok := LocalIntfItemMap["tenant"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Uid: func() types.String {
												if v, ok := LocalIntfItemMap["uid"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
										})
									}
								}
								listVal, _ := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes}, LocalIntfResult)
								return listVal
							}
							return types.ListNull(types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes})
						}(),
					}
				}
				return nil
			}(),
			IPAddress: func() *TunnelLocalIPIPAddressModel {
				if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil {
					return data.LocalIP.IPAddress
				}
				if IPAddressData, ok := blockData["ip_address"].(map[string]interface{}); ok {
					return &TunnelLocalIPIPAddressModel{
						Auto: func() *TunnelEmptyModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil {
								return data.LocalIP.IPAddress.Auto
							}
							if _, ok := IPAddressData["auto"].(map[string]interface{}); ok {
								return &TunnelEmptyModel{}
							}
							return nil
						}(),
						IPAddress: func() *TunnelLocalIPIPAddressIPAddressModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil {
								return data.LocalIP.IPAddress.IPAddress
							}
							if IPAddressData, ok := IPAddressData["ip_address"].(map[string]interface{}); ok {
								return &TunnelLocalIPIPAddressIPAddressModel{
									Ipv4: func() *TunnelLocalIPIPAddressIPAddressIpv4Model {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil && data.LocalIP.IPAddress.IPAddress.Ipv4 != nil {
											return data.LocalIP.IPAddress.IPAddress.Ipv4
										}
										if Ipv4Data, ok := IPAddressData["ipv4"].(map[string]interface{}); ok {
											return &TunnelLocalIPIPAddressIPAddressIpv4Model{
												Addr: func() types.String {
													if v, ok := Ipv4Data["addr"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
									Ipv6: func() *TunnelLocalIPIPAddressIPAddressIpv6Model {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil && data.LocalIP.IPAddress.IPAddress.Ipv6 != nil {
											return data.LocalIP.IPAddress.IPAddress.Ipv6
										}
										if Ipv6Data, ok := IPAddressData["ipv6"].(map[string]interface{}); ok {
											return &TunnelLocalIPIPAddressIPAddressIpv6Model{
												Addr: func() types.String {
													if v, ok := Ipv6Data["addr"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
						VirtualNetworkType: func() *TunnelLocalIPIPAddressVirtualNetworkTypeModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
								return data.LocalIP.IPAddress.VirtualNetworkType
							}
							if VirtualNetworkTypeData, ok := IPAddressData["virtual_network_type"].(map[string]interface{}); ok {
								return &TunnelLocalIPIPAddressVirtualNetworkTypeModel{
									Public: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.Public
										}
										if _, ok := VirtualNetworkTypeData["public"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
									SiteLocal: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.SiteLocal
										}
										if _, ok := VirtualNetworkTypeData["site_local"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
									SiteLocalInside: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.SiteLocalInside
										}
										if _, ok := VirtualNetworkTypeData["site_local_inside"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["params"].(map[string]interface{}); ok && (isImport || data.Params != nil) {
		data.Params = &TunnelParamsModel{
			Ipsec: func() *TunnelParamsIpsecModel {
				if !isImport && data.Params != nil && data.Params.Ipsec != nil {
					return data.Params.Ipsec
				}
				if IpsecData, ok := blockData["ipsec"].(map[string]interface{}); ok {
					return &TunnelParamsIpsecModel{
						IpsecPsk: func() *TunnelParamsIpsecIpsecPskModel {
							if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil {
								return data.Params.Ipsec.IpsecPsk
							}
							if IpsecPskData, ok := IpsecData["ipsec_psk"].(map[string]interface{}); ok {
								return &TunnelParamsIpsecIpsecPskModel{
									BlindfoldSecretInfo: func() *TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel {
										if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil && data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo != nil {
											return data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo
										}
										if BlindfoldSecretInfoData, ok := IpsecPskData["blindfold_secret_info"].(map[string]interface{}); ok {
											return &TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel{
												DecryptionProvider: func() types.String {
													if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												Location: func() types.String {
													if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												StoreProvider: func() types.String {
													if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
									ClearSecretInfo: func() *TunnelParamsIpsecIpsecPskClearSecretInfoModel {
										if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil && data.Params.Ipsec.IpsecPsk.ClearSecretInfo != nil {
											return data.Params.Ipsec.IpsecPsk.ClearSecretInfo
										}
										if ClearSecretInfoData, ok := IpsecPskData["clear_secret_info"].(map[string]interface{}); ok {
											return &TunnelParamsIpsecIpsecPskClearSecretInfoModel{
												Provider: func() types.String {
													if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												URL: func() types.String {
													if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["remote_ip"].(map[string]interface{}); ok && (isImport || data.RemoteIP != nil) {
		data.RemoteIP = &TunnelRemoteIPModel{
			Endpoints: func() *TunnelRemoteIPEndpointsModel {
				if !isImport && data.RemoteIP != nil && data.RemoteIP.Endpoints != nil {
					return data.RemoteIP.Endpoints
				}
				if EndpointsData, ok := blockData["endpoints"].(map[string]interface{}); ok {
					return &TunnelRemoteIPEndpointsModel{
						Endpoints: func() *TunnelEmptyModel {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.Endpoints != nil {
								return data.RemoteIP.Endpoints.Endpoints
							}
							if _, ok := EndpointsData["endpoints"].(map[string]interface{}); ok {
								return &TunnelEmptyModel{}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
			IP: func() *TunnelRemoteIPIPModel {
				if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil {
					return data.RemoteIP.IP
				}
				if IPData, ok := blockData["ip"].(map[string]interface{}); ok {
					return &TunnelRemoteIPIPModel{
						Ipv4: func() *TunnelRemoteIPIPIpv4Model {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil && data.RemoteIP.IP.Ipv4 != nil {
								return data.RemoteIP.IP.Ipv4
							}
							if Ipv4Data, ok := IPData["ipv4"].(map[string]interface{}); ok {
								return &TunnelRemoteIPIPIpv4Model{
									Addr: func() types.String {
										if v, ok := Ipv4Data["addr"].(string); ok && v != "" {
											return types.StringValue(v)
										}
										return types.StringNull()
									}(),
								}
							}
							return nil
						}(),
						Ipv6: func() *TunnelRemoteIPIPIpv6Model {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil && data.RemoteIP.IP.Ipv6 != nil {
								return data.RemoteIP.IP.Ipv6
							}
							if Ipv6Data, ok := IPData["ipv6"].(map[string]interface{}); ok {
								return &TunnelRemoteIPIPIpv6Model{
									Addr: func() types.String {
										if v, ok := Ipv6Data["addr"].(string); ok && v != "" {
											return types.StringValue(v)
										}
										return types.StringNull()
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if v, ok := apiResource.Spec["tunnel_type"].(string); ok && v != "" {
		data.TunnelType = types.StringValue(v)
	} else {
		data.TunnelType = types.StringNull()
	}

	// The import marker is a one-shot signal for the import Read only. Clear it so every
	// subsequent refresh runs as a normal Read with drift-preservation; otherwise the
	// resource stays in "import mode" forever and re-reads server-managed fields the user
	// never configured, producing perpetual plan drift.
	if isImport {
		resp.Diagnostics.Append(resp.Private.SetKey(ctx, "isImport", nil)...)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TunnelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data TunnelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.Tunnel{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.LocalIP != nil {
		LocalIPMap := make(map[string]interface{})
		if data.LocalIP.Intf != nil {
			LocalIPIntfMap := make(map[string]interface{})
			if !data.LocalIP.Intf.LocalIntf.IsNull() && !data.LocalIP.Intf.LocalIntf.IsUnknown() {
				var LocalIntfElems []TunnelLocalIPIntfLocalIntfModel
				diags := data.LocalIP.Intf.LocalIntf.ElementsAs(ctx, &LocalIntfElems, false)
				resp.Diagnostics.Append(diags...)
				if !resp.Diagnostics.HasError() && len(LocalIntfElems) > 0 {
					var LocalIntfList []map[string]interface{}
					for _, LocalIntfItem := range LocalIntfElems {
						LocalIntfItemMap := make(map[string]interface{})
						if !LocalIntfItem.Kind.IsNull() && !LocalIntfItem.Kind.IsUnknown() {
							LocalIntfItemMap["kind"] = LocalIntfItem.Kind.ValueString()
						}
						if !LocalIntfItem.Name.IsNull() && !LocalIntfItem.Name.IsUnknown() {
							LocalIntfItemMap["name"] = LocalIntfItem.Name.ValueString()
						}
						if !LocalIntfItem.Namespace.IsNull() && !LocalIntfItem.Namespace.IsUnknown() {
							LocalIntfItemMap["namespace"] = LocalIntfItem.Namespace.ValueString()
						}
						if !LocalIntfItem.Tenant.IsNull() && !LocalIntfItem.Tenant.IsUnknown() {
							LocalIntfItemMap["tenant"] = LocalIntfItem.Tenant.ValueString()
						}
						if !LocalIntfItem.Uid.IsNull() && !LocalIntfItem.Uid.IsUnknown() {
							LocalIntfItemMap["uid"] = LocalIntfItem.Uid.ValueString()
						}
						LocalIntfList = append(LocalIntfList, LocalIntfItemMap)
					}
					LocalIPIntfMap["local_intf"] = LocalIntfList
				}
			}
			LocalIPMap["intf"] = LocalIPIntfMap
		}
		if data.LocalIP.IPAddress != nil {
			LocalIPIPAddressMap := make(map[string]interface{})
			if data.LocalIP.IPAddress.Auto != nil {
				LocalIPIPAddressMap["auto"] = map[string]interface{}{}
			}
			if data.LocalIP.IPAddress.IPAddress != nil {
				LocalIPIPAddressIPAddressMap := make(map[string]interface{})
				if data.LocalIP.IPAddress.IPAddress.Ipv4 != nil {
					LocalIPIPAddressIPAddressIpv4Map := make(map[string]interface{})
					if !data.LocalIP.IPAddress.IPAddress.Ipv4.Addr.IsNull() && !data.LocalIP.IPAddress.IPAddress.Ipv4.Addr.IsUnknown() {
						LocalIPIPAddressIPAddressIpv4Map["addr"] = data.LocalIP.IPAddress.IPAddress.Ipv4.Addr.ValueString()
					}
					LocalIPIPAddressIPAddressMap["ipv4"] = LocalIPIPAddressIPAddressIpv4Map
				}
				if data.LocalIP.IPAddress.IPAddress.Ipv6 != nil {
					LocalIPIPAddressIPAddressIpv6Map := make(map[string]interface{})
					if !data.LocalIP.IPAddress.IPAddress.Ipv6.Addr.IsNull() && !data.LocalIP.IPAddress.IPAddress.Ipv6.Addr.IsUnknown() {
						LocalIPIPAddressIPAddressIpv6Map["addr"] = data.LocalIP.IPAddress.IPAddress.Ipv6.Addr.ValueString()
					}
					LocalIPIPAddressIPAddressMap["ipv6"] = LocalIPIPAddressIPAddressIpv6Map
				}
				LocalIPIPAddressMap["ip_address"] = LocalIPIPAddressIPAddressMap
			}
			if data.LocalIP.IPAddress.VirtualNetworkType != nil {
				LocalIPIPAddressVirtualNetworkTypeMap := make(map[string]interface{})
				if data.LocalIP.IPAddress.VirtualNetworkType.Public != nil {
					LocalIPIPAddressVirtualNetworkTypeMap["public"] = map[string]interface{}{}
				}
				if data.LocalIP.IPAddress.VirtualNetworkType.SiteLocal != nil {
					LocalIPIPAddressVirtualNetworkTypeMap["site_local"] = map[string]interface{}{}
				}
				if data.LocalIP.IPAddress.VirtualNetworkType.SiteLocalInside != nil {
					LocalIPIPAddressVirtualNetworkTypeMap["site_local_inside"] = map[string]interface{}{}
				}
				LocalIPIPAddressMap["virtual_network_type"] = LocalIPIPAddressVirtualNetworkTypeMap
			}
			LocalIPMap["ip_address"] = LocalIPIPAddressMap
		}
		apiResource.Spec["local_ip"] = LocalIPMap
	}
	if data.Params != nil {
		ParamsMap := make(map[string]interface{})
		if data.Params.Ipsec != nil {
			ParamsIpsecMap := make(map[string]interface{})
			if data.Params.Ipsec.IpsecPsk != nil {
				ParamsIpsecIpsecPskMap := make(map[string]interface{})
				if data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo != nil {
					ParamsIpsecIpsecPskBlindfoldSecretInfoMap := make(map[string]interface{})
					if !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.DecryptionProvider.IsNull() && !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.DecryptionProvider.IsUnknown() {
						ParamsIpsecIpsecPskBlindfoldSecretInfoMap["decryption_provider"] = data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.DecryptionProvider.ValueString()
					}
					if !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.Location.IsNull() && !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.Location.IsUnknown() {
						ParamsIpsecIpsecPskBlindfoldSecretInfoMap["location"] = data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.Location.ValueString()
					}
					if !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.StoreProvider.IsNull() && !data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.StoreProvider.IsUnknown() {
						ParamsIpsecIpsecPskBlindfoldSecretInfoMap["store_provider"] = data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo.StoreProvider.ValueString()
					}
					ParamsIpsecIpsecPskMap["blindfold_secret_info"] = ParamsIpsecIpsecPskBlindfoldSecretInfoMap
				}
				if data.Params.Ipsec.IpsecPsk.ClearSecretInfo != nil {
					ParamsIpsecIpsecPskClearSecretInfoMap := make(map[string]interface{})
					if !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.Provider.IsNull() && !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.Provider.IsUnknown() {
						ParamsIpsecIpsecPskClearSecretInfoMap["provider"] = data.Params.Ipsec.IpsecPsk.ClearSecretInfo.Provider.ValueString()
					}
					if !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.URL.IsNull() && !data.Params.Ipsec.IpsecPsk.ClearSecretInfo.URL.IsUnknown() {
						ParamsIpsecIpsecPskClearSecretInfoMap["url"] = data.Params.Ipsec.IpsecPsk.ClearSecretInfo.URL.ValueString()
					}
					ParamsIpsecIpsecPskMap["clear_secret_info"] = ParamsIpsecIpsecPskClearSecretInfoMap
				}
				ParamsIpsecMap["ipsec_psk"] = ParamsIpsecIpsecPskMap
			}
			ParamsMap["ipsec"] = ParamsIpsecMap
		}
		apiResource.Spec["params"] = ParamsMap
	}
	if data.RemoteIP != nil {
		RemoteIPMap := make(map[string]interface{})
		if data.RemoteIP.Endpoints != nil {
			RemoteIPEndpointsMap := make(map[string]interface{})
			if data.RemoteIP.Endpoints.Endpoints != nil {
				RemoteIPEndpointsMap["endpoints"] = map[string]interface{}{}
			}
			RemoteIPMap["endpoints"] = RemoteIPEndpointsMap
		}
		if data.RemoteIP.IP != nil {
			RemoteIPIPMap := make(map[string]interface{})
			if data.RemoteIP.IP.Ipv4 != nil {
				RemoteIPIPIpv4Map := make(map[string]interface{})
				if !data.RemoteIP.IP.Ipv4.Addr.IsNull() && !data.RemoteIP.IP.Ipv4.Addr.IsUnknown() {
					RemoteIPIPIpv4Map["addr"] = data.RemoteIP.IP.Ipv4.Addr.ValueString()
				}
				RemoteIPIPMap["ipv4"] = RemoteIPIPIpv4Map
			}
			if data.RemoteIP.IP.Ipv6 != nil {
				RemoteIPIPIpv6Map := make(map[string]interface{})
				if !data.RemoteIP.IP.Ipv6.Addr.IsNull() && !data.RemoteIP.IP.Ipv6.Addr.IsUnknown() {
					RemoteIPIPIpv6Map["addr"] = data.RemoteIP.IP.Ipv6.Addr.ValueString()
				}
				RemoteIPIPMap["ipv6"] = RemoteIPIPIpv6Map
			}
			RemoteIPMap["ip"] = RemoteIPIPMap
		}
		apiResource.Spec["remote_ip"] = RemoteIPMap
	}
	if !data.TunnelType.IsNull() && !data.TunnelType.IsUnknown() {
		apiResource.Spec["tunnel_type"] = data.TunnelType.ValueString()
	}

	_, err := r.client.UpdateTunnel(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update Tunnel: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetTunnel(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read Tunnel after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if blockData, ok := apiResource.Spec["local_ip"].(map[string]interface{}); ok && (isImport || data.LocalIP != nil) {
		data.LocalIP = &TunnelLocalIPModel{
			Intf: func() *TunnelLocalIPIntfModel {
				if IntfData, ok := blockData["intf"].(map[string]interface{}); ok {
					return &TunnelLocalIPIntfModel{
						LocalIntf: func() types.List {
							if !isImport && data.LocalIP != nil && data.LocalIP.Intf != nil && (data.LocalIP.Intf.LocalIntf.IsNull() || len(data.LocalIP.Intf.LocalIntf.Elements()) == 0) {
								return types.ListNull(types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes})
							}
							var LocalIntfExisting []TunnelLocalIPIntfLocalIntfModel
							if !isImport && data.LocalIP != nil && data.LocalIP.Intf != nil && !data.LocalIP.Intf.LocalIntf.IsNull() && !data.LocalIP.Intf.LocalIntf.IsUnknown() {
								data.LocalIP.Intf.LocalIntf.ElementsAs(ctx, &LocalIntfExisting, false)
							}
							if rawList, ok := IntfData["local_intf"].([]interface{}); ok && len(rawList) > 0 {
								var LocalIntfResult []TunnelLocalIPIntfLocalIntfModel
								for LocalIntfIdx, LocalIntfItem := range rawList {
									_ = LocalIntfIdx
									if LocalIntfItemMap, ok := LocalIntfItem.(map[string]interface{}); ok {
										LocalIntfResult = append(LocalIntfResult, TunnelLocalIPIntfLocalIntfModel{
											Kind: func() types.String {
												if v, ok := LocalIntfItemMap["kind"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Name: func() types.String {
												if v, ok := LocalIntfItemMap["name"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Namespace: func() types.String {
												if v, ok := LocalIntfItemMap["namespace"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Tenant: func() types.String {
												if v, ok := LocalIntfItemMap["tenant"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
											Uid: func() types.String {
												if v, ok := LocalIntfItemMap["uid"].(string); ok && v != "" {
													return types.StringValue(v)
												}
												return types.StringNull()
											}(),
										})
									}
								}
								listVal, _ := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes}, LocalIntfResult)
								return listVal
							}
							return types.ListNull(types.ObjectType{AttrTypes: TunnelLocalIPIntfLocalIntfModelAttrTypes})
						}(),
					}
				}
				return nil
			}(),
			IPAddress: func() *TunnelLocalIPIPAddressModel {
				if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil {
					return data.LocalIP.IPAddress
				}
				if IPAddressData, ok := blockData["ip_address"].(map[string]interface{}); ok {
					return &TunnelLocalIPIPAddressModel{
						Auto: func() *TunnelEmptyModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil {
								return data.LocalIP.IPAddress.Auto
							}
							if _, ok := IPAddressData["auto"].(map[string]interface{}); ok {
								return &TunnelEmptyModel{}
							}
							return nil
						}(),
						IPAddress: func() *TunnelLocalIPIPAddressIPAddressModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil {
								return data.LocalIP.IPAddress.IPAddress
							}
							if IPAddressData, ok := IPAddressData["ip_address"].(map[string]interface{}); ok {
								return &TunnelLocalIPIPAddressIPAddressModel{
									Ipv4: func() *TunnelLocalIPIPAddressIPAddressIpv4Model {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil && data.LocalIP.IPAddress.IPAddress.Ipv4 != nil {
											return data.LocalIP.IPAddress.IPAddress.Ipv4
										}
										if Ipv4Data, ok := IPAddressData["ipv4"].(map[string]interface{}); ok {
											return &TunnelLocalIPIPAddressIPAddressIpv4Model{
												Addr: func() types.String {
													if v, ok := Ipv4Data["addr"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
									Ipv6: func() *TunnelLocalIPIPAddressIPAddressIpv6Model {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.IPAddress != nil && data.LocalIP.IPAddress.IPAddress.Ipv6 != nil {
											return data.LocalIP.IPAddress.IPAddress.Ipv6
										}
										if Ipv6Data, ok := IPAddressData["ipv6"].(map[string]interface{}); ok {
											return &TunnelLocalIPIPAddressIPAddressIpv6Model{
												Addr: func() types.String {
													if v, ok := Ipv6Data["addr"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
						VirtualNetworkType: func() *TunnelLocalIPIPAddressVirtualNetworkTypeModel {
							if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
								return data.LocalIP.IPAddress.VirtualNetworkType
							}
							if VirtualNetworkTypeData, ok := IPAddressData["virtual_network_type"].(map[string]interface{}); ok {
								return &TunnelLocalIPIPAddressVirtualNetworkTypeModel{
									Public: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.Public
										}
										if _, ok := VirtualNetworkTypeData["public"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
									SiteLocal: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.SiteLocal
										}
										if _, ok := VirtualNetworkTypeData["site_local"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
									SiteLocalInside: func() *TunnelEmptyModel {
										if !isImport && data.LocalIP != nil && data.LocalIP.IPAddress != nil && data.LocalIP.IPAddress.VirtualNetworkType != nil {
											return data.LocalIP.IPAddress.VirtualNetworkType.SiteLocalInside
										}
										if _, ok := VirtualNetworkTypeData["site_local_inside"].(map[string]interface{}); ok {
											return &TunnelEmptyModel{}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["params"].(map[string]interface{}); ok && (isImport || data.Params != nil) {
		data.Params = &TunnelParamsModel{
			Ipsec: func() *TunnelParamsIpsecModel {
				if !isImport && data.Params != nil && data.Params.Ipsec != nil {
					return data.Params.Ipsec
				}
				if IpsecData, ok := blockData["ipsec"].(map[string]interface{}); ok {
					return &TunnelParamsIpsecModel{
						IpsecPsk: func() *TunnelParamsIpsecIpsecPskModel {
							if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil {
								return data.Params.Ipsec.IpsecPsk
							}
							if IpsecPskData, ok := IpsecData["ipsec_psk"].(map[string]interface{}); ok {
								return &TunnelParamsIpsecIpsecPskModel{
									BlindfoldSecretInfo: func() *TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel {
										if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil && data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo != nil {
											return data.Params.Ipsec.IpsecPsk.BlindfoldSecretInfo
										}
										if BlindfoldSecretInfoData, ok := IpsecPskData["blindfold_secret_info"].(map[string]interface{}); ok {
											return &TunnelParamsIpsecIpsecPskBlindfoldSecretInfoModel{
												DecryptionProvider: func() types.String {
													if v, ok := BlindfoldSecretInfoData["decryption_provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												Location: func() types.String {
													if v, ok := BlindfoldSecretInfoData["location"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												StoreProvider: func() types.String {
													if v, ok := BlindfoldSecretInfoData["store_provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
									ClearSecretInfo: func() *TunnelParamsIpsecIpsecPskClearSecretInfoModel {
										if !isImport && data.Params != nil && data.Params.Ipsec != nil && data.Params.Ipsec.IpsecPsk != nil && data.Params.Ipsec.IpsecPsk.ClearSecretInfo != nil {
											return data.Params.Ipsec.IpsecPsk.ClearSecretInfo
										}
										if ClearSecretInfoData, ok := IpsecPskData["clear_secret_info"].(map[string]interface{}); ok {
											return &TunnelParamsIpsecIpsecPskClearSecretInfoModel{
												Provider: func() types.String {
													if v, ok := ClearSecretInfoData["provider"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
												URL: func() types.String {
													if v, ok := ClearSecretInfoData["url"].(string); ok && v != "" {
														return types.StringValue(v)
													}
													return types.StringNull()
												}(),
											}
										}
										return nil
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["remote_ip"].(map[string]interface{}); ok && (isImport || data.RemoteIP != nil) {
		data.RemoteIP = &TunnelRemoteIPModel{
			Endpoints: func() *TunnelRemoteIPEndpointsModel {
				if !isImport && data.RemoteIP != nil && data.RemoteIP.Endpoints != nil {
					return data.RemoteIP.Endpoints
				}
				if EndpointsData, ok := blockData["endpoints"].(map[string]interface{}); ok {
					return &TunnelRemoteIPEndpointsModel{
						Endpoints: func() *TunnelEmptyModel {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.Endpoints != nil {
								return data.RemoteIP.Endpoints.Endpoints
							}
							if _, ok := EndpointsData["endpoints"].(map[string]interface{}); ok {
								return &TunnelEmptyModel{}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
			IP: func() *TunnelRemoteIPIPModel {
				if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil {
					return data.RemoteIP.IP
				}
				if IPData, ok := blockData["ip"].(map[string]interface{}); ok {
					return &TunnelRemoteIPIPModel{
						Ipv4: func() *TunnelRemoteIPIPIpv4Model {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil && data.RemoteIP.IP.Ipv4 != nil {
								return data.RemoteIP.IP.Ipv4
							}
							if Ipv4Data, ok := IPData["ipv4"].(map[string]interface{}); ok {
								return &TunnelRemoteIPIPIpv4Model{
									Addr: func() types.String {
										if v, ok := Ipv4Data["addr"].(string); ok && v != "" {
											return types.StringValue(v)
										}
										return types.StringNull()
									}(),
								}
							}
							return nil
						}(),
						Ipv6: func() *TunnelRemoteIPIPIpv6Model {
							if !isImport && data.RemoteIP != nil && data.RemoteIP.IP != nil && data.RemoteIP.IP.Ipv6 != nil {
								return data.RemoteIP.IP.Ipv6
							}
							if Ipv6Data, ok := IPData["ipv6"].(map[string]interface{}); ok {
								return &TunnelRemoteIPIPIpv6Model{
									Addr: func() types.String {
										if v, ok := Ipv6Data["addr"].(string); ok && v != "" {
											return types.StringValue(v)
										}
										return types.StringNull()
									}(),
								}
							}
							return nil
						}(),
					}
				}
				return nil
			}(),
		}
	}
	if v, ok := apiResource.Spec["tunnel_type"].(string); ok && v != "" {
		data.TunnelType = types.StringValue(v)
	} else {
		data.TunnelType = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TunnelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data TunnelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

	// Delete with bounded retry on transient referential BAD_REQUEST: during teardown a
	// resource can briefly still be referenced by another object (a healthcheck by an origin
	// pool, an origin pool by a load balancer, etc.), which the API rejects with 400 until
	// the referrer is gone. NOT_FOUND/404 (already deleted) and 501 (delete unsupported) are
	// terminal and handled after the loop.
	var err error
	for attempt := 0; ; attempt++ {
		err = r.client.DeleteTunnel(ctx, data.Namespace.ValueString(), data.Name.ValueString())
		if err == nil {
			break
		}
		msg := err.Error()
		transient := (strings.Contains(msg, "400") || strings.Contains(msg, "BAD_REQUEST")) &&
			!strings.Contains(msg, "NOT_FOUND") && !strings.Contains(msg, "404") && !strings.Contains(msg, "501")
		if !transient || attempt >= 5 {
			break
		}
		tflog.Warn(ctx, "Tunnel delete hit transient BAD_REQUEST (likely still referenced); retrying", map[string]interface{}{
			"name":      data.Name.ValueString(),
			"namespace": data.Namespace.ValueString(),
			"attempt":   attempt + 1,
		})
		select {
		case <-ctx.Done():
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Timed out retrying delete of Tunnel (still referenced): %s", err))
			return
		case <-time.After(5 * time.Second):
		}
	}
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "Tunnel already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "Tunnel delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete Tunnel: %s", err))
		return
	}
}

func (r *TunnelResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
